Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-04, with the labels that each got.

#266 Tuskarr Buildings (GDC) - Godisen
  common/buildings/wc_tuskarr.txt
  localisation/wc_culture_buildings.csv
Labels: :page_facing_up: localization :pen:, :star: new feature :new:

#268 Sethrak Children
  gfx/characters/sethrak_child/sethrak_child_female.dds
  gfx/characters/sethrak_child/sethrak_child_male.dds
  interface/portraits/portraits_sethrak_sprites.gfx
Labels: :art: graphics :paintbrush:

#241 New Flags
  gfx/flags/c_edj.tga
  gfx/flags/c_ramkahen.tga
  gfx/flags/d_coldarra.tga
  gfx/flags/d_edj.tga
  gfx/flags/d_neferset.tga
  gfx/flags/d_ramkahen.tga
  gfx/flags/d_uldum.tga
  gfx/flags/k_sholazar_basin.tga
  gfx/flags/k_tanaris.tga
Labels: :art: graphics :paintbrush:

#302 Additional gamerules
  common/game_rules/000_wc_game_rules.txt
  events/job_chancellor.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :ice_cream: vanilla modification :icecream:, :star: new feature :new:, :wrench: bug fix :hammer:

#245 World Trees
  common/buildings/wc_druidic.txt
  common/buildings/wc_uniques.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/modifier_definitions/wc_class_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/religion_modifiers/wc_religion_modifiers.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_class_traits.txt
  decisions/HF_religious_decisions.txt
  decisions/settlement_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_realm_decisions.txt
  events/HF_religious_events.txt
  events/HF_warrior_lodge_mission_events.txt
  events/bankruptcy_events.txt
  events/game_rule_events.txt
  events/hf_african_flavor_events.txt
  events/hl_nomad_events.txt
  events/rebel_events.txt
  events/wc_class_events.txt
  events/wc_druidic_events.txt
  events/wc_race_events.txt
  events/wc_realm_events.txt
  events/wc_void_events.txt
  events/ze_war_chest_extortion.txt
  gfx/event_pictures/burning_world_tree.tga
  gfx/event_pictures/emerald_nightmare.tga
  gfx/event_pictures/world_tree.tga
  history/titles/b_nordrassil.txt
  interface/wc_event_pictures.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
  localisation/wc_uniques.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  localisation_rus/000_wc_religions.csv
Labels: :star: new feature :new:
