Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-10, with the labels that each got.

#768 Minor fixes to Arthas Third War chains
  events/wc_third_war_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#752 Added portraits
  common/game_rules/000_wc_game_rules.txt
  gfx/characters/shared/belf.dds
  gfx/characters/shared/dryads.dds
  gfx/characters/shared/humans.dds
  gfx/characters/shared/nelves.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_highelf.gfx
  interface/portraits/portraits_overlay.gfx
  localisation/00_wc_sad.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#718 Cipher Trade posts (Trade posts and building side) pull request n1
  artist_resources/mapitems/trade_arrow.xcf
  common/buildings/00_tradepost.txt
  common/buildings/01_tradepost.txt
  common/holding_types/wc_holdings.txt
  common/modifier_definitions/wc_trade_modifier_definitions.txt
  common/scripted_triggers/wc_trade_triggers.txt
  common/static_modifiers.txt
  common/trade_routes/00_wc_eastern_kingdoms_north.txt
  common/trade_routes/00_wc_eastern_kingdoms_south.txt
  common/trade_routes/00_wc_eastern_kingdoms_west_sea.txt
  common/trade_routes/00_wc_great_sea.txt
  common/trade_routes/00_wc_kalimdor.txt
  common/trade_routes/00_wc_kalimdor_east_sea.txt
  gfx/mapitems/trade_arrow.dds
  localisation/00_ciwc_united_localisation.csv
  localisation/00_wc_generics.csv
Labels: :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:, :star: new feature :new:

#814 2nd Patrons
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/provinces/3642 - Molten Cay.txt
  history/titles/b_amjawa_2.txt
  history/titles/c_arom.txt
  history/titles/c_dun_algaz.txt
  history/titles/c_hayward.txt
  history/titles/c_stillwhisper_pond.txt
  history/titles/c_underlight.txt
Labels: :grey_exclamation: priority low, :star: new feature :new:, :wrench: bug fix :hammer:

#763 Fix "Beyond the Dark Portal" Localization Issues
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#783 17th Bug Crusade
  common/cb_types/00_cb_types.txt
  common/cb_types/01_cb_types.txt
  common/cb_types/02_cb_types_shattered_world.txt
  common/cb_types/wc_cb_types.txt
  common/cultures/culture_goblin.txt
  common/dynasties/110000_satyr.txt
  common/dynasties/118000_qiraji.txt
  common/dynasties/47000_nerubian.txt
  common/dynasties/47000_spider.txt
  common/governments/nomadic_governments.txt
  common/governments/republic_governments.txt
  common/landed_titles/wc_republican_landed_titles.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/tributary_types/00_tributary_types.txt
  common/tributary_types/wc_tributary_types.txt
  decisions/wc_class_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_test_decisions.txt
  events/LT_wonder_flavor_events.txt
  events/wc_dark_cult_events.txt
  events/wc_loa_events.txt
  events/wc_plague_events.txt
  history/characters/150000_naga.txt
  history/characters/1_azerothian.txt
  history/characters/270000_tolvir.txt
  history/characters/310000_patron_characters.txt
  history/characters/410000_dryad.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_lordaeronian.txt
  history/titles/b_violet_hold.txt
  history/titles/c_dalaran.txt
  history/titles/c_dalarans_hills.txt
  history/titles/d_dalaran.txt
  history/titles/k_dalaran.txt
  map/positions.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#761 Draenor destruction event
  events/wc_beyond_dp.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#816 Rumours Events Adaptation
  events/rumours_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#818 Military Overhaul: the Magical Buff
  common/buildings/00_buildings.txt
  common/buildings/00_tribal.txt
  common/defines/troopvalues.lua
  common/retinue_subunits/00_retinue_subunits.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_unit_scripted_effects.txt
  common/special_troops/wc_special_troops.txt
  common/static_modifiers.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#815 Military Overhaul: the Technologies
  common/combat_tactics/00_combat_tactics.txt
  common/technology.txt
  localisation/000_wc_military_localization.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#821 Invasion Game Rules
  common/game_rules/000_wc_game_rules.txt
  common/scripted_effects/wc_scripted_effects.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority low, :star: new feature :new:

#829 Major bug fix №0
  common/trade_routes/00_wc_eastern_kingdoms_north.txt
  localisation/00_wc_sad.csv
Labels: :wrench: bug fix :hammer:

#705 Society Rework
  common/objectives/00_focuses.txt
  common/on_actions/00_on_actions.txt
  common/religions/druidism_group.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_society_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/HF_religious_decisions.txt
  decisions/dynasty_decisions.txt
  decisions/employment_decisions.txt
  decisions/mnm_monastic_order_decisions.txt
  decisions/mnm_society_decisions.txt
  decisions/wc_cc_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_sad_society.txt
  decisions/wc_sisterhood_decisions.txt
  decisions/wc_society_decisions.txt
  events/HF_religious_events.txt
  events/mnm_devil_worshipers_events.txt
  events/mnm_misc_events.txt
  events/mnm_monastic_orders_events.txt
  events/wc_cc_missions.txt
  events/wc_cenarion_circle_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  events/wc_emerald_dream_events.txt
  events/wc_quest_events.txt
  events/wc_sisterhood_events.txt
  events/wc_sisterhood_missions.txt
  events/wc_society_events.txt
  events/wc_startup_events.txt
  history/characters/340000_night_elf.txt
  history/characters/420000_ancients.txt
  interface/wc_decision_icons.gfx
  localisation/00_wc_job_titles.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :hammer: maintenance :wrench:, :star: new feature :new:

#834 Dynastic Names
  common/cultures/culture_gnoll.txt
  common/cultures/culture_tuskarr.txt
  common/landed_titles/01_landed_titles.txt
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#847 Gold sound
  sound/money_in.wav
  sound/money_out.wav
Labels: :grey_exclamation: priority low, :ice_cream: vanilla modification :icecream:

#851 German Fixes from Artifact Branch
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :page_facing_up: localization :pen:

#854 Military Overhaul: the Scaling
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/02_scripted_effects_alternate_start.txt
  events/on_action_events.txt
  events/rebel_events_the_old_gods.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#860 Teron Gorefiend DK second bookmark
  history/characters/10000_orc.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#861 Fix Highborne provinces history (on reload)
  history/titles/c_avalune.txt
  history/titles/c_dumont.txt
  history/titles/c_eldrethalas.txt
  history/titles/c_elunar.txt
  history/titles/c_estulan.txt
  history/titles/c_oneiros.txt
  history/titles/c_warpwood.txt
  history/titles/d_eldrethalas.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#855 Military Overhaul: the Terrain Combat Modifiers
  common/static_modifiers.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#866 1st Unused Localization
  coder_resources/_unused/localisation/not_used_strings.csv
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#830 Zuzu's Druid Form Nerf
  common/traits/druid_forms.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority low

#842 Take Vows - Endorsed Bloodlines Fix
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#843 Replace Holy Father with High Priest
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#841 Religion/Culture Change Issues
  common/objectives/00_zeus_childhood_focuses.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/conversion_decisions.txt
  decisions/mnm_secret_religious_societies_decisions.txt
  decisions/ze_decisions.txt
  events/guardian_events.txt
  events/rip_flavor_events.txt
  events/wc_race_events.txt
  events/ze_childhood_events.txt
  events/ze_lord_spiritual_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :wrench: bug fix :hammer:

#837 18th Bug Crusade
  common/bloodlines/wc_bloodlines.txt
  common/cb_types/00_cb_types.txt
  common/defines/00_dummy.lua
  common/government_flavor/00_government_flavor.txt
  common/religions/druidism_group.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/00_chinese_portrait_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  decisions/HF_coronation_decisions.txt
  decisions/LT_936_decisions.txt
  decisions/mnm_devil_worshipers_decisions.txt
  decisions/settlement_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_order_decisions.txt
  decisions/wc_realm_decisions.txt
  events/HFP_crusade_events.txt
  events/jd_china_succession_events.txt
  events/mnm_devil_worshipers_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  events/wc_quest_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/positions.txt
Labels: :exclamation: priority critical, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#891 LvLup sound effect
  common/scripted_effects/wc_class_scripted_effects.txt
  events/wc_class_events.txt
  interface/sound.sfx
  sound/warcraft_lvl_up.wav
Labels: :grey_exclamation: priority low, :star: new feature :new:
