Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-02, with the labels that each got.

#106 3rd Bug Crusade
  common/buildings/wc_hospital.txt
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/governments/theocracy_governments.txt
  common/minor_titles/00_minor_titles.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/objectives/00_focuses.txt
  common/on_actions/00_on_actions.txt
  common/religions/arakkoa_religion_group.txt
  common/religions/arcane_group.txt
  common/religions/dragon_religion_group.txt
  common/religions/druidism_group.txt
  common/religions/elemental_lords_group.txt
  common/religions/fel_group.txt
  common/religions/light_group.txt
  common/religions/loa_group.txt
  common/religions/necromancy_group.txt
  common/religions/nerubian_religion_group.txt
  common/religions/pandaren_religion_group.txt
  common/religions/primitive_group.txt
  common/religions/secular_group.txt
  common/religions/shamanism_group.txt
  common/religions/void_group.txt
  common/religions/vrykul_religion_group.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_test_decisions.txt
  events/mnm_misc_events.txt
  events/rip_flavor_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  events/wc_dragon_events.txt
  events/wc_government_events.txt
  events/wc_plague_events.txt
  events/wc_realm_events.txt
  events/wc_undead_events.txt
  events/wol_theology_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :wrench: bug fix :hammer:

#68 1th Performance Jihad
  common/cb_types/00_cb_types.txt
  common/cb_types/01_cb_types.txt
  common/cb_types/02_cb_types_shattered_world.txt
  common/game_rules/00_game_rules.txt
  common/minor_titles/00_minor_titles.txt
  common/objectives/00_ambitions.txt
  common/objectives/00_factions.txt
  common/objectives/00_plots.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/03_scripted_effects_sainthood.txt
  common/scripted_effects/04_scripted_effects_crusades.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_triggers/00_chinese_portrait_triggers.txt
  common/scripted_triggers/00_game_rules.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/03_crusades.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/HF_baptism_decisions.txt
  decisions/HF_coronation_decisions.txt
  decisions/conversion_decisions.txt
  decisions/minor_decisions.txt
  decisions/rip_various_decisions.txt
  decisions/settlement_decisions.txt
  decisions/wc_class_decisions.txt
  events/siege_events.txt
  events/soa_misc_religious_events.txt
  events/traits_effects_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_class_events.txt
  events/wc_startup_events.txt
  interface/portraits/portraits_dwarf.gfx
Labels: :hammer: maintenance :wrench:

#114 Small Improvements
  common/cb_types/wc_cb_types.txt
  common/game_rules/wc_game_rules.txt
  common/modifier_definitions/wc_class_modifier_definitions.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/objectives/00_focuses.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_being_traits.txt
  common/traits/wc_class_traits.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_special_traits.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_undead_decisions.txt
  decisions/wc_war_decisions.txt
  events/wc_first_war_events.txt
  events/wc_second_war_events.txt
  events/wc_void_events.txt
  gfx/interface/decision_icons/reborn_black_empire.dds
  gfx/interface/decision_icons/teach_yourself_paladin.dds
  interface/wc_decision_icons.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
  localisation/wc_religions.csv
  localisation/wc_sad.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :star: new feature :new:

#120 Adding Wowpedia links
  gfx/interface/charview_goto_wiki.dds
  localisation/WikipediaLinks.csv
Labels: :star: new feature :new:

#135 4th Bug Crusade
  common/cultures/culture_goblin.txt
  common/cultures/culture_undead.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/governments/feudal_governments.txt
  common/objectives/00_ambitions.txt
  common/on_actions/00_on_actions.txt
  common/religions/fel_group.txt
  common/religions/light_group.txt
  common/religions/loa_group.txt
  common/religions/nerubian_religion_group.txt
  common/religions/primitive_group.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/04_scripted_effects_crusades.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_substitute_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  decisions/HL_mercenary_decisions.txt
  decisions/dynasty_decisions.txt
  decisions/wc_realm_decisions.txt
  events/HFP_crusade_flavour.txt
  events/HF_alternate_start_events.txt
  events/HF_reconquista_events.txt
  events/cm_charlemagne_story_events.txt
  events/emperor_ticket_easter_eggs.txt
  events/evil_events.txt
  events/hl_silk_route_events.txt
  events/indian_holy_order_events.txt
  events/jd_raiding_china.txt
  events/religious_events.txt
  events/republic_trade_events.txt
  events/rip_flavor_events.txt
  events/rip_physician_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_dark_cult_events.txt
  events/wc_dragon_events.txt
  events/wc_fel_events.txt
  events/wc_frostwolf_events.txt
  events/wc_plague_events.txt
  events/wc_politfaction_events.txt
  events/wc_race_events.txt
  events/wc_third_war_events.txt
  events/wc_void_events.txt
  events/wol_seduction_events.txt
  interface/portraits/portraits_dryad.gfx
  interface/portraits/portraits_highborne.gfx
  interface/portraits/portraits_highelf_sprites.gfx
  interface/portraits/portraits_human.gfx
  interface/portraits/portraits_human_sprites.gfx
  interface/portraits/portraits_sethrak.gfx
  interface/portraits/portraits_vulpera.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :wrench: bug fix :hammer:

#136 2nd Small Improvements
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/on_actions/00_on_actions.txt
  common/religion_modifiers/wc_religion_modifiers.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/sad_scripted_triggers.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_class_traits.txt
  decisions/employment_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_war_decisions.txt
  events/various_notification_events.txt
  events/wc_class_events.txt
  events/wc_first_war_events.txt
  events/wc_second_war_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  gfx/interface/decision_icons/horde_invite_bloodthirsty_clans.dds
  gfx/interface/decision_icons/transformation_into_cthraxxi.dds
  history/titles/c_dark_portal.txt
  interface/wc_decision_icons.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :star: new feature :new:

#140 5th Bug Crusade
  common/buildings/wc_uniques.txt
  common/cb_types/wc_cb_types.txt
  common/defines/00_dummy.lua
  common/dynasties/16000_arathorian.txt
  common/minor_titles/00_minor_titles.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_effects/wcsp_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/mnm_society_decisions.txt
  decisions/way_of_life_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/ambition_events.txt
  events/mnm_devil_worshipers_events.txt
  events/wc_class_events.txt
  events/wc_fel_events.txt
  events/wc_politfaction_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :wrench: bug fix :hammer:

#138 Cenarion circle, sisterhood of elune, old gods
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/000_wc_artifacts.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/landed_titles/wc_titular_titles.txt
  common/on_actions/00_on_actions.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_sad_society.txt
  decisions/wc_sisterhood_decisions.txt
  events/wc_cenarion_circle_events.txt
  events/wc_class_events.txt
  events/wc_offmap_events.txt
  events/wc_sisterhood_events.txt
  gfx/interface/offmap_screen/china_status_placeholder.dds
  gfx/interface/societies/portrait_ring_sisterhood_of_elune.dds
  gfx/interface/societies/portrait_ring_small_sisterhood_of_elune.dds
  gfx/interface/societies/society_currency_sisterhood_of_elune.dds
  gfx/interface/societies/society_influence_sisterhood_of_elune.dds
  interface/portraits/portraits_undead_vrykul_sprites.gfx
  interface/wc_domestic_societies.gfx
  localisation/wc_offmap.csv
  localisation/wc_sad.csv
Labels: :page_facing_up: localization :pen:, :star: new feature :new:, :wrench: bug fix :hammer:

#126 New Flags
  gfx/flags/c_wyrmskull_coast.tga
  gfx/flags/d_brunnhildar.tga
  gfx/flags/d_cape_of_stranglethorn.tga
  gfx/flags/d_giants_run.tga
  gfx/flags/d_gjalerbron.tga
  gfx/flags/d_isle_of_giants.tga
  gfx/flags/d_mugamba.tga
  gfx/flags/d_nifflevar.tga
  gfx/flags/d_orsis.tga
  gfx/flags/d_quagmire.tga
  gfx/flags/d_razorfen.tga
  gfx/flags/d_stone_hill.tga
  gfx/flags/d_taurajo.tga
  gfx/flags/d_tel_abim.tga
  gfx/flags/d_utgarde.tga
  gfx/flags/d_valkyrion.tga
  gfx/flags/d_verdant_wilds.tga
  gfx/flags/d_waterspring.tga
  gfx/flags/e_uldum.tga
  gfx/flags/k_azshara.tga
  gfx/flags/k_barrens.tga
  gfx/flags/k_dragonblight.tga
  gfx/flags/k_gurubashi.tga
  gfx/flags/k_howling_fjord.tga
  gfx/flags/k_tel_abim.tga
  gfx/flags/k_uldum.tga
  gfx/flags/k_voldun.tga
  gfx/flags/k_wildhammer.tga
  gfx/flags/k_zandalar.tga
  gfx/flags/k_zulaman.tga
  gfx/flags/k_zulfarrak.tga
Labels: :art: graphics :paintbrush:

#141 Lore character portraits
  gfx/characters/shared/dryads.dds
  gfx/characters/shared/humans.dds
  gfx/characters/shared/nelves.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_demonform.gfx
  interface/portraits/portraits_dryad.gfx
  interface/portraits/portraits_human.gfx
  interface/portraits/portraits_nightelf.gfx
  interface/portraits/portraits_overlay.gfx
Labels: :art: graphics :paintbrush:

#159 Zuzu's Rebalance
  common/bloodlines/wc_bloodlines.txt
  common/buildings/wc_uniques.txt
  common/traits/wc_race_traits.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/16000_gnome.txt
  history/characters/180000_magnataur.txt
  history/characters/190000_taunka.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/210000_tauren.txt
  history/characters/220000_dark_troll.txt
  history/characters/22000_wildhammer.txt
  history/characters/270000_tolvir.txt
  history/characters/290000_frozen_giant.txt
  history/characters/29000_gnoll.txt
  history/characters/330000_highborne.txt
  history/characters/340000_night_elf.txt
  history/characters/380000_frostnymph.txt
  history/characters/390000_sethrak.txt
  history/characters/410000_dryad.txt
  history/characters/42000_high_elf.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/57000_amani.txt
  history/characters/60000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/66000_zandalari.txt
  history/characters/75000_old_dwarven.txt
  history/characters/80000_drakkari.txt
Labels: :balance_scale: balance :balance_scale:
