Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-08, with the labels that each got.

#575 I am Speed: The Branch
  common/defines/00_dummy.lua
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :star: new feature :new:

#562 Bug Crusade - 13th Chapter
  common/cb_types/wc_cb_types.txt
  common/landed_titles/wc_titular_titles.txt
  common/laws/ze_demesne_laws.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/settlement_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_test_decisions.txt
  decisions/wc_war_decisions.txt
  dlc_metadata/dlc_characters/00_dlc_characters.txt
  dlc_metadata/dlc_recommendations/00_dlc_recommendations.txt
  events/HF_religious_events.txt
  events/on_action_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  events/wc_plague_events.txt
  events/wc_race_events.txt
  events/wc_troll_events.txt
  events/wc_war_events.txt
  history/characters/10000_orc.txt
  history/characters/1_azerothian.txt
  history/characters/42000_high_elf.txt
  history/characters/59000_dalaranian.txt
  history/characters/62000_dragon.txt
  history/titles/c_menethil_harbor.txt
  history/titles/c_south_delta.txt
  history/titles/d_burning_blade.txt
  history/titles/d_laughing_skull.txt
  history/titles/d_shattered_hand.txt
  history/titles/e_pantheon.txt
  history/titles/k_dun_niffelem.txt
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/positions.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#609 Issue #579
  common/dynasties/119000_harpy.txt
Labels: :wrench: bug fix :hammer:

#610 Small improvements afk
  decisions/wc_dark_cult_decisions.txt
  events/wc_dark_cult_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :star: new feature :new:

#638 Decision icons-01
  artist_resources/icons/loot__decision.png
  artist_resources/icons/reforge_decision.png
  artist_resources/icons/sell_decision.png
  artist_resources/icons/trainer_decision.png
  artist_resources/icons/trainer_decision.xcf
  decisions/wc_class_decisions.txt
  gfx/interface/special_decision_icons/loot_decision.dds
  gfx/interface/special_decision_icons/reforge_decision.dds
  gfx/interface/special_decision_icons/sell_decision.dds
  gfx/interface/special_decision_icons/trainer_decision.dds
  interface/wc_domestic_diplomacy.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#559 Cenarion Circle - Fixes and Standardization
  common/event_modifiers/wc_cooldown_modifiers.txt
  decisions/mnm_society_decisions.txt
  decisions/wc_cc_decisions.txt
  decisions/wc_sisterhood_decisions.txt
  decisions/wc_society_decisions.txt
  events/wc_cenarion_circle_events.txt
  events/wc_society_events.txt
  gfx/interface/decision_icons/invite_student_society.dds
  gfx/interface/decision_icons/train_class_society.dds
  interface/wc_decision_icons.gfx
  localisation/00_wc_sad.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:, :star: new feature :new:

#645 Added Wowpedia links for Tiffin Wrynn and Vandellor
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#646 Offmap fixes and refactoring
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  decisions/wc_offmap_decisions.txt
  events/wc_offmap_events.txt
  localisation/00_wc_offmap.csv
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#661 Issue #655
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/z_landed_titles_kalimdor.txt
  gfx/flags/c_neferset.tga
  gfx/flags/c_orsis.tga
  gfx/flags/k_neferset.tga
  gfx/flags/k_ramkahen.tga
  gfx/flags/k_uldum.tga
  history/provinces/2924 - Neferset.txt
  history/provinces/2952 - Uldum.txt
  history/titles/_unused/c_virdam.txt
  history/titles/c_aamsk.txt
  history/titles/c_akhenet.txt
  history/titles/c_ammon.txt
  history/titles/c_anbarhan.txt
  history/titles/c_asova.txt
  history/titles/c_dulized.txt
  history/titles/c_hamatep.txt
  history/titles/c_helhuvip.txt
  history/titles/c_khartut.txt
  history/titles/c_khintaset.txt
  history/titles/c_kubitis.txt
  history/titles/c_marat.txt
  history/titles/c_moonsuph.txt
  history/titles/c_nahom.txt
  history/titles/c_neferset.txt
  history/titles/c_oorf.txt
  history/titles/c_orsis.txt
  history/titles/c_phedathi.txt
  history/titles/c_ramkahen.txt
  history/titles/c_sahket.txt
  history/titles/c_south_wind.txt
  history/titles/c_sunstone.txt
  history/titles/c_sunsuph.txt
  history/titles/c_sunwatcher.txt
  history/titles/c_ta_kemet.txt
  history/titles/c_tahret.txt
  history/titles/c_tammano.txt
  history/titles/c_tolnariv.txt
  history/titles/c_virsar.txt
  history/titles/d_khartut.txt
  history/titles/d_neferset.txt
  history/titles/d_orsis.txt
  history/titles/d_ramkahen.txt
  history/titles/d_uldum.txt
  history/titles/k_ramkahen.txt
  history/titles/k_uldum.txt
  localisation/000_Other_title_names.csv
  localisation/00_Barony_names.csv
  localisation/00_Kingdom_names.csv
  localisation/wc_religions.csv
  map/climate.txt
  map/provinceDef.xls
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:

#679 1st Religion Icons
  gfx/interface/religion_icon_strip.dds
  gfx/interface/religion_icon_strip_big.dds
  gfx/interface/religion_icon_strip_small.dds
Labels: :art: graphics :paintbrush:

#680 Artifacts: the New Home
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :hammer: maintenance :wrench:
