Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-05, with the labels that each got.

#269 Draenei and Cultural Melting Pots, additional flavor events/decisions
  common/cultures/culture_human.txt
  common/cultures/culture_orc.txt
  common/job_actions/wc_job_actions.txt
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/nicknames/wc_nicknames.txt
  common/on_actions/00_on_actions.txt
  common/religions/light_group.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_troll_decisions.txt
  events/wc_culture_conversion_events.txt
  events/wc_draenei_events.txt
  events/wc_first_war_events.txt
  events/wc_troll_events.txt
  events/wc_war_events.txt
  gfx/event_pictures/exodar.tga
  gfx/event_pictures/zuldazar.tga
  gfx/flags/d_hand_of_argus.tga
  gfx/flags/d_lightbound.tga
  gfx/flags/d_naaru.tga
  gfx/flags/e_empire_of_zul.tga
  gfx/flags/e_zulfarrak.tga
  gfx/flags/k_exodar.tga
  gfx/interface/decision_icons/form_the_empire_of_zul.dds
  gfx/interface/religion_icon_strip.dds
  gfx/interface/religion_icon_strip_big.dds
  gfx/interface/religion_icon_strip_small.dds
  history/technology/k_azuremyst.txt
  history/titles/d_lightbound.txt
  history/titles/d_naaru.txt
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_wc_title_key.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_cultures.csv
  localisation/wc_religions.csv
  localisation/wc_traits.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/climate.txt
  map/geographical_region.txt
  map/provinceDef.xls
Labels: :art: graphics :paintbrush:, :page_facing_up: localization :pen:, :star: new feature :new:

#296 1st Wonders
  common/artifacts/000_wc_artifacts.txt
  common/buildings/wc_uniques.txt
  common/game_rules/00_game_rules.txt
  common/modifier_definitions/wc_class_modifier_definitions.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/objectives/00_LT_ambitions.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/wonder_upgrades/wc_wonder_upgrades.txt
  common/wonders/wc_wonders.txt
  decisions/wc_class_decisions.txt
  decisions/wc_realm_decisions.txt
  events/LT_wonder_flavor_event_2.txt
  events/wc_class_events.txt
  events/wc_fel_events.txt
  events/wc_first_war_events.txt
  events/wc_third_war_events.txt
  events/wc_void_events.txt
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_karazhan_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_karazhan_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_karazhan_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_necropolis_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_necropolis_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_necropolis_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_soul_engine_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_soul_engine_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_soul_engine_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_sunwell_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_sunwell_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_sunwell_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_twilight_citadel_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_twilight_citadel_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_twilight_citadel_small.dds
  history/provinces/2956 - Ahnqiraj.txt
  history/provinces/3576 - Dazaralor.txt
  history/provinces/394 - Sunwell Plateau.txt
  history/provinces/46 - Karazhan.txt
  history/provinces/799 - Carrion.txt
  history/titles/c_karazhan.txt
  interface/wc_wonder.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/08_custom_loc_wonder_setup.txt
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :star: new feature :new:

#352 9th Bug Crusade
  common/council_positions/00_loyalist.txt
  common/council_positions/01_pragmatist.txt
  common/council_positions/02_glory_hound.txt
  common/council_positions/03_zealot.txt
  common/council_positions/04_malcontent.txt
  common/cultures/culture_murloc.txt
  common/governments/feudal_governments.txt
  common/governments/nomadic_governments.txt
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/z_landed_titles_noise.txt
  common/minor_titles/00_minor_titles.txt
  common/minor_titles/wc_minor_titles.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_special_traits.txt
  decisions/employment_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/HFP_pregnancy_events.txt
  events/HFP_random_flavor_events.txt
  events/ambition_events.txt
  events/birth_events.txt
  events/hl_raiding_adventurers_events.txt
  events/wc_dark_cult_events.txt
  events/wc_fel_events.txt
  events/wc_first_war_events.txt
  events/wc_order_events.txt
  events/wc_race_events.txt
  events/wc_void_events.txt
  history/characters/140000_satyr.txt
  history/characters/60000_lordaeronian.txt
  history/provinces/2956 - Ahnqiraj.txt
  history/provinces/3167 - Fire Scar.txt
  history/provinces/3168 - Aessina.txt
  history/provinces/3179 - Shady Nook.txt
  history/provinces/3181 - Night Run.txt
  history/provinces/3201 - Xonulzis.txt
  history/provinces/3217 - Sable Ridge.txt
  history/provinces/3221 - Ravencrest.txt
  history/provinces/3223 - Xemrir.txt
  history/provinces/3330 - Bladewood.txt
  history/provinces/394 - Sunwell Plateau.txt
  history/titles/c_lights_hope.txt
  history/titles/c_stonard.txt
  history/titles/c_tyrs_hand.txt
  localisation/000_Other_title_names.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
  localisation/wc_traits.csv
  localisation_rus/000_ru_wc_traits.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/geographical_region.txt
  map/island_region.txt
  map/provinceDef.xls
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#335 Necromancy: Shadowlanders
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/000_wc_artifacts.txt
  common/dynasties/1_azerothian.txt
  common/dynasties/36000_dalaranian.txt
  common/governments/theocracy_governments.txt
  common/landed_titles/z_holy_sites.txt
  common/objectives/00_focuses.txt
  common/religions/necromancy_group.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/HF_baptism_decisions.txt
  decisions/employment_decisions.txt
  events/HF_baptism_events.txt
  events/traits_effects_events.txt
  events/wc_undead_events.txt
  events/wol_scholarship_events.txt
  events/ze_lord_spiritual_events.txt
  history/characters/1_azerothian.txt
  history/characters/59000_dalaranian.txt
  history/provinces/44 - Raven Hill.txt
  history/provinces/46 - Karazhan.txt
  history/provinces/47 - Deadmans Pass.txt
  history/provinces/49 - Vice.txt
  history/titles/c_deadmans_pass.txt
  history/titles/c_karazhan.txt
  history/titles/c_raven_hill.txt
  history/titles/c_vice.txt
  history/titles/d_deadwind_pass.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religions.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :star: new feature :new:

#369 9.1th Bug Сrusade
  common/landed_titles/wc_religious_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_troll_decisions.txt
  events/job_offmap.txt
  events/wc_class_events.txt
  events/wc_court_events.txt
  events/wc_offmap_events.txt
  events/wc_startup_events.txt
  events/wc_void_events.txt
  history/titles/b_silver_bastion.txt
  history/titles/e_empire_of_zul.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#387 German Localization
  localisation/000_Other_title_names.csv
  localisation/00_Barony_names.csv
  localisation/00_wc_government.csv
  localisation/00_wc_special_units.csv
  localisation/00_wc_title_key.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_wc_buildings.csv
  localisation/mercaneries_holyorders.csv
  localisation/tyr_wc_loa.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_generics.csv
  localisation/wc_uniques.csv
Labels: :page_facing_up: localization :pen:
