Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-11, with the labels that each got.

#871 New flagsiews
  gfx/flags/c_ravenholdt.tga
  gfx/flags/d_bloodsail_pirates.tga
  gfx/flags/d_dogs_of_war.tga
  gfx/flags/d_giants_run.tga
  gfx/flags/d_hemets_hunters.tga
  gfx/flags/d_isle_of_giants.tga
  gfx/flags/d_korkron.tga
  gfx/flags/d_ravenholdt.tga
  gfx/flags/d_roughnecks.tga
  gfx/flags/d_stormriggers.tga
  gfx/flags/d_verdant_wilds.tga
  gfx/flags/d_wardens.tga
  gfx/flags/d_waterspring.tga
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#884 Tel'Abim Bananas
  common/buildings/wc_tradepost.txt
  common/scripted_triggers/wc_trade_triggers.txt
  localisation/00_wc_generics.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#903 German Religions
  localisation/wc_religions.csv
Labels: :exclamation: priority high, :page_facing_up: localization :pen:

#890 Disallow Religion Head to adopt secret religion
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/mnm_secret_religious_societies_decisions.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#892 19th Bug Сrusade
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_substitute_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_test_decisions.txt
  events/hl_raiding_adventurers_events.txt
  events/on_action_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_beyond_dp.txt
  events/wc_second_war_events.txt
  events/wc_war_events.txt
  history/characters/210000_tauren.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#885 Fix some army positions (mostly when moving)
  map/positions.txt
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#905 20th Bug Crusade
  common/laws/succession_laws.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  events/wc_class_events.txt
  events/wc_undead_events.txt
  localisation/00_wc_generics.csv
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#911 Meme fixes
  common/on_actions/00_on_actions.txt
  decisions/wc_class_decisions.txt
  events/wc_order_events.txt
  history/characters/46000_gilnean.txt
  history/titles/c_alther.txt
  history/titles/c_blackrock_pass.txt
  history/titles/c_blackwood_2.txt
  history/titles/c_huthenra.txt
  history/titles/c_jinthakalar.txt
  history/titles/c_lakeshire.txt
  history/titles/c_long_wash.txt
  history/titles/c_naedanar.txt
  history/titles/c_purgation_isle.txt
  history/titles/c_snowfang.txt
  history/titles/c_tahret.txt
  history/titles/c_winterfall.txt
  history/titles/d_burning_steppes.txt
  history/titles/d_searing_gorge.txt
  history/titles/d_starfall.txt
  localisation/00_wc_sad.csv
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#893 Evil Laws Issues
  common/governments/feudal_governments.txt
  common/laws/succession_laws.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_dark_cult_decisions.txt
  events/HF_religious_events.txt
  events/on_action_events.txt
  events/wc_government_events.txt
  events/wc_race_events.txt
  events/wc_startup_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#894 Adventure Rebalance
  common/on_actions/00_on_actions.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/hl_raiding_adventurers_events.txt
  events/wc_druidic_events.txt
  events/wc_fel_events.txt
  events/wc_war_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#780 Military Overhaul: the Cultural Buildings
  coder_resources/_unused/localisation/wc_culture_buildings.csv
  common/buildings/wc_castle_culture.txt
  localisation/wc_culture_buildings.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#844 13th Small Improvements
  common/cb_types/wc_cb_types.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/game_rules/00_game_rules.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/game_rule_events.txt
  events/wc_class_events.txt
  events/wc_fel_events.txt
  events/wc_first_war_events.txt
  events/wc_void_events.txt
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
  history/titles/c_cifonill.txt
  history/titles/c_ealnow.txt
  history/titles/c_falfarren.txt
  history/titles/c_green_hill.txt
  history/titles/c_haasra.txt
  history/titles/c_murcevin.txt
  history/titles/c_night_canyon.txt
  history/titles/c_nightsong.txt
  history/titles/c_shady_nook.txt
  history/titles/c_silverwing.txt
  history/titles/c_southwind.txt
  history/titles/c_splintertree.txt
  history/titles/c_staghelm.txt
  history/titles/c_valor.txt
  history/titles/d_cenarion_hold.txt
  history/titles/d_murcevin.txt
  history/titles/d_silverwing_sentinels.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_cultures.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#916 Localisation crusade 6
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#912 Night Elf Holding Icons
  artist_resources/holdings/nightelfgfx/arts/empty_forest.png
  common/cultures/culture_ancient.txt
  common/cultures/culture_dryad.txt
  common/cultures/culture_night_elf.txt
  common/religions/druidism_group.txt
  gfx/interface/holdings/frostnymphgfx/province_capital_settlement_frame_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/province_settlement_frame_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_building_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_castle_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_castle_frostnymphgfx_looted.tga
  gfx/interface/holdings/frostnymphgfx/settlement_city_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_city_frostnymphgfx_looted.tga
  gfx/interface/holdings/frostnymphgfx/settlement_new_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_nomad_empty_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_nomad_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_nomad_frostnymphgfx_looted.tga
  gfx/interface/holdings/frostnymphgfx/settlement_temple_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_temple_frostnymphgfx_looted.tga
  gfx/interface/holdings/frostnymphgfx/settlement_tribal_empty_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_tribal_frostnymphgfx.tga
  gfx/interface/holdings/frostnymphgfx/settlement_tribal_frostnymphgfx_looted.tga
  gfx/interface/holdings/nightelf/castle.dds
  gfx/interface/holdings/nightelf/castle_looted.dds
  gfx/interface/holdings/nightelf/city.dds
  gfx/interface/holdings/nightelf/city_looted.dds
  gfx/interface/holdings/nightelf/settlement_temple_nightelf.dds
  gfx/interface/holdings/nightelf/settlement_temple_nightelf_looted.dds
  gfx/interface/holdings/nightelf/tribe.dds
  gfx/interface/holdings/nightelf/tribe_looted.dds
  gfx/interface/holdings/nightelfgfx/province_capital_settlement_frame_nightelfgfx.dds
  gfx/interface/holdings/nightelfgfx/province_settlement_frame_nightelfgfx.dds
  gfx/interface/holdings/nightelfgfx/settlement_building_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_castle_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_castle_nightelfgfx_looted.tga
  gfx/interface/holdings/nightelfgfx/settlement_city_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_city_nightelfgfx_looted.tga
  gfx/interface/holdings/nightelfgfx/settlement_new_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_temple_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_temple_nightelfgfx_looted.tga
  gfx/interface/holdings/nightelfgfx/settlement_tribal_empty_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_tribal_nightelfgfx.tga
  gfx/interface/holdings/nightelfgfx/settlement_tribal_nightelfgfx_looted.tga
  interface/wc_holdings.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#919 3rd Patron Batch
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/titles/c_brightdale.txt
  history/titles/c_three_corners.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#923 wc_cultures.csv Columns
  localisation/wc_cultures.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#914 Resaved Portrait Backgrounds
  gfx/characters/shared/backgrounds.dds
  gfx/characters/shared/darkiron_background.dds
  gfx/characters/titanwatcher_male/backgrounds/pantheon_background.dds
  gfx/characters/titanwatcher_male/backgrounds/valarjar_background.dds
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :wrench: bug fix :hammer:

#915 No Vanilla Music
  music/caliph_music_pack.txt
  music/english_music_pack.txt
  music/faith_music_pack.txt
  music/fullplatemetal.txt
  music/holy_fury.txt
  music/holy_land_music_pack.txt
  music/hymns_of_abraham.txt
  music/hymns_to_the_old_gods.txt
  music/hymnsofrevelation.txt
  music/jade_dragon.txt
  music/orchestralhouselords.txt
  music/paganfury.txt
  music/paganfury2.txt
  music/republic_music_pack.txt
  music/rus_music_pack.txt
  music/songs.txt
  music/songs_of_byzantium.txt
  music/songsofindia.txt
  music/songsofthesteppes.txt
  music/vikingmetalmusic.txt
Labels: :exclamation: priority high, :star: new feature :new:

#925 Mind Control and Turn Undead Blocks
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_undead_decisions.txt
  events/wc_class_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :hammer: maintenance :wrench:

#949 Artifact Indentation
  common/artifact_spawns/wc_artifact_spawns.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#941 Reworked AI Status of Magic Logic
  common/laws/wc_misc_laws.txt
  common/scripted_triggers/wc_scripted_triggers.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium

#922 21st Bug Crusade 🐞⚔
  common/buildings/00_hospital.txt
  common/governments/feudal_governments.txt
  common/holding_types/00_holding_types.txt
  common/landed_titles/z_landed_titles_eastern_kingdoms.txt
  common/retinue_subunits/00_retinue_subunits.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#870 Targeted Quests Rework
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_society_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  events/mnm_misc_events.txt
  events/wc_class_events.txt
  events/wc_quest_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :wrench: bug fix :hammer:

#960 Scourge Holding Icons
  artist_resources/holdings/lichgfx/arts/Dragonblight3(1x1).jpg
  common/religions/necromancy_group.txt
  gfx/interface/holdings/lichgfx/province_capital_settlement_frame_lichgfx.dds
  gfx/interface/holdings/lichgfx/province_settlement_frame_lichgfx.dds
  gfx/interface/holdings/lichgfx/settlement_building_lichgfx.tga
  gfx/interface/holdings/lichgfx/settlement_new_lichgfx.tga
  gfx/interface/holdings/lichgfx/settlement_tribal_empty_lichgfx.tga
  interface/wc_holdings.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#864 Artifact Balancing
  common/artifacts/000_wc_artifacts.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#917 Racial Stereotypes Game Rule
  common/game_rules/000_wc_game_rules.txt
  common/scripted_effects/wc_scripted_effects.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#910 Game Rule for Adoption Event
  artist_resources/other_traits/adopted.xcf
  common/game_rules/000_wc_game_rules.txt
  common/traits/wc_special_traits.txt
  events/wc_court_events.txt
  gfx/traits/adopted.dds
  history/characters/42000_high_elf.txt
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:, :wrench: bug fix :hammer:
