Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-07, with the labels that each got.

#404 Election Rework
  common/laws/succession_laws.txt
  common/religions/loa_group.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_score_values/wc_voting_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/succession_voting/00_succession_voting.txt
  common/succession_voting/01_succession_voting_specials.txt
  common/succession_voting/wc_succession_voting.txt
  events/job_lord_spiritual.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :star: new feature :new:

#439 Tactic Rework for MO
  common/combat_tactics/00_combat_tactics.txt
  common/combat_tactics/wc_combat_tactics.txt
  common/scripted_triggers/wc_leadership_triggers.txt
  localisation/000_wc_military_localization.csv
  localisation/00_zuwc_united_localisation.csv
  music/songs.txt
Labels: :balance_scale: balance :balance_scale:, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:, :star: new feature :new:

#486 Wonders File Organization (GDC)
  common/wonder_upgrades/wc_wonders_buildable_upgrades.txt
  common/wonder_upgrades/wc_wonders_historical_upgrades.txt
  common/wonders/wc_wonders_buildable.txt
  common/wonders/wc_wonders_historical.txt
  common/wonders/wonders.info
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_wonders.csv
  localisation/wc_wonders_upgrades.csv
Labels: :book: documentation :books:, :hammer: maintenance :wrench:

#487 Issue #485
  history/provinces/134 - Golbolar.txt
  history/provinces/230 - Vankeiki.txt
  history/provinces/254 - Peleahjin.txt
  history/provinces/257 - Queldanil.txt
  history/provinces/258 - Shadraalor.txt
  history/provinces/260 - Jinthaalor.txt
  history/provinces/265 - Lower Jinthaalor.txt
  history/provinces/2919 - Anbarhan.txt
  history/provinces/2960 - Hiveashi.txt
  history/provinces/2963 - Hivezora.txt
  history/provinces/2968 - Hiveregal.txt
  history/provinces/2990 - Eldratir.txt
  history/provinces/3022 - Jambarrak.txt
  history/provinces/3185 - Dordanil.txt
  history/provinces/3193 - Ordilaran.txt
  history/provinces/3202 - Atelanor.txt
  history/provinces/3229 - Bashalaran.txt
  history/provinces/3237 - Ametharan.txt
  history/provinces/3243 - Morlosaran.txt
  history/provinces/3246 - Emeraran.txt
  history/provinces/3293 - Keltheril.txt
  history/provinces/3294 - Snowdaril.txt
  history/provinces/3296 - Naedanar.txt
  history/provinces/3310 - Bwonalor.txt
  history/provinces/3311 - Shadradar.txt
  history/provinces/355 - Quellithien.txt
  history/provinces/3568 - Jinkalak.txt
  history/provinces/3623 - Ominous Island.txt
  history/provinces/365 - Torwatha.txt
  history/provinces/367 - Zebwatha.txt
  history/provinces/53 - Zulmarash.txt
  history/provinces/60 - Zulmamwe.txt
  history/provinces/61 - Zulkunda.txt
  history/provinces/692 - Zulmashar.txt
  history/provinces/731 - Drakzin.txt
  history/provinces/732 - Zebhalak.txt
  history/provinces/755 - Zolheb.txt
  history/provinces/756 - Dubrajin.txt
  history/provinces/757 - Zolmaz.txt
  history/provinces/760 - Drakmabwa.txt
  history/provinces/761 - Zimrhuk.txt
  history/provinces/764 - Zimtorga.txt
  history/provinces/765 - Hebdrakkar.txt
  history/provinces/770 - Chagajin.txt
  history/provinces/771 - Draksotra.txt
  history/provinces/772 - Zimabwa.txt
  history/provinces/774 - Hebvalok.txt
  history/provinces/946 - Battokalor.txt
  localisation/00_Barony_names.csv
  localisation/00_County_names.csv
  localisation/00_Province_names.csv
  map/definition.csv
  map/provinceDef.xls
Labels: :wrench: bug fix :hammer:

#492 Localisation Crusade - 3rd Chapter
  localisation/00_DEwc_united_localisation.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_government.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_city.csv
  localisation/00_wc_ruler_titles_magocracy.csv
  localisation/00_wc_ruler_titles_nomadic.csv
  localisation/00_wc_ruler_titles_technocracy.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_ruler_titles_vice_royalty.csv
  localisation/00_wc_special_units.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/mercaneries_holyorders.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_fel.csv
  localisation/wc_loa_event.csv
  localisation/wc_offmap.csv
  localisation/wc_religions.csv
  localisation/wc_sad.csv
  localisation/wc_scourge.csv
  localisation/wc_traits.csv
  localisation/wc_uniques.csv
Labels: :page_facing_up: localization :pen:

#483 12th Bug Crusade
  common/cb_types/wc_cb_types.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/mercenaries/00_mercenaries.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/HL_mercenary_decisions.txt
  decisions/HL_title_decisions.txt
  decisions/jd_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_order_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_undead_decisions.txt
  events/hl_raiding_adventurers_events.txt
  events/wc_beyond_dp.txt
  events/wc_class_events.txt
  events/wc_light_events.txt
  events/wc_order_events.txt
  events/wc_plague_events.txt
  events/wc_politfaction_events.txt
  events/wc_race_events.txt
  events/wc_realm_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_war_events.txt
  gfx/characters/dryad_child/dryad_female.dds
  gfx/characters/dryad_child/dryad_male.dds
  gfx/characters/dryad_child/frost_dryad_female.dds
  gfx/characters/dryad_child/frost_dryad_male.dds
  history/characters/22000_wildhammer.txt
  history/titles/c_dark_portal.txt
  history/titles/d_bonetrail.txt
  history/titles/d_nordrassil.txt
  history/titles/d_sildinas.txt
  history/titles/d_sytror.txt
  history/titles/k_hyjal.txt
  interface/portraits/portraits_dryad_sprites.gfx
  interface/portraits/portraits_frostnymph_sprites.gfx
  interface/portraits/portraits_highborne_sprites.gfx
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#255 Cenarion circle and druids
  common/artifacts/000_wc_artifacts.txt
  common/cb_types/00_cb_types.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/objectives/00_focuses.txt
  common/objectives/wc_ambitions.txt
  common/offmap_powers/wc_offmap_yogg_saron.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/sad_scripted_effects.txt
  common/scripted_score_values/wc_scripted_class_values.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/societies/wc_societies.txt
  common/traits/druid_forms.txt
  common/tributary_types/00_tributary_types.txt
  decisions/jd_decisions.txt
  decisions/wc_cc_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_ogre_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_sad_society.txt
  decisions/wc_sisterhood_decisions.txt
  events/wc_cc_missions.txt
  events/wc_cenarion_circle_events.txt
  events/wc_class_events.txt
  events/wc_emerald_dream_events.txt
  events/wc_offmap_events.txt
  events/wc_ogre_events.txt
  events/wc_race_events.txt
  events/wc_sad.txt
  events/wc_society_government_events.txt
  gfx/event_pictures/malorne.tga
  gfx/interface/decision_icons/become_ogre_mage.dds
  gfx/interface/decision_icons/study_at_temple.dds
  gfx/interface/decision_icons/train_disciple.dds
  gfx/interface/decision_icons/vows_of_purity.dds
  gfx/interface/societies/rank_icons_five.dds
  gfx/interface/societies/rank_icons_five_highlight.dds
  gfx/interface/societies/rank_icons_five_locked.dds
  gfx/interface/society_quest/mission_bg_circle.dds
  gfx/interface/society_quest/mission_bg_sisterhood.dds
  history/titles/k_cenarion_circle.txt
  history/titles/k_cenarion_circle_fake.txt
  history/titles/k_hyjal.txt
  interface/portrait_properties/00_portrait_properties.txt
  interface/wc_decision_icons.gfx
  interface/wc_domestic_societies.gfx
  localisation/00_wc_offmap.csv
  localisation/wc_sad.csv
Labels: :exclamation: priority critical, :star: new feature :new:, :wrench: bug fix :hammer:

#525 1st Patron Characters
  common/dynasties/125000_patron_dynasties.txt
  common/landed_titles/01_landed_titles.txt
  history/characters/310000_patron_characters.txt
  history/provinces/246 - Strahnbrad.txt
  history/titles/b_gallows.txt
  history/titles/c_duskwither_ravine.txt
  history/titles/c_northighlands.txt
  history/titles/c_stonecairn.txt
  localisation/00_Barony_names.csv
  map/provinceDef.xls
Labels: :star: new feature :new:

#523 12.5th Bug Crusade
  common/artifacts/02_artifacts_wonders.txt
  common/cb_types/wc_cb_types.txt
  common/governments/feudal_governments.txt
  common/governments/tribal_governments.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_war_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  events/wc_order_events.txt
  events/wc_politfaction_events.txt
  localisation/00_wc_government.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_sad.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#521 1st Game Rules
  common/game_rules/000_wc_game_rules.txt
  common/on_actions/00_on_actions.txt
  decisions/wc_dark_cult_decisions.txt
  events/wc_beyond_dp.txt
  events/wc_draenei_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  history/characters/10000_orc.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#529 Artifacts slot vanillisation
  common/artifacts/000_wc_artifacts.txt
  common/artifacts/000_wc_generic_artifacts_hats.txt
  common/artifacts/00_artifacts.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#532 4th Flags
  gfx/flags/d_aerie_peak.tga
  gfx/flags/d_cifonill.tga
  gfx/flags/d_dazaralor.tga
  gfx/flags/d_drognur.tga
  gfx/flags/d_eastvale.tga
  gfx/flags/d_loch_modan.tga
  gfx/flags/d_nazwatha.tga
  gfx/flags/d_nightsong.tga
  gfx/flags/d_nittawosew.tga
  gfx/flags/d_oomsk.tga
  gfx/flags/d_redhelm.tga
  gfx/flags/d_searing_gorge.tga
  gfx/flags/d_sentinel_hill.tga
  gfx/flags/d_silverwind.tga
  gfx/flags/d_skypeak.tga
  gfx/flags/d_stonewatch.tga
  gfx/flags/d_thorvald.tga
  gfx/flags/d_undermine.tga
  gfx/flags/d_wahkan.tga
  gfx/flags/d_zebahari.tga
  gfx/flags/e_storm_peaks.tga
  gfx/flags/e_trade_coalition.tga
  gfx/flags/k_grizzly_hills.tga
  gfx/flags/k_hinterlands.tga
  gfx/flags/k_kezan.tga
  gfx/flags/k_mulgore.tga
  gfx/flags/k_storm_peaks.tga
  gfx/flags/k_tanaris.tga
Labels: :art: graphics :paintbrush:

#493 Localisation Crusade - 4th Chapter
  localisation/000_Other_title_names.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_Duchy_names.csv
  localisation/00_Empire_names.csv
  localisation/00_Kingdom_names.csv
  localisation/00_Province_names.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_government.csv
  localisation/00_wc_job_titles.csv
  localisation/00_wc_offmap.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_city.csv
  localisation/00_wc_ruler_titles_magocracy.csv
  localisation/00_wc_ruler_titles_nomadic.csv
  localisation/00_wc_ruler_titles_technocracy.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_ruler_titles_vice_royalty.csv
  localisation/00_wc_special_units.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/mercaneries_holyorders.csv
  localisation/tyr_wc_loa.csv
  localisation/wc_combat.csv
  localisation/wc_cultures.csv
  localisation/wc_oldgods.csv
  localisation/wc_religions.csv
  localisation/wc_sad.csv
  localisation/wc_scourge.csv
  localisation/wc_traits.csv
  localisation/wc_uniques.csv
  localisation/wc_wonders.csv
  localisation/wc_wonders_upgrades.csv
Labels: :page_facing_up: localization :pen:

#556 Steam Page Enhancement
  artist_resources/page_design/logos/goa_subreddit_button.pdn
  artist_resources/page_design/logos/goa_subreddit_button.png
  artist_resources/page_design/steam.txt
Labels: :book: documentation :books:
