Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-06, with the labels that each got.

#400 Nraqi portrait fixes
  gfx/characters/nraqi_male/nraqi_male_eyes_1.dds
Labels: :wrench: bug fix :hammer:

#391 German Localization
  localisation/000_Other_title_names.csv
  localisation/00_Barony_names.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_government.csv
  localisation/00_wc_special_units.csv
  localisation/00_wc_title_key.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_wc_buildings.csv
  localisation/mercaneries_holyorders.csv
  localisation/tyr_wc_loa.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
  localisation/wc_loa_event.csv
  localisation/wc_offmap.csv
  localisation/wc_oldgods.csv
  localisation/wc_religion_buildings.csv
  localisation/wc_religions.csv
  localisation/wc_scourge.csv
  localisation/wc_traits.csv
  localisation/wc_uniques.csv
Labels: :page_facing_up: localization :pen:

#396 3.2.0 Adaptation
  common/bloodlines/00_bloodlines.txt
  common/buildings/00_CastleCulture.txt
  common/buildings/00_tribalCulture.txt
  common/cb_types/00_cb_types.txt
  common/cultures/00_cultures.txt
  common/event_modifiers/01_event_modifiers_LT.txt
  common/game_rules/00_game_rules.txt
  common/minor_titles/00_minor_titles.txt
  common/nicknames/00_nicknames.txt
  common/on_actions/00_on_actions.txt
  common/religions/00_religions.txt
  common/scripted_effects/04_scripted_effects_crusades.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/01_scripted_triggers_combat.txt
  common/succession_voting/01_succession_voting_specials.txt
  common/wonder_upgrades/00_wonder_upgrades.txt
  common/wonders/00_wonders.txt
  common/wonders/wc_wonders.txt
  decisions/HF_religious_decisions.txt
  decisions/LT_936_decisions.txt
  decisions/minor_decisions.txt
  decisions/realm_decisions.txt
  decisions/wonder_decisions.txt
  events/LT_936_events.txt
  events/LT_wonder_flavor_events.txt
  events/LT_wonder_maintenance_events.txt
  events/dutch_renaming_events.txt
  events/evil_events.txt
  events/lovers_events.txt
  events/mongol_events.txt
  events/rip_eternal_life_events.txt
Labels: :exclamation: priority critical, :ice_cream: vanilla modification :icecream:

#386 Alternative Event Pictures
  common/government_flavor/00_government_flavor.txt
  common/religions/dragon_religion_group.txt
  common/religions/elemental_lords_group.txt
  common/religions/primitive_group.txt
  common/religions/secular_group.txt
  common/religions/vrykul_religion_group.txt
  decisions/wc_religion_decisions.txt
  events/wc_loa_events.txt
  events/wc_primitive_events.txt
  events/wc_religious_events.txt
  events/wc_sad.txt
  gfx/event_pictures/ancient.tga
  gfx/event_pictures/arakkoa_cultist.tga
  gfx/event_pictures/arakkoa_peaks.tga
  gfx/event_pictures/arakkoa_priest.tga
  gfx/event_pictures/arcanist.tga
  gfx/event_pictures/black_temple.tga
  gfx/event_pictures/candle_temple.tga
  gfx/event_pictures/dalaran.tga
  gfx/event_pictures/dancing_nightbornes.tga
  gfx/event_pictures/darnassus.tga
  gfx/event_pictures/druidic_forest.tga
  gfx/event_pictures/duel0.tga
  gfx/event_pictures/duel1.tga
  gfx/event_pictures/duel2.tga
  gfx/event_pictures/duel3.tga
  gfx/event_pictures/duel4.tga
  gfx/event_pictures/duel5.tga
  gfx/event_pictures/durotan.tga
  gfx/event_pictures/fel_inquisitor.tga
  gfx/event_pictures/jade_forest.tga
  gfx/event_pictures/kobold_mage.tga
  gfx/event_pictures/kobold_monk.tga
  gfx/event_pictures/kobold_treasury.tga
  gfx/event_pictures/mage_in_library.tga
  gfx/event_pictures/murloc_oracle.tga
  gfx/event_pictures/murloc_pool.tga
  gfx/event_pictures/murloc_seer.tga
  gfx/event_pictures/nerubian_temple.tga
  gfx/event_pictures/pandaren_couple.tga
  gfx/event_pictures/pandaren_lorewalker.tga
  gfx/event_pictures/pandaren_monk.tga
  gfx/event_pictures/rape.dds
  gfx/event_pictures/reef.tga
  gfx/event_pictures/shaman_stones.tga
  gfx/event_pictures/shaman_tauren.tga
  gfx/event_pictures/troll_ceremony.tga
  gfx/event_pictures/twisted_forest.tga
  gfx/event_pictures/vizier.tga
  gfx/event_pictures/void_elves_couple.tga
  interface/wc_alternative_event_pictures.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#414 Demonic Cuties
  artist_resources/races/creature_shivarra/creature_shivarra.xcf
  common/cultures/culture_demonic.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_race_events.txt
  gfx/characters/nathrezim_female/nathrezim_female_base_1.dds
  gfx/characters/nathrezim_female/nathrezim_female_neck_1.dds
  gfx/characters/shivarra_female/shivarra_female_base_1.dds
  gfx/characters/shivarra_female/shivarra_female_neck_1.dds
  gfx/traits/creature_shivarra.dds
  interface/portraits/portraits_annihilan.gfx
  interface/portraits/portraits_annihilan_sprites.gfx
  interface/portraits/portraits_nathrezim.gfx
  interface/portraits/portraits_nathrezim_sprites.gfx
  interface/wc_traits.gfx
  localisation/wc_traits.csv
  localisation_rus/000_ru_wc_traits.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#395 Inhuman Marriages
  artist_resources/other_traits/blood.xcf
  artist_resources/races/creature_magnataur/creature_magnataur.xcf
  common/dynasties/2000_orc.txt
  common/game_rules/000_wc_game_rules.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/nicknames/wc_nicknames.txt
  common/scripted_effects/05_scripted_effects_competitions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_blood_traits.txt
  common/traits/wc_race_traits.txt
  decisions/wc_test_decisions.txt
  events/HF_bloodline_acquisition_events.txt
  events/traits_effects_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_race_events.txt
  gfx/traits/blood/blood_centaur.dds
  gfx/traits/blood/blood_draenei.dds
  gfx/traits/blood/blood_dryad.dds
  gfx/traits/blood/blood_frostnymph.dds
  gfx/traits/blood/blood_high_elf.dds
  gfx/traits/blood/blood_highborne.dds
  gfx/traits/blood/blood_human.dds
  gfx/traits/blood/blood_magnataur.dds
  gfx/traits/blood/blood_night_elf.dds
  gfx/traits/blood/blood_ogre.dds
  gfx/traits/blood/blood_orc.dds
  gfx/traits/blood/blood_taunka.dds
  gfx/traits/blood/blood_tauren.dds
  gfx/traits/blood/blood_vrykul.dds
  gfx/traits/creature_centaur.dds
  gfx/traits/creature_magnataur.dds
  history/characters/10000_orc.txt
  history/characters/1_azerothian.txt
  history/characters/42000_high_elf.txt
  interface/wc_traits.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/wc_cultures.csv
  localisation/wc_sad.csv
  localisation/wc_traits.csv
  localisation_rus/000_ru_wc_traits.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#437 Artifacts standardization
  common/artifacts/000_wc_artifacts.txt
  common/artifacts/000_wc_generic_artifacts_hats.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#432 Sub-Culture Buildings for MO (WIP)
  common/buildings/wc_castle.txt
  common/buildings/wc_city.txt
  common/buildings/wc_sub_human.txt
  common/buildings/wc_temple.txt
  common/buildings/wc_tuskarr.txt
  localisation/wc_culture_buildings.csv
Labels: :balance_scale: balance :balance_scale:, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:, :star: new feature :new:
