Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-03, with the labels that each got.

#214 3rd Small Improvements
  common/buildings/wc_uniques.txt
  common/cb_types/wc_cb_types.txt
  common/defines/00_dummy.lua
  common/game_rules/000_wc_game_rules.txt
  common/minor_titles/wc_minor_titles.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/objectives/00_factions.txt
  common/on_actions/00_on_actions.txt
  common/religions/fel_group.txt
  common/religions/necromancy_group.txt
  common/religions/void_group.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/00_traits.txt
  common/traits/01_traits.txt
  common/traits/02_traits.txt
  common/traits/wc_health_traits.txt
  common/traits/wc_lifestyle_traits.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_special_traits.txt
  decisions/employment_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_test_decisions.txt
  decisions/wc_undead_decisions.txt
  decisions/wc_war_decisions.txt
  events/wc_beyond_dp.txt
  events/wc_dark_cult_events.txt
  events/wc_fel_events.txt
  events/wc_first_war_events.txt
  events/wc_plague_events.txt
  events/wc_politfaction_events.txt
  events/wc_race_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  events/wc_war_events.txt
  history/characters/42000_high_elf.txt
  history/titles/c_silverfury.txt
  history/titles/c_windrunner.txt
  history/titles/d_shalandis.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :star: new feature :new:

#215 Fixes sejtalk
  common/event_modifiers/wc_event_modifiers.txt
  common/objectives/00_focuses.txt
  common/offmap_powers/wc_offmap_yogg_saron.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/way_of_life_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_religion_decisions.txt
  decisions/wc_sad_society.txt
  events/wc_offmap_events.txt
  localisation/wc_offmap.csv
  localisation/wc_sad.csv
Labels: :wrench: bug fix :hammer:

#219 AI Fleet Navigation
  map/adjacencies.csv
  map/geographical_region.txt
  map/island_region.txt
Labels: :wrench: bug fix :hammer:

#228 7th Bug Crusade
  common/governments/feudal_governments.txt
  common/laws/succession_laws.txt
  common/laws/wc_misc_laws.txt
  common/laws/wc_succession_laws.txt
  common/on_actions/00_on_actions.txt
  common/opinion_modifiers/00_opinion_modifiers.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_test_decisions.txt
  decisions/wc_undead_decisions.txt
  decisions/wc_war_decisions.txt
  events/on_action_events.txt
  events/plot_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_dark_cult_events.txt
  events/wc_druidic_events.txt
  events/wc_duel_events.txt
  events/wc_plague_events.txt
  events/wc_race_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_void_events.txt
  gfx/flags/k_cenarion_circle_fake.tga
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/default.map
  map/island_region.txt
  map/provinceDef.xls
Labels: :wrench: bug fix :hammer:

#226 Pirates
  common/cb_types/00_cb_types.txt
  common/cultures/culture_human.txt
  common/dynasties/44000_pirate.txt
  common/dynasties/60000_pirate.txt
  common/landed_titles/wc_mercenary_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/02_traits.txt
  events/oldgods_various_events.txt
  events/wc_job_explorer.txt
  history/characters/90000_pirate.txt
  history/provinces/3533 - Freehold.txt
  history/provinces/3564 - Forlorn_3.txt
  history/provinces/3569 - Polder Crag.txt
  history/provinces/705 - Scalawag Point.txt
  history/provinces/706 - Sorlofs Strand.txt
  history/provinces/817 - Strand of Ancients.txt
  history/provinces/823 - Farshire.txt
  history/provinces/833 - Abanreach.txt
  history/provinces/949 - Dragon Isles.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_cultures.csv
  map/provinceDef.xls
Labels: :hammer: maintenance :wrench:, :star: new feature :new:

#45 duchy/kingdom/empire flags EK
  gfx/flags/d_redridge_mountains.tga
Labels: :art: graphics :paintbrush:

#250 Corrupted Blood Diseases
  artist_resources/other_traits/corrupted_blood.xcf
  common/disease/00_disease.txt
  common/disease/wc_disease.txt
  common/nicknames/00_nicknames.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_disease_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_disease_score_values.txt
  common/scripted_score_values/wc_vanilla_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/succession_voting/00_succession_voting.txt
  common/succession_voting/01_succession_voting_specials.txt
  common/succession_voting/wc_succession_voting.txt
  common/traits/wc_health_traits.txt
  decisions/mnm_hermetics_decisions.txt
  decisions/rip_various_decisions.txt
  decisions/way_of_life_decisions.txt
  events/HFP_health_events.txt
  events/battle_events.txt
  events/court_events.txt
  events/friends_rivals_events.txt
  events/hedge_knights_events.txt
  events/married_life_events.txt
  events/mnm_devil_worshipers_events.txt
  events/rip_seclusion_events.txt
  events/rip_symptom_events.txt
  events/rip_treatment_events.txt
  events/wc_disease_events.txt
  events/wc_plague_events.txt
  events/wol_carousing_events.txt
  gfx/traits/corrupted_blood.dds
  interface/wc_traits.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_traits.csv
  localisation_rus/000_ru_wc_traits.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :ice_cream: vanilla modification :icecream:, :star: new feature :new:
