Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-12, with the labels that each got.

#965 Bloodhoof Runespear Artifact
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/000_wc_artifacts.txt
  gfx/interface/inventory/artifacts/bloodhoof_runespear.dds
  gfx/interface/inventory/artifacts/bloodhoof_runespear_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low, :page_facing_up: localization :pen:

#971 Frost Nymph Portrait Issue
  interface/portraits/portraits_frostnymph.gfx
  interface/portraits/portraits_frostnymph_sprites.gfx
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#926 Political Factions Game Rule
  common/game_rules/000_wc_game_rules.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  decisions/wc_politfaction_decisions.txt
  events/wc_third_war_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localization :pen:, :star: new feature :new:

#979 Artifact Sorting
  common/artifacts/000_wc_artifacts.txt
  common/artifacts/000_wc_slots.txt
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded_generic.txt
  common/artifacts/902_wc_artifacts_crown_crowns.txt
  common/artifacts/902_wc_artifacts_crown_hats_generic.txt
  common/artifacts/903_wc_artifacts_wrist.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  common/artifacts/907_wc_artifacts_ring.txt
  common/artifacts/908_wc_artifacts_relic.txt
  common/artifacts/909_wc_artifacts_library.txt
  common/artifacts/909_wc_artifacts_library_librams.txt
  common/artifacts/910_wc_artifacts_leader.txt
  common/artifacts/999_wc_artifacts_other.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#982 Rebalancing of all Lore Artifacts
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/902_wc_artifacts_crown_crowns.txt
  common/artifacts/902_wc_artifacts_crown_hats_generic.txt
  common/artifacts/903_wc_artifacts_wrist.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  common/artifacts/907_wc_artifacts_ring.txt
  common/artifacts/908_wc_artifacts_relic.txt
  common/artifacts/909_wc_artifacts_library.txt
  common/artifacts/909_wc_artifacts_library_librams.txt
  common/artifacts/910_wc_artifacts_leader.txt
  common/artifacts/999_wc_artifacts_other.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#969 Disband Faction/Leave Faction if you're Leader
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  decisions/wc_politfaction_decisions.txt
  events/wc_politfaction_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localization :pen:, :star: new feature :new:

#981 Mind Control Refactoring
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_plague_events.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#986 4th Patron Batch
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/titles/c_northpass.txt
  history/titles/c_splurmurslr.txt
  history/titles/c_tyrs_hand.txt
  interface/portrait_properties/00_portrait_properties.txt
Labels: :exclamation: priority high, :star: new feature :new:

#951 7th Localisation Crusade 📜⚔
  localisation/000_wc_military_localization.csv
  localisation/000_wc_traits.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_HolyFury.csv
  localisation/00_ciwc_united_localisation.csv
  localisation/00_traits.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:

#879 Removing DLC Requirements from Mod
  common/artifact_spawns/wc_artifact_spawns.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_ogre_decisions.txt
  decisions/wc_politfaction_decisions.txt
  events/wc_cenarion_circle_events.txt
  events/wc_dark_cult_events.txt
  events/wc_fel_events.txt
  events/wc_frostwolf_events.txt
  events/wc_light_events.txt
  events/wc_offmap_events.txt
  events/wc_quest_events.txt
  events/wc_race_events.txt
  events/wc_tomb_events.txt
  events/wc_traditions_events.txt
  events/wc_troll_events.txt
  events/wc_void_events.txt
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/1_azerothian.txt
  history/characters/22000_wildhammer.txt
  history/characters/320000_centaur.txt
  history/characters/340000_night_elf.txt
  history/characters/38000_arathorian.txt
  history/characters/410000_dryad.txt
  history/characters/42000_high_elf.txt
  history/characters/48000_tirassian.txt
  history/characters/57000_amani.txt
  history/characters/60000_lordaeronian.txt
  history/characters/62000_dragon.txt
  history/characters/66000_zandalari.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#1002 #527 fix
  common/scripted_effects/wc_history_scripted_effects.txt
  history/characters/10000_orc.txt
  history/characters/150000_naga.txt
  history/characters/430000_nathrezim.txt
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#1001 Focus requirements
  common/objectives/00_focuses.txt
  decisions/HF_sway_antagonize_decisions.txt
  decisions/way_of_life_decisions.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#963 14th Small Improvements
  common/cultures/culture_human.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/religions/primitive_group.txt
  common/religions/vrykul_religion_group.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/societies/wc_societies.txt
  common/traits/00_traits.txt
  common/traits/02_traits.txt
  decisions/wc_class_decisions.txt
  decisions/wc_politfaction_decisions.txt
  events/wc_class_events.txt
  events/wc_undead_events.txt
  history/characters/10000_orc.txt
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_cultures.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localization :pen:, :star: new feature :new:

#1012 Artifact icons (new and remade)
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  gfx/interface/inventory/artifacts/ancient_kernel.dds
  gfx/interface/inventory/artifacts/ancient_kernel_small.dds
  gfx/interface/inventory/artifacts/apocalypse.dds
  gfx/interface/inventory/artifacts/apocalypse_small.dds
  gfx/interface/inventory/artifacts/ashbringer.dds
  gfx/interface/inventory/artifacts/ashbringer_small.dds
  gfx/interface/inventory/artifacts/atiesh.dds
  gfx/interface/inventory/artifacts/atiesh_small.dds
  gfx/interface/inventory/artifacts/bloodhoof_runespear.dds
  gfx/interface/inventory/artifacts/bloodhoof_runespear_small.dds
  gfx/interface/inventory/artifacts/doomhammer.dds
  gfx/interface/inventory/artifacts/doomhammer_og.dds
  gfx/interface/inventory/artifacts/doomhammer_og_small.dds
  gfx/interface/inventory/artifacts/doomhammer_small.dds
  gfx/interface/inventory/artifacts/remnant_caer_darrow.dds
  gfx/interface/inventory/artifacts/remnant_caer_darrow_small.dds
  gfx/interface/inventory/artifacts/runeblade_blood.dds
  gfx/interface/inventory/artifacts/runeblade_blood_small.dds
  gfx/interface/inventory/artifacts/runeblade_frost.dds
  gfx/interface/inventory/artifacts/runeblade_frost_small.dds
  gfx/interface/inventory/artifacts/runeblade_unholy.dds
  gfx/interface/inventory/artifacts/runeblade_unholy_small.dds
  gfx/interface/inventory/artifacts/scythe_of_elune.dds
  gfx/interface/inventory/artifacts/scythe_of_elune_small.dds
  gfx/interface/inventory/artifacts/silver_hand.dds
  gfx/interface/inventory/artifacts/silver_hand_small.dds
  gfx/interface/inventory/artifacts/tauren_totem.dds
  gfx/interface/inventory/artifacts/tauren_totem_small.dds
  gfx/interface/inventory/artifacts/xalatath.dds
  gfx/interface/inventory/artifacts/xalatath_small.dds
  history/characters/10000_orc.txt
  interface/wc_treasury.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1013 Scarlet Refactoring
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  events/wc_light_events.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1006 Twin Blades and Gorehowl
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  events/wc_second_war_events.txt
  gfx/interface/inventory/artifacts/gorehowl.dds
  gfx/interface/inventory/artifacts/gorehowl_small.dds
  gfx/interface/inventory/artifacts/twin_blades_of_azzinoth.dds
  gfx/interface/inventory/artifacts/twin_blades_of_azzinoth_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1009 Balancing of vanilla smith artifacts
  common/artifacts/00_artifacts.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :ice_cream: vanilla modification :icecream:

#950 Trade Post Cultural Buildings
  common/buildings/00_tradepost.txt
  common/buildings/wc_tradepost_culture.txt
  common/buildings/wc_tradepost_religion.txt
  common/scripted_triggers/wc_trade_triggers.txt
  localisation/00_ciwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#970 Issue #901 Fix
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  decisions/wc_test_decisions.txt
  events/wc_politfaction_events.txt
  history/titles/e_lordaeron.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1010 22th Bug Crusade
  common/artifact_spawns/wc_artifact_spawns.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/religions/elemental_lords_group.txt
  common/religions/secular_group.txt
  decisions/wc_politfaction_decisions.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  history/characters/17000_28000_bronzebeard.txt
  history/titles/c_irongate.txt
  history/titles/d_deep_elem.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1027 Ah Shit, Here We Go Again: Sorting Stuff
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_doomhammer.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_doomhammer_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_knife_1h_artifactcthun_d_01_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_mace_2h_artifactsilverhand_d_01_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_scythe_of_elune.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_scythe_of_elune_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_staff_medivh_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_sword_2h_artifactashbringer_d_01.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_sword_2h_artifactashbringer_d_01_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_sword_2h_artifactsoulrend_d_01_small.dds
  .artist_resources/_unused/gfx/interface/inventory/artifacts/inv_the_silver_hand_small.dds
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#1028 Stereotypes Game Rule Rework
  common/game_rules/000_wc_game_rules.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  events/job_chancellor.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1030 Recolored Modifier Icons
  common/event_modifiers/wc_event_modifiers.txt
  gfx/interface/modifier_icons.dds
  interface/province.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1029 Book rename
  common/artifacts/01_artifacts_books.txt
  events/jd_artifact_events.txt
  gfx/interface/inventory/artifacts/steamy_novel_1.dds
  gfx/interface/inventory/artifacts/steamy_novel_1_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_2.dds
  gfx/interface/inventory/artifacts/steamy_novel_2_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_3.dds
  gfx/interface/inventory/artifacts/steamy_novel_3_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_4.dds
  gfx/interface/inventory/artifacts/steamy_novel_4_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_5.dds
  gfx/interface/inventory/artifacts/steamy_novel_5_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_6.dds
  gfx/interface/inventory/artifacts/steamy_novel_6_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_7.dds
  gfx/interface/inventory/artifacts/steamy_novel_7_small.dds
  gfx/interface/inventory/artifacts/steamy_novel_8.dds
  gfx/interface/inventory/artifacts/steamy_novel_8_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority low, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:

#1033 Abdication Effects
  common/scripted_effects/wc_scripted_effects.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#975 Issue #908 Fix
  common/landed_titles/00_rebels.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1034 23rd Bug Crusade
  common/minor_titles/00_minor_titles.txt
  common/minor_titles/01_minor_title_wonders.txt
  common/objectives/00_LT_ambitions.txt
  common/objectives/00_plots.txt
  common/scripted_score_values/wc_vanilla_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/HFP_crusades.txt
  decisions/HF_religious_decisions.txt
  decisions/minor_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_undead_decisions.txt
  decisions/wonder_decisions.txt
  events/HFP_crusade_flavour.txt
  events/HFP_eldership_events.txt
  events/HFP_pregnancy_events.txt
  events/HF_bloodline_events.txt
  events/HF_religious_events.txt
  events/jd_grace_decision_events.txt
  events/oldgods_various_events.txt
  events/rip_maimed_events.txt
  events/soa_various_events.txt
  events/wc_undead_events.txt
  events/wol_war_events.txt
  events/ze_various_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#913 Cenarion Fixes
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_congenital_traits.txt
  decisions/realm_decisions.txt
  history/titles/d_murcevin.txt
Labels: :beetle: bug :beetle:, :grey_exclamation: priority low

#1044 Dazar'alor Renamed
  localisation/000_Other_title_names.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#1045 Paladin DNA
  history/characters/60000_lordaeronian.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1050 Sin'dorei Flag
  common/landed_titles/wc_titular_titles.txt
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_third_war_events.txt
  gfx/flags/d_sindorei.tga
  history/titles/d_sindorei.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1042 Archi and kil
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/traits/wc_special_traits.txt
  events/wc_fel_events.txt
  gfx/characters/shared/demons.dds
  gfx/interface/inventory/artifacts/scepter_of_sargeras.dds
  gfx/interface/inventory/artifacts/scepter_of_sargeras_small.dds
  gfx/interface/inventory/artifacts/warblade_of_archimonde.dds
  gfx/interface/inventory/artifacts/warblade_of_archimonde_small.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_eredar.gfx
  interface/portraits/portraits_overlay.gfx
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :star: new feature :new:
