Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-01, with the labels that each got.

#2 Delete Duplicate Bugs Report Template
  .github/ISSUE_TEMPLATE/origination-request--bugs-.md
Labels: :book: documentation :books:, :paperclips: duplicate :paperclips:

#1 Creating Initial Documentation for Repository
  CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: :book: documentation :books:, :exclamation: test :exclamation:

#12 Adjustments to Repository to Accommodate Issues
  CONTRIBUTING.md
Labels: :book: documentation :books:

#15 1st Bug Crusade
  common/cb_types/00_cb_types.txt
  common/landed_titles/01_landed_titles.txt
  common/laws/succession_laws.txt
  common/scripted_effects/06_scripted_effects_legendary_bloodlines.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/rip_prosperity_events.txt
  events/wc_race_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  gfx/characters/titanwatcher_female/titans/eonar.dds
  history/characters/400000_titan.txt
  history/provinces/102 - Ironforge.txt
  interface/portraits/portraits_titanwatcher.gfx
  interface/portraits/portraits_titanwatcher_sprites.gfx
  localisation/00_Barony_names.csv
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
  map/provinceDef.xls
Labels: :art: graphics :paintbrush:, :wrench: bug fix :hammer:

#18 New Rule (GDC)
  CONTRIBUTING.md
  README.md
Labels: :book: documentation :books:

#26 Rule Changes (GDC)
  CONTRIBUTING.md
  README.md
Labels: :book: documentation :books:

#40 Druid Form Flags
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_triggers/sad_scripted_triggers.txt
  events/wc_class_events.txt
  history/characters/340000_night_elf.txt
Labels: :hammer: maintenance :wrench:

#52 Update Changelog Rules
  CONTRIBUTING.md
  README.md
Labels: :book: documentation :books:, :hammer: maintenance :wrench:

#67 2nd Bug Crusade
  artist_resources/races/creature_sayaadi/creature_sayaadi.xcf
  artist_resources/races/creature_sayaadi/creature_sayaadi_contrast.xcf
  common/cb_types/wc_cb_types.txt
  common/landed_titles/00_rebels.txt
  common/landed_titles/z_holy_sites.txt
  common/landed_titles/z_landed_titles_eastern_kingdoms.txt
  common/landed_titles/z_landed_titles_great_sea.txt
  common/landed_titles/z_landed_titles_kalimdor.txt
  common/landed_titles/z_landed_titles_northrend.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/oldgods_blot_events.txt
  events/wc_politfaction_events.txt
  events/wc_primitive_events.txt
  events/wc_race_events.txt
  events/wc_realm_events.txt
  events/wc_shamanistic_events.txt
  events/wc_void_events.txt
  events/wol_hunting_events.txt
  events/ze_childhood_events.txt
  gfx/traits/creature_sayaadi.dds
  interface/wc_traits.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_sad.csv
Labels: :wrench: bug fix :hammer:

#77 Being Traits
  artist_resources/other_traits/being_void/being_void.xcf
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/disease/wc_disease.txt
  common/governments/feudal_governments.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_combat_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_being_traits.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_special_traits.txt
  decisions/rip_torture_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_undead_decisions.txt
  events/rip_physician_events.txt
  events/roi_various_events.txt
  events/wc_class_events.txt
  events/wc_court_events.txt
  events/wc_dark_cult_events.txt
  events/wc_duel_events.txt
  events/wc_fel_events.txt
  events/wc_offmap_events.txt
  events/wc_plague_events.txt
  events/wc_race_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_tomb_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  events/wc_vrykul_events.txt
  gfx/traits/being_demon.dds
  gfx/traits/being_undead.dds
  gfx/traits/being_void.dds
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/110000_scourge.txt
  history/characters/120000_nraqi.txt
  history/characters/140000_satyr.txt
  history/characters/150000_naga.txt
  history/characters/240000_qiraji.txt
  history/characters/340000_night_elf.txt
  history/characters/360000_eredruin.txt
  history/characters/60000_lordaeronian.txt
  history/characters/66000_zandalari.txt
  history/characters/76000_nerubian.txt
  interface/portrait_properties/00_portrait_properties.txt
  interface/wc_traits.gfx
  localisation/wc_traits.csv
  localisation_rus/000_ru_wc_traits.csv
Labels: :star: new feature :new:

#38 Ancients
  artist_resources/races/ancients/IconSmall_LoreAncient.gif
  artist_resources/races/ancients/IconSmall_ProtectorAncient.gif
  artist_resources/races/ancients/IconSmall_WarAncient.gif
  artist_resources/races/ancients/IconSmall_WindAncient.gif
  artist_resources/races/ancients/ancients.xcf
  artist_resources/races/ancients/ancients_contrast.xcf
  common/artifacts/000_wc_artifacts.txt
  common/cultures/culture_ancient.txt
  common/dynasties/160000_ancient .txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/societies/wc_societies.txt
  common/traits/wc_race_traits.txt
  decisions/wc_class_decisions.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_religion_decisions.txt
  events/wc_court_events.txt
  events/wc_offmap_events.txt
  events/wc_race_events.txt
  events/wc_sad.txt
  gfx/characters/ancient_child/ancient_child_male.dds
  gfx/characters/ancient_male/ancient_lore_male_eyes_1.dds
  gfx/characters/ancient_male/ancient_male_base_1.dds
  gfx/characters/ancient_male/ancient_war_male_eyes_1.dds
  gfx/characters/ancient_male/ancient_wind_male_eyes_1.dds
  gfx/characters/ancient_male/protectors_male_eyes_1.dds
  gfx/interface/decision_icons/summon_ancient.dds
  gfx/interface/inventory/artifacts/ancient_kernel_small.dds
  gfx/traits/creature_ancient_lore.dds
  gfx/traits/creature_ancient_war.dds
  gfx/traits/creature_ancient_wind.dds
  gfx/traits/creature_protector.dds
  history/characters/420000_ancients.txt
  interface/portraits/portraits_ancient_sprites.gfx
  interface/portraits/portraits_ancients.gfx
  interface/wc_decision_icons.gfx
  interface/wc_traits.gfx
  interface/wc_treasury.gfx
  localisation/wc_sad.csv
Labels: :art: graphics :paintbrush:, :balance_scale: balance :balance_scale:, :page_facing_up: localization :pen:, :star: new feature :new:

#96 Moved dragon-related events to wc_race_events.txt (GDC)
  common/on_actions/00_on_actions.txt
  events/wc_dragon_events.txt
  events/wc_race_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :hammer: maintenance :wrench:
