Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2019-09, with the labels that each got.

#665 11th Small Improvements
  common/cb_types/00_cb_types.txt
  common/cb_types/01_cb_types.txt
  common/cb_types/02_cb_types_shattered_world.txt
  common/cultures/culture_human.txt
  common/cultures/culture_quilboar.txt
  common/cultures/culture_satyr.txt
  common/game_rules/000_wc_game_rules.txt
  common/governments/tribal_governments.txt
  common/landed_titles/wc_titular_titles.txt
  common/landed_titles/z_landed_titles_eastern_kingdoms.txt
  common/mercenaries/wc_mercenaries.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_scripted_class_values.txt
  common/scripted_score_values/wc_vanilla_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/02_traits.txt
  common/traits/wc_race_traits.txt
  decisions/realm_decisions.txt
  decisions/rip_torture_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_order_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_realm_decisions.txt
  events/rip_seclusion_events.txt
  events/rip_symptom_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  events/wc_loa_events.txt
  events/wc_order_events.txt
  events/wc_primitive_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  events/wol_carousing_events.txt
  events/wol_theology_events.txt
  gfx/event_pictures/korkron.tga
  gfx/flags/d_karazhan.tga
  gfx/interface/decision_icons/form_korkron.dds
  history/characters/16000_gnome.txt
  history/titles/c_gjalerbron.txt
  history/titles/c_grizzlemaw.txt
  history/titles/c_icecrown.txt
  history/titles/c_icemist.txt
  history/titles/c_low_fields.txt
  history/titles/c_mightstone.txt
  history/titles/c_silentreach.txt
  history/titles/c_wintergarde.txt
  history/titles/d_karazhan.txt
  history/titles/d_korkron.txt
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_zuwc_united_localisation.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :star: new feature :new:

#686 Minor-fixes-1
  common/artifacts/000_wc_artifacts.txt
  common/bloodlines/wc_earned_bloodlines.txt
  common/cb_types/wc_cb_types.txt
  common/combat_tactics/00_combat_tactics.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_class_values.txt
  common/traits/wc_congenital_traits.txt
  common/traits/wc_race_traits.txt
  decisions/wc_sad_society.txt
  events/sunset_invasion.txt
  events/wc_loa_events.txt
  events/wc_race_events.txt
  events/wc_society_events.txt
  history/characters/100000_vrykul.txt
  history/characters/10000_orc.txt
  history/characters/11000_dark_iron.txt
  history/characters/150000_naga.txt
  history/characters/1_azerothian.txt
  history/characters/200000_farraki.txt
  history/characters/250000_harpy.txt
  history/characters/360000_eredruin.txt
  history/characters/400000_titan.txt
  history/characters/48000_tirassian.txt
  history/characters/60000_lordaeronian.txt
  history/characters/6000_gurubashi.txt
  history/characters/90000_pirate.txt
  history/provinces/205 - Direforge.txt
  history/provinces/916 - Silentreach.txt
  localisation/00_zuwc_united_localisation.csv
  music/goa_main_music.txt
  music/world_of_warcraft_crystalsong.ogg
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#688 Military Overhaul: the Icons
  artist_resources/leadership_traits/cavalry_leader.xcf
  artist_resources/leadership_traits/light_foot_leader.xcf
  artist_resources/units/animals.xcf
  artist_resources/units/archmage.xcf
  artist_resources/units/caster.xcf
  artist_resources/units/cavalry.xcf
  artist_resources/units/elite.xcf
  artist_resources/units/infantry.xcf
  artist_resources/units/large_cavalry.xcf
  artist_resources/units/large_infantry.xcf
  artist_resources/units/thralls.xcf
  artist_resources/units/thralls_2.xcf
  artist_resources/units/wing.xcf
  common/special_troops/wc_special_troops.txt
  gfx/interface/unitpanel_specialunits_bigstrip.dds
  gfx/interface/unitpanel_specialunits_smallstrip.dds
  gfx/interface/unitpanel_unitstrip_big.dds
  gfx/interface/unitpanel_unitstrip_small.dds
  gfx/traits/cavalry_leader.dds
  gfx/traits/holy_warrior.dds
  gfx/traits/light_foot_leader.dds
  gfx/traits/wc_cavalry_leader.tga
  gfx/traits/wc_heavy_infantry_leader.tga
  gfx/traits/wc_light_foot_leader.tga
  interface/unitpanel.gfx
  interface/wc_traits.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#692 16th Bug Crusade
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/cultures/culture_titanforged.txt
  common/death/wc_death.txt
  common/game_rules/00_game_rules.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/objectives/00_focuses.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_substitute_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/societies/wc_societies.txt
  common/traits/wc_class_traits.txt
  common/traits/wc_race_traits.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_troll_decisions.txt
  events/family_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_class_events.txt
  events/wc_court_events.txt
  events/wc_diplomacy_events.txt
  events/wc_fel_events.txt
  events/wc_race_events.txt
  events/wc_third_war_events.txt
  events/wc_void_events.txt
  events/wol_business_events.txt
  history/characters/210000_tauren.txt
  history/characters/22000_wildhammer.txt
  history/characters/250000_harpy.txt
  history/characters/310000_patron_characters.txt
  history/characters/340000_night_elf.txt
  history/characters/400000_titan.txt
  history/characters/410000_dryad.txt
  history/characters/420000_ancients.txt
  history/characters/430000_nathrezim.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_lordaeronian.txt
  history/characters/62000_dragon.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religions.csv
  localisation/wc_traits.csv
  localisation_rus/000_ru_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#701 16.5th Bug Crusade
  events/wc_class_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#545 📜 Localisation Crusade ⚔ | 5th Chapter
  coder_resources/_unused/localisation/00_wc_buildings.csv
  coder_resources/_unused/localisation/not_used_strings.csv
  localisation/000_Other_title_names.csv
  localisation/00_wc_government.csv
  localisation/00_wc_job_titles.csv
  localisation/00_wc_offmap.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_special_units.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/ET_localisation.csv
  localisation/tyr_wc_loa.csv
  localisation/wc_combat.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
  localisation/wc_fel.csv
  localisation/wc_loa_event.csv
  localisation/wc_nomad.csv
  localisation/wc_oldgods.csv
  localisation/wc_religion_buildings.csv
  localisation/wc_religions.csv
  localisation/wc_traits.csv
  localisation/wc_uniques.csv
Labels: :exclamation: priority high, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:

#717 AI Title Destroyers
  common/defines/00_dummy.lua
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#689 Military Overhaul: the Artifacts
  common/artifacts/00_artifacts.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/mnm_artifacts_events.txt
  localisation/000_wc_military_localization.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation_units.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#722 Night Elven Holder Issues
  history/characters/340000_night_elf.txt
  history/titles/c_darkshore.txt
  history/titles/c_ealnow.txt
  history/titles/c_emeraran.txt
  history/titles/c_forest_song.txt
  history/titles/c_green_vale.txt
  history/titles/c_irontree.txt
  history/titles/c_jadefire.txt
  history/titles/c_ketedin.txt
  history/titles/c_malorne.txt
  history/titles/c_mists_edge.txt
  history/titles/c_moonvalley.txt
  history/titles/c_phullila.txt
  history/titles/c_thal_grove.txt
  history/titles/c_thethiru.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#731 Military Overhaul: the Mercenaries
  common/landed_titles/wc_mercenary_landed_titles.txt
  common/mercenaries/00_mercenaries.txt
  common/mercenaries/wc_mercenaries.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :wrench: bug fix :hammer:

#743 Remove infection upon becoming demon, fixes #737
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#753 EVTOPTB_WCCC.240 Fix
  events/wc_cc_missions.txt
  localisation/00_wc_sad.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#748 Fix WCUND.135 Localization (Scourge + Legion)
  events/wc_undead_events.txt
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#747 Remove Elemental Blessing after conversion
  events/wc_on_action_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#746 Fix typo in the Plague of Lordaeron event popup
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#758 Adjust One-Legged trait to Crippled
  localisation/00_traits.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#767 Correct Frostmourne original owner
  events/wc_third_war_events.txt
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#766 Fix Mind Control Failure not adding traits to target
  events/wc_class_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#770 Buildings don't use allow, use trigger instead
  common/buildings/wc_druidic.txt
  common/buildings/wc_uniques.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#764 Fix Silver Hand (and other Holy Orders) reference to wrong Religion on leave
  localisation/00_HolyFury.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#742 Localization Updates/Fixes
  localisation/000_Other_title_names.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#773 Fix Dryad Blood not applying
  common/scripted_effects/wc_scripted_effects.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#775 Fix Vault of Archavon + Great Forge unique builds
  common/buildings/wc_uniques.txt
  localisation/wc_uniques.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#774 Aliden Perenolde leads the Syndicate until Classic
  history/characters/58000_alteraci.txt
  history/titles/c_headland.txt
  history/titles/c_strahnbrad.txt
  history/titles/d_syndicate.txt
Labels: :grey_exclamation: priority low, :star: new feature :new:

#769 Fix the localization in WCUND.1301
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#786 590 Province Issue
  localisation/00_Province_names.csv
  map/climate.txt
  map/default.map
  map/definition.csv
  map/provinceDef.xls
Labels: :beetle: bug :beetle:, :exclamation: priority critical
