Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-12, with the labels that each got.

#1831 New Naga portraits
  gfx/characters/naga_female/naga_female_base_1.dds
  gfx/characters/naga_female/naga_female_clothes.dds
  gfx/characters/naga_female/naga_female_headgear.dds
  gfx/characters/naga_female/naga_female_neck_1.dds
  gfx/characters/naga_male/naga_male_base_1.dds
  gfx/characters/naga_male/naga_male_clothes.dds
  gfx/characters/naga_male/naga_male_headgear.dds
  gfx/characters/naga_male/naga_male_neck_1.dds
  interface/portraits/portraits_naga.gfx
  interface/portraits/portraits_naga_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1833 Naga holding icons
  common/religions/void_group.txt
  gfx/interface/holdings/nagagfx/province_capital_settlement_frame_nagagfx.dds
  gfx/interface/holdings/nagagfx/province_settlement_frame_nagagfx.dds
  gfx/interface/holdings/nagagfx/settlement_building_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_castle_nagafgfx_looted.tga
  gfx/interface/holdings/nagagfx/settlement_castle_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_city_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_city_nagagfx_looted.tga
  gfx/interface/holdings/nagagfx/settlement_new_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_temple_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_temple_nagagfx_looted.tga
  gfx/interface/holdings/nagagfx/settlement_tribal_empty_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_tribal_nagagfx.tga
  gfx/interface/holdings/nagagfx/settlement_tribal_nagagfx_looted.tga
  interface/wc_holdings.gfx
  interface/wc_mapitems.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1838 Hidden Random World
  interface/frontend.gui
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1807 Yak Statue
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/wonder_upgrades/wc_wonders_buildable_upgrades.txt
  common/wonders/00_wonders.txt
  common/wonders/wc_wonders_buildable.txt
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_yak_statue_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_yak_statue_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_yak_statue_small.dds
  interface/wc_wonder.gfx
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/08_custom_loc_wonder_setup.txt
  localisation/customizable_localisation/wc_customizable_localisation_wonders.txt
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :star: new feature :new:

#1839 Stone Tol'vir Fertility
  common/traits/wc_race_traits.txt
  interface/portraits/portraits_tolvir_sprites.gfx
Labels: :wrench: bug fix :hammer:

#1840 35th Bug Crusade
  common/cultures/culture_elemental.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/wonder_upgrades/00_wonder_upgrades.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_realm_decisions.txt
  events/roi_guru_events.txt
  events/wc_crisis_events.txt
  events/wc_dark_cult_events.txt
  events/wc_first_war_events.txt
  events/wc_on_action_events.txt
  events/wc_race_events.txt
  events/wc_second_war_events.txt
  events/wc_startup_events.txt
  interface/portraits/portraits_troll_sprites.gfx
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:
