Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-04, with the labels that each got.

#1206 Vrykuls and Giants
  common/traits/wc_special_traits.txt
  events/wc_realm_events.txt
  gfx/characters/frostvrykul_female/frostvrykul_female_base_1.dds
  gfx/characters/frostvrykul_female/frostvrykul_female_clothes.dds
  gfx/characters/frostvrykul_male/frostvrykul_male_base_1.dds
  gfx/characters/frostvrykul_male/frostvrykul_male_clothes.dds
  gfx/characters/icegiant_female/icegiant_female_base_1.dds
  gfx/characters/icegiant_male/icegiant_male_base_1.dds
  gfx/characters/kvaldir_female/kvaldir_female_base_1.dds
  gfx/characters/kvaldir_male/kvaldir_male_base_1.dds
  gfx/characters/kvaldir_male/kvaldir_male_headgear.dds
  gfx/characters/shared/vrykuls.dds
  gfx/characters/stormgiant_female/stormgiant_female_base_1.dds
  gfx/characters/stormgiant_male/stormgiant_male_base_1.dds
  gfx/characters/undead_vrykul_female/undead_vrykul_female_base_1.dds
  gfx/characters/undead_vrykul_female/undead_vrykul_female_clothes.dds
  gfx/characters/undead_vrykul_female/undead_vrykul_female_hair_ties_front.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_base_1.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_beard_1.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_beard_ties_front.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_clothes.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_hair_behind_1.dds
  gfx/characters/undead_vrykul_male/undead_vrykul_male_hair_ties_front.dds
  gfx/characters/vrykul_child/frost_child_female.dds
  gfx/characters/vrykul_child/frost_child_male.dds
  gfx/characters/vrykul_child/kvaldir_child_female.dds
  gfx/characters/vrykul_child/kvaldir_child_male.dds
  gfx/characters/vrykul_child/vrykul_child_female.dds
  gfx/characters/vrykul_child/vrykul_child_male.dds
  gfx/characters/vrykul_female/vrykul_female_base_1.dds
  gfx/characters/vrykul_female/vrykul_female_clothes.dds
  gfx/characters/vrykul_female/vrykul_female_hair_1.dds
  gfx/characters/vrykul_female/vrykul_female_hair_behind_1.dds
  gfx/characters/vrykul_female/vrykul_female_hair_ties_front.dds
  gfx/characters/vrykul_male/vrykul_male_base_1.dds
  gfx/characters/vrykul_male/vrykul_male_beard_1.dds
  gfx/characters/vrykul_male/vrykul_male_beard_ties_front.dds
  gfx/characters/vrykul_male/vrykul_male_clothes.dds
  gfx/characters/vrykul_male/vrykul_male_hair_1.dds
  gfx/characters/vrykul_male/vrykul_male_hair_behind_1.dds
  gfx/characters/vrykul_male/vrykul_male_hair_ties_front.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_demonform.gfx
  interface/portraits/portraits_frostvrykul.gfx
  interface/portraits/portraits_frostvrykul_sprites.gfx
  interface/portraits/portraits_icegiant.gfx
  interface/portraits/portraits_icegiant_sprites.gfx
  interface/portraits/portraits_kvaldir.gfx
  interface/portraits/portraits_kvaldir_sprites.gfx
  interface/portraits/portraits_overlay.gfx
  interface/portraits/portraits_stormgiant.gfx
  interface/portraits/portraits_stormgiant_sprites.gfx
  interface/portraits/portraits_undead_vrykul.gfx
  interface/portraits/portraits_undead_vrykul_sprites.gfx
  interface/portraits/portraits_vrykul.gfx
  interface/portraits/portraits_vrykul_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1293 Memefixes 4
  .artist_resources/decision_icons/blood_rituals.dds
  .coder_resources/_unused/decisions/wc_dark_cult_decisions.txt
  .coder_resources/_unused/event_modifiers/wc_event_modifiers.txt
  .coder_resources/_unused/events/wc_dark_cult_events.txt
  .coder_resources/_unused/localisation/not_used_strings.csv
  common/artifact_spawns/wc_artifact_spawns.txt
  common/cb_types/01_cb_types.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/landed_titles/z_landed_titles_eastern_kingdoms.txt
  common/religions/00_religions.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_effects/wc_artifacts_historical_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  decisions/mnm_hermetics_decisions.txt
  decisions/way_of_life_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/HF_religious_events.txt
  events/wc_dark_cult_events.txt
  events/wc_primitive_events.txt
  gfx/interface/societies/society_exp_bg_sisterhood_of_elune.dds
  history/characters/10000_orc.txt
  interface/wc_decision_icons.gfx
  interface/wc_treasury.gfx
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :ice_cream: vanilla modification :icecream:, :page_facing_up: localisation :pen:

#1376 Nerglish (water deities) have no sky burial
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/minor_decisions.txt
  events/hl_extra_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1379 Remove barrow dens after conversion
  events/wc_on_action_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1389 Github now ignores desktop.ini
  .gitignore
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#948 Class Mentoring Rework
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/opinion_modifiers/wc_opinion_modifiers.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  events/wc_class_events.txt
  events/wc_first_war_events.txt
  interface/domestic_diplomacy.gui
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1353 Old god decisions
  common/event_modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_sacrifice_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  decisions/wc_offmap_decisions.txt
  events/wc_on_action_events.txt
  localisation/00_wc_offmap.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#1371 16th Small Improvments
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  common/traits/wc_class_traits.txt
  common/traits/wc_race_traits.txt
  decisions/wc_class_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_test_decisions.txt
  events/wc_emerald_dream_events.txt
  events/wc_fel_events.txt
  events/wc_realm_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  history/characters/340000_night_elf.txt
  history/characters/76000_nerubian.txt
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1362 Ulduar
  common/event_modifiers/wc_event_modifiers.txt
  common/on_actions/00_on_actions.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_titanforged_events.txt
  gfx/event_pictures/thorim_sif.tga
  history/characters/100000_vrykul.txt
  history/characters/120000_nraqi.txt
  history/characters/400000_titan.txt
  history/provinces/1144 - Eanorah.txt
  history/provinces/858 - Ulduar.txt
  history/provinces/864 - Iahienal.txt
  history/titles/c_eanorah.txt
  history/titles/c_iahienal.txt
  history/titles/c_ulduar.txt
  history/titles/d_ulduar.txt
  history/titles/k_ulduar.txt
  interface/wc_event_pictures.gfx
  localisation/00_wc_sad.csv
  localisation/WikipediaLinks.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1391 Fixed affixes name
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  localisation/00_DEwc_united_localisation.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customisable_localisation_DE.txt
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1394 Changed Old Gods Triggers
  common/scripted_effects/wc_sacrifice_scripted_effects.txt
  common/scripted_triggers/wc_religious_triggers.txt
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#1253 Frozen Throne Localization
  localisation/000_Other_title_names.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religions.csv
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:

#1325 Frozen Events
  common/artifact_spawns/wc_artifact_spawns.txt
  common/bloodlines/wc_earned_bloodlines.txt
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/cultures/culture_goblin.txt
  common/game_rules/000_wc_game_rules.txt
  common/modifier_definitions/wc_bloodline_modifier_definitions.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_triggers/01_scripted_triggers_combat.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_order_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_undead_decisions.txt
  events/wc_druidic_events.txt
  events/wc_first_war_events.txt
  events/wc_frozen_throne_story_events.txt
  events/wc_light_events.txt
  events/wc_realm_events.txt
  events/wc_startup_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  gfx/event_pictures/scourge_march.tga
  gfx/interface/decision_icons/vassalize_d_scarlet_crusade.dds
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  interface/wc_other_pictures.gfx
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#1283 Frozen artifacts
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/908_wc_artifacts_relic.txt
  common/artifacts/910_wc_artifacts_leader.txt
  gfx/interface/inventory/artifacts/deathwhisper.dds
  gfx/interface/inventory/artifacts/deathwhisper_small.dds
  gfx/interface/inventory/artifacts/queldelar.dds
  gfx/interface/inventory/artifacts/queldelar_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1421 Ulduar fixes
  events/wc_titanforged_events.txt
Labels: :beetle: bug :beetle:, :exclamation: priority critical

#1422 6th Patrons
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/provinces/270 - Lordamere.txt
  history/provinces/287 - Headlands.txt
  history/titles/c_headlands.txt
  history/titles/c_lordamere.txt
  history/titles/c_skulk_rock.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1385 Localisation crusade 12
  events/wc_fel_events.txt
  localisation/000_Other_title_names.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_offmap.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religions.csv
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:

#1411 Dynasty Shields for Evil Characters
  .artist_resources/coas/scary_runes_pattern.xcf
  gfx/coats_of_arms/scary_runes_pattern.tga
  interface/coat_of_arms/coats_of_arms.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1354 Tweaked Cho'galls journey 2
  common/dynasties/2000_orc.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_religious_triggers.txt
  decisions/wc_dark_cult_decisions.txt
  events/wc_dark_cult_events.txt
  events/wc_offmap_events.txt
  events/wc_on_action_events.txt
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
  history/provinces/2962 - Ishrak.txt
  history/titles/d_twilights_hammer.txt
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :star: new feature :new:

#1423 29th Bug Crusade
  common/artifact_spawns/wc_artifact_spawns.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_substitute_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_test_decisions.txt
  events/indian_pilgrim_events.txt
  events/mnm_devil_worshipers_events.txt
  events/pilgrim_events.txt
  events/roi_feast_events.txt
  events/wc_ai_cleanup_events.txt
  events/wc_frozen_throne_story_events.txt
  events/wc_on_action_events.txt
  events/wol_seduction_events.txt
  history/characters/42000_high_elf.txt
  history/characters/430000_nathrezim.txt
  history/characters/46000_gilnean.txt
  history/titles/b_cold_hearth.txt
  history/titles/c_brill.txt
  history/titles/c_dalaran.txt
  history/titles/c_dalarans_hills.txt
  history/titles/c_dawning_lane.txt
  history/titles/c_dawnstar.txt
  history/titles/c_deathknell.txt
  history/titles/c_duskwither_ravine.txt
  history/titles/c_emberstone.txt
  history/titles/c_fairbreeze.txt
  history/titles/c_falconwing_square.txt
  history/titles/c_falthrien.txt
  history/titles/c_goldenbough_pass.txt
  history/titles/c_magisters_terrace.txt
  history/titles/c_nightmare_vale.txt
  history/titles/c_north_sanctum.txt
  history/titles/c_north_tide.txt
  history/titles/c_quellithien.txt
  history/titles/c_sanctum_of_the_sun.txt
  history/titles/c_silvermoon.txt
  history/titles/c_skittering_dark.txt
  history/titles/c_stillwhisper_pond.txt
  history/titles/c_suns_reach.txt
  history/titles/c_sunsail_anchorage.txt
  history/titles/c_sunstrider_isle.txt
  history/titles/c_sunwell_plateau.txt
  history/titles/c_tranquil_shore.txt
  history/wars/northgate_rebellion.txt
  map/geographical_region.txt
  map/island_region.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1415 New Historical Wonders Pictures
  .artist_resources/wonders/ANQ_LOOT.png
  .artist_resources/wonders/ANQ_NOR.png
  .artist_resources/wonders/SOS_LOOT.png
  .artist_resources/wonders/SOS_NOR.png
  .artist_resources/wonders/ULD_LOOT.png
  .artist_resources/wonders/ULD_NOR.png
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_small.dds
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1443 Fix for AI summoning of King Ymiron
  decisions/wc_realm_decisions.txt
Labels: :exclamation: priority high, :wrench: bug fix :hammer:

#1444 Drak'thul
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  gfx/interface/inventory/artifacts/robe_of_the_warlock.dds
  gfx/interface/inventory/artifacts/robe_of_the_warlock_small.dds
  history/characters/10000_orc.txt
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1388 Generic Artifacts Modifiers
  common/artifacts/904_wc_artifacts_amulets_generic.txt
  common/artifacts/907_wc_artifacts_rings_generic.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium

#1424 17th Small Improvments
  .coder_resources/_unused/decisions/wc_holiday_decisions.txt
  common/cb_types/wc_cb_types.txt
  common/cultures/culture_aqir.txt
  common/cultures/culture_centaur.txt
  common/cultures/culture_gnoll.txt
  common/cultures/culture_harpy.txt
  common/cultures/culture_hozen.txt
  common/cultures/culture_kobold.txt
  common/cultures/culture_murloc.txt
  common/cultures/culture_quilboar.txt
  common/cultures/culture_trogg.txt
  common/cultures/culture_undead.txt
  common/religions/arcane_group.txt
  common/religions/druidism_group.txt
  common/religions/light_group.txt
  common/religions/necromancy_group.txt
  common/religions/secular_group.txt
  common/religions/void_group.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/08_scripted_triggers_LT.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/static_modifiers.txt
  common/traits/wc_race_traits.txt
  decisions/conversion_decisions.txt
  decisions/rip_various_decisions.txt
  decisions/wc_holiday_decisions.txt
  decisions/ze_decisions.txt
  events/HF_bloodline_acquisition_events.txt
  events/LT_court_maintenance_events.txt
  events/guardian_events.txt
  events/wc_race_events.txt
  events/ze_childhood_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1392 Implemented remove_lifestyle_trait_effect in vanilla code
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/06_scripted_effects_legendary_bloodlines.txt
  decisions/employment_decisions.txt
  decisions/hf_warrior_lodge_decisions.txt
  events/HF_coronation_events.txt
  events/HF_saintly_bloodlines_events.txt
  events/female_councillor_events.txt
  events/jd_chinese_diplomacy_events.txt
  events/jd_grace_decision_events.txt
  events/jd_raiding_china.txt
  events/job_offmap.txt
  events/rip_flavor_events.txt
  events/rip_hospital_events.txt
  events/rip_physician_events.txt
  events/soa_jewish_events.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#1390 Changed lvl5 onehanded sword elemental icons
  .artist_resources/artifacts/done/1h_swords.xcf
  gfx/interface/inventory/artifacts/weapons_generic/sword_onehanded_5_cold.dds
  gfx/interface/inventory/artifacts/weapons_generic/sword_onehanded_5_fire.dds
  gfx/interface/inventory/artifacts/weapons_generic/sword_onehanded_5_lightning.dds
  gfx/interface/inventory/artifacts/weapons_generic/sword_onehanded_5_magic.dds
  gfx/interface/inventory/artifacts/weapons_generic/sword_onehanded_5_poison.dds
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1401 Memefixes 5
  .artist_resources/holdings/orcgfx/icons/looted.tga
  common/artifact_spawns/wc_artifact_spawns.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/game_rules/wc_unimportant_game_rules.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/nicknames/wc_nicknames.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  dlc_metadata/dlc_characters/00_dlc_characters.txt
  dlc_metadata/dlc_recommendations/00_dlc_recommendations.txt
  gfx/characters/dwarf_daughter.tga
  gfx/characters/dwarf_son.tga
  gfx/characters/goblin_daughter.tga
  gfx/characters/goblin_son.tga
  gfx/characters/greenskins/orc.dds
  gfx/characters/greenskins/ruin.dds
  gfx/characters/murloc_daughter.tga
  gfx/characters/murloc_son.tga
  gfx/characters/orc_daughter.tga
  gfx/characters/orc_son.tga
  gfx/characters/orcfel_male/orcfel_male_neck_1.dds
  gfx/characters/orcfel_male/orcfel_male_neck_3.dds
  gfx/characters/sartosan_female/sartosan_female_clothes.dds
  gfx/characters/sartosan_female/sartosan_female_clothes_behind.dds
  gfx/characters/sartosan_female/sartosan_female_headgear.dds
  gfx/characters/sartosan_female/sartosan_female_headgear_behind.dds
  gfx/characters/sartosan_female/sartosan_female_headgear_mid.dds
  gfx/characters/strigany_daughter.tga
  gfx/characters/strigany_son.tga
  gfx/characters/unpopulated/unpopulated_plains.dds
  gfx/event_pictures/battle_scene.dds
  gfx/event_pictures/merchant_ship_at_sea_republic.dds
  gfx/interface/holdings/unpopulated/settlement_any_unpopulated.tga
  history/characters/10000_orc.txt
  history/characters/370000_shatyar.txt
  history/characters/42000_high_elf.txt
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#1414 Scripted AI Acceptance Score Values
  common/scripted_score_values/wc_scripted_ai_acceptance_score_values.txt
  decisions/wc_class_decisions.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#1356 Money borrowing
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_economy_modifiers.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_economy_decisions.txt
  events/wc_economy_events.txt
  gfx/event_pictures/chests_with_gold.tga
  gfx/interface/decision_icons/repay_action.tga
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/00_wc_economy.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1435 Gender laws overhaul
  common/governments/feudal_governments.txt
  common/governments/theocracy_governments.txt
  common/laws/succession_laws.txt
  common/religions/druidism_group.txt
  common/scripted_triggers/wc_gender_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/HF_religious_events.txt
  events/on_action_events.txt
  history/characters/340000_night_elf.txt
  history/provinces/3264 - Nordrassil.txt
  history/titles/c_aviana.txt
  history/titles/c_elunar_2.txt
  history/titles/c_janystaea.txt
  history/titles/c_nordlazar.txt
  history/titles/c_nordrassil.txt
  history/titles/c_sildinas.txt
  history/titles/c_sithenn.txt
  history/titles/c_sothann.txt
  history/titles/c_thimil.txt
  history/titles/d_nordrassil.txt
  history/titles/d_thimil.txt
  history/titles/k_hyjal.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:, :wrench: bug fix :hammer:

#1446 Orcish Dynasty Shields
  .artist_resources/coas/orcish_runes_pattern.png
  .artist_resources/coas/orcish_runes_pattern.svg
  common/dynasties/2000_orc.txt
  gfx/coats_of_arms/orcish_runes_pattern.tga
  interface/coat_of_arms/coats_of_arms.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1447 Vrykul Dynasty Shields
  .artist_resources/coas/vrykul_runes_pattern.png
  .artist_resources/coas/vrykul_runes_pattern.svg
  common/dynasties/70000_vrykul.txt
  gfx/coats_of_arms/vrykul_runes_pattern.tga
  interface/coat_of_arms/coats_of_arms.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1460 Artifact Flags
  common/artifacts/901_wc_artifacts_weapon_onehanded_generic_meme.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded_generic_meme.txt
  common/artifacts/904_wc_artifacts_amulets_generic_meme.txt
  common/artifacts/907_wc_artifacts_rings_generic_meme.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:

#1416 Constellar Minors 2
  common/dynasties/20000_high_elf.txt
  history/characters/42000_high_elf.txt
  history/characters/60000_lordaeronian.txt
  history/characters/68000_darkspear.txt
  history/titles/c_saltysand.txt
  history/titles/c_tahonda.txt
  history/titles/c_weazel.txt
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1418 Localisation Crusade 13
  .coder_resources/_unused/localisation/not_used_strings.csv
  common/bookmarks/00_bookmarks.txt
  localisation/000_wc_traits.csv
  localisation/00_wc_economy.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/wc_cultures.csv
  localisation/wc_religions.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1484 30th Bug Crusade
  common/dynasties/20000_high_elf.txt
  common/dynasties/30000_lordaeronian.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_unit_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_dark_cult_events.txt
  events/wc_on_action_events.txt
  history/characters/42000_high_elf.txt
  history/characters/48000_tirassian.txt
  history/characters/60000_lordaeronian.txt
  history/characters/90000_pirate.txt
  history/titles/c_corlain.txt
  history/titles/d_drustwar.txt
  localisation/WikipediaLinks.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1301 Drust Religion
  .artist_resources/races/wicker things/wicker_things.xcf
  common/cultures/culture_undead.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/religions/necromancy_group.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  decisions/wc_undead_decisions.txt
  events/wc_plague_events.txt
  events/wc_race_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  events/wc_zu_test_events.txt
  gfx/characters/wickerbehemoth_male/wickerbehemoth_male_neck.dds
  gfx/characters/wickergolem_male/wickergolem_male_base_1.dds
  gfx/characters/wickerman_male/wickerman_male_neck.dds
  gfx/event_pictures/drustvar.tga
  gfx/flags/d_throssian.tga
  gfx/interface/decision_icons/turn_yourself_into_wicker_golem.dds
  gfx/interface/religion_icon_strip.dds
  gfx/interface/religion_icon_strip_big.dds
  gfx/interface/religion_icon_strip_small.dds
  gfx/interface/unitpanel_unitstrip_small.dds
  gfx/traits/creature_wicker_behemoth.dds
  gfx/traits/creature_wicker_golem.dds
  gfx/traits/creature_wickerman.dds
  history/titles/d_throssian.txt
  interface/portraits/portraits_wickerbehemoth.gfx
  interface/portraits/portraits_wickerbehemoth_sprites.gfx
  interface/portraits/portraits_wickergolem.gfx
  interface/portraits/portraits_wickergolem_sprites.gfx
  interface/portraits/portraits_wickerman.gfx
  interface/portraits/portraits_wickerman_sprites.gfx
  interface/wc_event_pictures.gfx
  interface/wc_traits.gfx
  localisation/000_Other_title_names.csv
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religions.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1497 1st Hotfixes
  common/religions/arcane_group.txt
  common/religions/elemental_lords_group.txt
  common/religions/fel_group.txt
  common/religions/necromancy_group.txt
  common/religions/shamanism_group.txt
  gfx/interface/religion_icon_strip_small.dds
  gfx/interface/unitpanel_unitstrip_small.dds
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1459 Bracers Artifacts
  .artist_resources/artifacts/done/bracers.xcf
  .artist_resources/offmap_OG_minimap_button.xcf
  common/artifacts/903_wc_artifacts_wrist_generic.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_triggers/wc_scripted_artifacts_spawn_triggers.txt
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_1.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_2_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_2_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_2_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_2_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_2_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_3_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_3_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_3_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_3_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_3_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_4_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_4_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_4_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_4_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_4_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_5_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_5_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_5_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_5_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/bracelet_5_stewardship.dds
  interface/wc_treasury_generic.gfx
  localisation/00_memewc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1494 Elven prayers
  common/landed_titles/z_holy_sites.txt
  common/religions/arcane_group.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#1506 Demonic elven portraits
  common/cultures/culture_demonic.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_race_events.txt
  gfx/characters/highelfdemon/highelfdemon_female_base_1.dds
  gfx/characters/highelfdemon/highelfdemon_male_base_1.dds
  gfx/characters/nightelfdemon/nightelfdemon_female_base_1.dds
  gfx/characters/nightelfdemon/nightelfdemon_male_base_1.dds
  interface/portraits/portraits_highelfdemon.gfx
  interface/portraits/portraits_highelfdemon_sprites.gfx
  interface/portraits/portraits_nightelfdemon.gfx
  interface/portraits/portraits_nightelfdemon_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1457 Titan Keeper Portraits
  .artist_resources/portraits/titans/light.txt
  .artist_resources/portraits/titans/position.txt
  gfx/characters/shared/keepers.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_overlay.gfx
  interface/portraits/portraits_titanwatcher.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1510 Improvements Work
  common/religions/primitive_group.txt
  common/religions/secular_group.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/wonders/wc_wonders_historical.txt
  decisions/wc_religion_decisions.txt
  events/wc_titanforged_events.txt
  history/characters/400000_titan.txt
  history/characters/75000_old_dwarven.txt
  history/characters/90000_pirate.txt
  history/provinces/1144 - Eanorah.txt
  history/provinces/858 - Ulduar.txt
  history/provinces/864 - Iahienal.txt
  localisation/wc_cultures.csv
  localisation/wc_religions.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1507 Scarlet Light Holy Sites
  common/landed_titles/z_holy_sites.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium
