Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-08, with the labels that each got.

#1665 Generic Ranged Weapons
  .artist_resources/artifacts/bows.xcf
  .artist_resources/artifacts/crossbows.xcf
  .artist_resources/artifacts/done/bows.xcf
  .artist_resources/artifacts/done/crossbows.xcf
  .artist_resources/artifacts/done/rifles.xcf
  .artist_resources/artifacts/rifles.xcf
  .gitignore
  common/artifacts/901_wc_artifacts_weapon_ranged_generic_meme.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_triggers/wc_artifact_spawning_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_artifacts_spawn_triggers.txt
  common/scripted_triggers/wc_scripted_artifacts_triggers.txt
  gfx/interface/inventory/artifacts/weapons_generic/bow_1.dds
  gfx/interface/inventory/artifacts/weapons_generic/bow_2.dds
  gfx/interface/inventory/artifacts/weapons_generic/bow_3.dds
  gfx/interface/inventory/artifacts/weapons_generic/bow_4.dds
  gfx/interface/inventory/artifacts/weapons_generic/bow_5.dds
  gfx/interface/inventory/artifacts/weapons_generic/crossbow_1.dds
  gfx/interface/inventory/artifacts/weapons_generic/crossbow_2.dds
  gfx/interface/inventory/artifacts/weapons_generic/crossbow_3.dds
  gfx/interface/inventory/artifacts/weapons_generic/crossbow_4.dds
  gfx/interface/inventory/artifacts/weapons_generic/crossbow_5.dds
  gfx/interface/inventory/artifacts/weapons_generic/rifle_1.dds
  gfx/interface/inventory/artifacts/weapons_generic/rifle_2.dds
  gfx/interface/inventory/artifacts/weapons_generic/rifle_3.dds
  gfx/interface/inventory/artifacts/weapons_generic/rifle_4.dds
  gfx/interface/inventory/artifacts/weapons_generic/rifle_5.dds
  interface/wc_treasury_generic.gfx
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1519 Janeiro Point Wonder 🏛
  common/wonder_upgrades/wc_wonders_buildable_upgrades.txt
  common/wonder_upgrades/wc_wonders_historical_upgrades.txt
  common/wonders/wc_wonders_historical.txt
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_janeiro_point_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_janeiro_point_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_janeiro_point_small.dds
  history/provinces/91 - Wild Cape.txt
  interface/wc_wonder.gfx
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low, :star: new feature :new:

#1753 Memefixes 8
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded_generic_meme.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_trade_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  decisions/wc_economy_decisions.txt
  events/wc_crisis_events.txt
  events/wc_frozen_throne_story_events.txt
  events/wc_on_action_events.txt
  events/wc_third_war_events.txt
  history/characters/60000_63000_lordaeronian.txt
  history/titles/c_talgurub.txt
  history/titles/c_zanchul.txt
  localisation/00_zuwc_united_localisation.csv
  music/goa_main_music.txt
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#1762 Pandaria Hunting
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_region_triggers.txt
  events/hunting_events.txt
  events/wol_hunting_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :wrench: bug fix :hammer:

#1750 1st Pandaria Bugfixes
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  events/wc_pandaria_events.txt
  history/characters/540000_mantid.txt
  localisation/wc_religions.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1761 Pandaria Mercenaries
  common/cultures/culture_hozen.txt
  common/landed_titles/wc_mercenary_landed_titles.txt
  common/mercenaries/wc_mercenaries.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  gfx/flags/d_forest_hozen_band.tga
  gfx/flags/d_jinyu_company.tga
  gfx/flags/d_jungle_hozen_band.tga
  gfx/flags/d_jungle_hozen_fleet.tga
  gfx/flags/d_mainland_pandaren_company_1.tga
  gfx/flags/d_mainland_pandaren_company_2.tga
  gfx/flags/d_mainland_pandaren_fleet.tga
  gfx/flags/d_mogu_company.tga
  gfx/flags/d_mountain_hozen_band.tga
  gfx/flags/d_saurok_band.tga
  gfx/flags/d_saurok_fleet.tga
  gfx/flags/d_yaungol_band.tga
  localisation/000_Other_title_names.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1709 Heart of Y'Shaarj
  common/artifacts/908_wc_artifacts_relic.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/wc_sha_events.txt
  gfx/interface/inventory/artifacts/heart_of_yshaarj.dds
  gfx/interface/inventory/artifacts/heart_of_yshaarj_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1764 2nd Pandaria Bugfixes
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1765 Lightbound Icon Fix
  common/religions/light_group.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1763 Lei Shen
  .artist_resources/traits/thunder_king_trait.xcf
  common/bloodlines/wc_bloodlines.txt
  common/bloodlines/wc_earned_bloodlines.txt
  common/dynasties/172000_mogu.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/nicknames/wc_nicknames.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_trait_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/traits/wc_demigod_traits.txt
  decisions/wc_crisis_decisions.txt
  events/wc_crisis_events.txt
  events/wc_pandaria_events.txt
  gfx/characters/shared/mogu_static_portraits.dds
  gfx/event_pictures/thunder_king.tga
  gfx/event_pictures/zandalar_and_pandaren_fight.tga
  gfx/interface/decision_icons/resurrect_lei_shen.dds
  gfx/traits/thunder_king_trait.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_mogu.gfx
  interface/portraits/portraits_overlay.gfx
  interface/wc_alternative_event_pictures.gfx
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1751 Plural forms in artifact origins localization
  common/artifacts/903_wc_artifacts_wrist_generic.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_triggers/wc_artifact_spawning_scripted_triggers.txt
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1769 Pandaria Buildings
  common/buildings/wc_castle_culture.txt
  common/retinue_subunits/00_retinue_subunits.txt
  localisation/000_wc_military_localization.csv
  localisation/wc_culture_buildings.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1723 Mantid paragons
  common/bloodlines/wc_earned_bloodlines.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/nicknames/wc_nicknames.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/wc_race_decisions.txt
  events/wc_race_events.txt
  gfx/event_pictures/mantid_poisoner.tga
  gfx/event_pictures/mantivess_hall.tga
  gfx/event_pictures/mogu_and_mantid_battle.tga
  gfx/traits/mantid_paragon.dds
  history/characters/540000_mantid.txt
  interface/wc_alternative_event_pictures.gfx
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :star: new feature :new:

#1732 Monk Сlass
  common/event_modifiers/wc_event_modifiers.txt
  common/modifier_definitions/wc_class_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_vanilla_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  common/traits/wc_class_traits.txt
  decisions/mnm_hermetics_decisions.txt
  decisions/wc_class_decisions.txt
  events/mnm_hermetics_events.txt
  events/wc_class_events.txt
  events/wc_dark_cult_events.txt
  gfx/interface/decision_icons/teach_yourself_monk.dds
  gfx/traits/class/class_monk_1.dds
  gfx/traits/class/class_monk_10.dds
  gfx/traits/class/class_monk_2.dds
  gfx/traits/class/class_monk_3.dds
  gfx/traits/class/class_monk_4.dds
  gfx/traits/class/class_monk_5.dds
  gfx/traits/class/class_monk_6.dds
  gfx/traits/class/class_monk_7.dds
  gfx/traits/class/class_monk_8.dds
  gfx/traits/class/class_monk_9.dds
  interface/wc_decision_icons.gfx
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1775 8th Patrons
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/titles/c_andilien_estate.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#1776 Pandaria Monks
  common/scripted_triggers/wc_class_scripted_triggers.txt
  events/wc_startup_events.txt
  history/characters/500000_pandaren.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1774 34th Bug Crusade
  common/bloodlines/wc_bloodlines.txt
  common/nicknames/00_nicknames.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  events/wc_class_events.txt
  events/wc_crisis_events.txt
  events/wc_dark_cult_events.txt
  history/provinces/256 - Hiriwatha.txt
  history/provinces/258 - Shadraalor.txt
  history/provinces/261 - Altar of Zul.txt
  history/provinces/262 - Agolwatha.txt
  history/provinces/263 - Skulk Rock.txt
  history/provinces/264 - Shaolwatha.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1773 22nd Small Improvments
  common/bloodlines/wc_earned_bloodlines.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/traits/wc_class_traits.txt
  decisions/wc_form_x_title_decisions.txt
  events/wc_crisis_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#845 Old Gods Content
  common/bloodlines/wc_earned_bloodlines.txt
  common/buildings/wc_uniques.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/game_rules/000_wc_game_rules.txt
  common/nicknames/wc_nicknames.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_unit_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_offmap_scripted_triggers.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/wonder_upgrades/wc_wonders_historical_upgrades.txt
  common/wonders/wc_wonders_historical.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_wonder_decisions.txt
  events/wc_first_war_events.txt
  events/wc_offmap_events.txt
  events/wc_on_action_events.txt
  events/wc_third_war_events.txt
  events/wc_void_events.txt
  gfx/interface/decision_icons/recruit_old_god_guard.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_old_god_cthun.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_old_god_nzoth.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_old_god_yogg_saron.dds
  history/titles/c_dark_portal.txt
  interface/wc_decision_icons.gfx
  interface/wc_wonder.gfx
  localisation/00_wc_offmap.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :star: new feature :new:

#1740 Chogall final step
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_dark_cult_events.txt
  events/wc_offmap_events.txt
  history/characters/52000_ogre.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :construction: WIP :construction:, :star: new feature :new:

#1780 Fixed yaungol hair and eye indexes
  interface/portraits/portraits_yaungol.gfx
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1781 is_playable => only_playable fix
  decisions/wc_class_decisions.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1779 Pandaren portraits
  gfx/characters/pandaren_female/pandaren_female_base_1.dds
  gfx/characters/pandaren_female/pandaren_female_clothes.dds
  gfx/characters/pandaren_female/pandaren_female_hair_1.dds
  gfx/characters/pandaren_female/pandaren_female_headgear.dds
  gfx/characters/pandaren_female/pandaren_female_neck_1.dds
  gfx/characters/pandaren_male/pandaren_male_base_1.dds
  gfx/characters/pandaren_male/pandaren_male_beard_1.dds
  gfx/characters/pandaren_male/pandaren_male_brows.dds
  gfx/characters/pandaren_male/pandaren_male_clothes.dds
  gfx/characters/pandaren_male/pandaren_male_hair_1.dds
  gfx/characters/pandaren_male/pandaren_male_headgear.dds
  gfx/characters/pandaren_male/pandaren_male_neck_1.dds
  interface/portraits/portraits_pandaren.gfx
  interface/portraits/portraits_pandaren_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1784 One-eyed Lor'themar
  history/characters/42000_high_elf.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#1749 Pandaria Trade Routes
  common/holding_types/00_holding_types.txt
  common/scripted_triggers/wc_trade_triggers.txt
  common/trade_routes/00_wc_pandaria.txt
  localisation/00_ciwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1700 Ranger general, story fix, historical ranger-generals for game.
  history/characters/42000_high_elf.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1345 Forge Hammer of Twilight decision
  common/artifact_spawns/wc_artifact_spawns.txt
  common/societies/wc_societies.txt
  decisions/wc_society_decisions.txt
  events/wc_dark_cult_events.txt
  gfx/interface/decision_icons/forge_hammer_of_the_twilight.dds
  interface/wc_decision_icons.gfx
  localisation/00_wc_sad.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1772 Mogu Portraits
  gfx/characters/mogu_male/mogu_male_base_1.dds
  gfx/characters/mogu_male/mogu_male_beard_1.dds
  gfx/characters/mogu_male/mogu_male_brows.dds
  gfx/characters/mogu_male/mogu_male_clothes.dds
  gfx/characters/mogu_male/mogu_male_hair.dds
  gfx/characters/mogu_male/mogu_male_headgear.dds
  gfx/characters/mogu_male/mogu_male_neck_1.dds
  interface/portraits/portraits_mogu.gfx
  interface/portraits/portraits_mogu_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1786 Colored Mantid Females
  .artist_resources/portraits/mantid_female/recoloring.xcf
  gfx/characters/mantid_female/mantid_female_base_1.dds
  gfx/characters/mantid_female/mantid_female_iris.dds
  gfx/characters/mantid_female/mantid_female_neck.dds
  history/characters/540000_mantid.txt
  interface/portraits/portraits_mantid.gfx
  interface/portraits/portraits_mantid_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1787 Mantid are Void Beings
  events/wc_race_events.txt
  history/characters/540000_mantid.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#1728 Artifacts as Reward for Society Quests
  common/game_rules/000_wc_game_rules.txt
  common/game_rules/000_wc_game_rules_artifacts.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/01_scripted_effects_duels.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_scripted_generic_artifact_spawn_values.txt
  common/scripted_triggers/wc_scripted_artifacts_spawn_triggers.txt
  common/scripted_triggers/wc_scripted_artifacts_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  events/HF_bloodline_events.txt
  events/HF_warrior_lodge_mission_events.txt
  events/hf_warrior_lodge_events.txt
  events/mnm_artifacts_events.txt
  events/mnm_assassins_events.txt
  events/mnm_devil_worshipers_events.txt
  events/mnm_hermetics_events.txt
  events/mnm_monastic_orders_events.txt
  events/mnm_secret_religious_societies_events.txt
  events/wc_artifact_spawn_gamestart.txt
  events/wc_artifacts_generic_random_spawn.txt
  events/wc_class_events.txt
  events/wc_emerald_dream_events.txt
  events/wc_quest_events.txt
  events/wc_zu_test_events.txt
  localisation/00_memewc_united_localisation.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1777 Replacement of TOG Looting Events
  common/game_rules/000_wc_game_rules_artifacts.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_score_values/wc_scripted_generic_artifact_spawn_values.txt
  events/oldgods_various_events.txt
  events/wc_artifacts_generic_random_spawn.txt
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
Labels: :grey_exclamation: priority low, :ice_cream: vanilla modification :icecream:, :star: new feature :new:

#1778 Artifacts/Class Game Rules
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/game_rules/000_wc_game_rules.txt
  common/game_rules/000_wc_game_rules_artifacts.txt
  common/scripted_triggers/wc_scripted_artifacts_triggers.txt
  localisation/00_memewc_united_localisation.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:, :wrench: bug fix :hammer:

#1788 More Yaungol Female Skin Colors
  interface/portraits/portraits_yaungol.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1771 Pandaria fashion show
  .artist_resources/portraits/mantid_male/light.txt
  .artist_resources/portraits/mantid_male/position.txt
  gfx/characters/hozen_female/hozen_female_neck_1.dds
  gfx/characters/hozen_male/hozen_male_clothes.dds
  gfx/characters/hozen_male/hozen_male_headgear.dds
  gfx/characters/hozen_male/hozen_male_neck_1.dds
  gfx/characters/mantid_male/mantid_male_clothes.dds
  gfx/characters/mantid_male/mantid_male_clothes_behind.dds
  gfx/characters/mantid_male/mantid_male_headgear.dds
  gfx/characters/mantid_male/mantid_male_neck_1.dds
  gfx/characters/yaungol_male/yaungol_male_beard_ties_front.dds
  gfx/characters/yaungol_male/yaungol_male_clothes.dds
  gfx/characters/yaungol_male/yaungol_male_clothes_front.dds
  gfx/characters/yaungol_male/yaungol_male_fur.dds
  gfx/characters/yaungol_male/yaungol_male_horns_1.dds
  gfx/characters/yaungol_male/yaungol_male_neck_1.dds
  interface/portraits/portraits_hozen.gfx
  interface/portraits/portraits_hozen_sprites.gfx
  interface/portraits/portraits_mantid.gfx
  interface/portraits/portraits_mantid_sprites.gfx
  interface/portraits/portraits_yaungol.gfx
  interface/portraits/portraits_yaungol_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1528 Historical Norse Names for Vrykul
  common/cultures/culture_vrykul.txt
  history/characters/100000_vrykul.txt
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1782 Lor'themar portraits and static portraits triggers
  gfx/characters/shared/belf.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_overlay.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1783 Techs Tweaks
  history/technology/e_arathor_empire.txt
  history/technology/e_kul_tiras.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority low

#1790 Shado-Pan Assimilation Issue
  common/landed_titles/wc_religious_landed_titles.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1791 Bluish Pandaria Issue
  gfx/characters/grummle_child/grummle_child_female.dds
  gfx/characters/grummle_child/grummle_child_male.dds
  gfx/characters/jinyu_child/jinyu_female_child.dds
  gfx/characters/jinyu_child/jinyu_male_child.dds
  gfx/characters/jinyu_female/jinyu_female_base_1.dds
  gfx/characters/jinyu_female/jinyu_female_clothes.dds
  gfx/characters/jinyu_female/jinyu_female_neck_1.dds
  gfx/characters/jinyu_male/jinyu_male_base_1.dds
  gfx/characters/jinyu_male/jinyu_male_clothes.dds
  gfx/characters/jinyu_male/jinyu_male_neck_1.dds
  gfx/characters/mantid_child/mantid_child_female.dds
  gfx/characters/mantid_child/mantid_child_male.dds
  gfx/characters/mogu_child/mogu_female_child.dds
  gfx/characters/mogu_child/mogu_male_child.dds
  gfx/characters/mogu_female/mogu_female_neck_1.dds
  gfx/characters/saurok_child/saurok_child_female.dds
  gfx/characters/saurok_child/saurok_child_male.dds
  gfx/characters/saurok_female/saurok_female_neck_1.dds
  gfx/characters/saurok_male/saurok_male_neck_1.dds
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1792 Dwarven Flags
  gfx/flags/c_ironforge.tga
  gfx/flags/d_blackrock_mountain.tga
  gfx/flags/d_central_dun_morogh.tga
  gfx/flags/k_blackrock.tga
  gfx/flags/k_ironforge.tga
  gfx/flags/k_wildhammer.tga
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1793 Elven flags
  gfx/flags/c_darnassus.tga
  gfx/flags/c_silvermoon.tga
  gfx/flags/c_tranquillien.tga
  gfx/flags/c_windrunner.tga
  gfx/flags/d_blood_knights_order.tga
  gfx/flags/d_kalidar.tga
  gfx/flags/d_silvermoon.tga
  gfx/flags/d_sindorei.tga
  gfx/flags/d_tranquillien.tga
  gfx/flags/e_kaldorei.tga
  gfx/flags/e_quelthalas.tga
  gfx/flags/k_cenarion_circle.tga
  gfx/flags/k_quelthalas.tga
  gfx/flags/k_tranquillien.tga
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1795 Human Flags
  gfx/flags/c_corins_crossing.tga
  gfx/flags/c_gilneas.tga
  gfx/flags/c_karazhan.tga
  gfx/flags/c_lordaeron.tga
  gfx/flags/c_wintergarde.tga
  gfx/flags/d_argent_dawn.tga
  gfx/flags/d_church_of_the_holy_light.tga
  gfx/flags/d_church_scarlet_light.tga
  gfx/flags/d_gilneas.tga
  gfx/flags/d_karazhan.tga
  gfx/flags/d_lordaeron.tga
  gfx/flags/d_lordamere.tga
  gfx/flags/d_scarlet_crusade.tga
  gfx/flags/d_wintergarde.tga
  gfx/flags/e_lordaeron.tga
  gfx/flags/k_lordaeron.tga
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1559 German Generic Artifacts Localization
  localisation/00_DEwc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customisable_localisation_DE.txt
Labels: :page_facing_up: localisation - german :pen:, :page_facing_up: localisation :pen:

#1796 Pandaria Flags
  common/religions/00_religions.txt
  common/religions/druidism_group.txt
  common/religions/elemental_lords_group.txt
  common/religions/fel_group.txt
  common/religions/nerubian_religion_group.txt
  common/religions/pandaren_religion_group.txt
  common/religions/primitive_group.txt
  common/religions/secular_group.txt
  common/religions/shamanism_group.txt
  common/religions/void_group.txt
  common/religions/vrykul_religion_group.txt
  gfx/flags/_other/c_amous.tga
  gfx/flags/_other/c_anti-atlas.tga
  gfx/flags/_other/c_antiocheia.tga
  gfx/flags/_other/c_anxi.tga
  gfx/flags/_other/c_aoudaghost.tga
  gfx/flags/c_dawnblossom.tga
  gfx/flags/c_fallingblossom.tga
  gfx/flags/c_halfhill.tga
  gfx/flags/c_jadeheart.tga
  gfx/flags/c_krasarang.tga
  gfx/flags/c_mantivess.tga
  gfx/flags/c_mogushan.tga
  gfx/flags/c_shadybranch.tga
  gfx/flags/c_silkwood.tga
  gfx/flags/c_windspire.tga
  gfx/flags/c_xuen.tga
  gfx/flags/c_yulon.tga
  gfx/flags/c_zouchin.tga
  gfx/flags/d_black_ox.tga
  gfx/flags/d_golden_lotus.tga
  gfx/flags/d_halfhill.tga
  gfx/flags/d_jade_serpent.tga
  gfx/flags/d_mantivess.tga
  gfx/flags/d_mogushan.tga
  gfx/flags/d_red_crane.tga
  gfx/flags/d_shado_pan.tga
  gfx/flags/d_silkwood.tga
  gfx/flags/d_white_tiger.tga
  gfx/flags/d_xuen.tga
  gfx/flags/d_yulon.tga
  gfx/flags/d_zouchin.tga
  gfx/flags/e_banshan.tga
  gfx/flags/e_kun_lai.tga
  gfx/flags/e_pandaria_empire.tga
  gfx/flags/e_shekmag.tga
  gfx/flags/e_yulin.tga
  gfx/flags/k_halfhill.tga
  gfx/flags/k_krasarang.tga
  gfx/flags/k_kun_lai.tga
  gfx/flags/k_kyparqov.tga
  gfx/flags/k_lei_dao.tga
  gfx/flags/k_mogushan.tga
  gfx/flags/k_shado_pan.tga
  gfx/flags/k_sheilun.tga
  gfx/flags/k_townlong.tga
  gfx/flags/k_yulin.tga
  gfx/flags/k_zouchin.tga
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1797 AI building Old Gods Issue
  common/wonder_upgrades/wc_wonders_historical_upgrades.txt
  events/wc_offmap_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1798 Panda and Old Gods' Balance Tweaks
  common/scripted_score_values/wc_scripted_score_values.txt
  events/wc_dark_cult_events.txt
  events/wc_sha_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#1738 Localisation Crusade 19
  events/wc_crisis_events.txt
  localisation/00_DEwc_united_localisation.csv
  localisation/00_ciwc_united_localisation.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_government.csv
  localisation/00_wc_offmap.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_sacrifice_events.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/customizable_localisation/wc_customisable_localisation_DE.txt
  localisation/wc_cultures.csv
  localisation/wc_religions.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1799 Fixed parser.cpp:688
  events/wol_scholarship_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:
