Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-11, with the labels that each got.

#1825 9th Patrons
  history/characters/310000_patron_characters.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#1828 Thunder Isle Climate
  common/landed_titles/01_landed_titles.txt
  history/provinces/91 - Wild Cape.txt
  map/climate.txt
  map/provinceDef.xls
Labels: :wrench: bug fix :hammer:

#1695 Pandaria Post-Release - Wandering Isle / Ankoan
  common/on_actions/00_on_actions.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_form_x_title_decisions.txt
  events/wc_crisis_events.txt
  events/wc_pandaria_events.txt
  gfx/characters/ankoan_male/ankoan_male_base_1.dds
  gfx/characters/ankoan_male/ankoan_male_neck_1.dds
  gfx/event_pictures/wandering_isle.tga
  interface/portraits/portraits_ankoan.gfx
  interface/portraits/portraits_ankoan_sprites.gfx
  interface/wc_event_pictures.gfx
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1834 CB GUI Tooltip
  common/cb_types/00_cb_types.txt
  common/cb_types/01_cb_types.txt
  common/cb_types/02_cb_types_shattered_world.txt
  common/cb_types/wc_cb_types.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#1830 Serathil for Kash'drakor
  common/artifact_spawns/wc_artifact_spawns.txt
Labels: :wrench: bug fix :hammer:
