Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-05, with the labels that each got.

#1493 Localisation Crusade 14
  events/wol_war_events.txt
  localisation/000_Other_title_names.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1516 Allowing Scarlet Light characters to wear the tabard of the Silver Hand
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
Labels: :grey_exclamation: priority medium, :question: suggestion :question:

#1521 31th Bug Crusade
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_gender_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1520 Human female facial features cleanup
  gfx/characters/human_female/humanblack_female_1_eyes.dds
  gfx/characters/human_female/humanblack_female_1_mouth.dds
  gfx/characters/human_female/humanblack_female_1_nose.dds
  gfx/characters/human_female/humanblack_female_2_eyes.dds
  gfx/characters/human_female/humanblack_female_2_mouth.dds
  gfx/characters/human_female/humanblack_female_2_nose.dds
  gfx/characters/human_female/humanblack_female_3_eyes.dds
  gfx/characters/human_female/humanblack_female_3_mouth.dds
  gfx/characters/human_female/humanblack_female_3_nose.dds
  gfx/characters/human_female/humantan_female_1_eyes.dds
  gfx/characters/human_female/humantan_female_1_mouth.dds
  gfx/characters/human_female/humantan_female_1_nose.dds
  gfx/characters/human_female/humantan_female_2_eyes.dds
  gfx/characters/human_female/humantan_female_2_mouth.dds
  gfx/characters/human_female/humantan_female_2_nose.dds
  gfx/characters/human_female/humantan_female_3_eyes.dds
  gfx/characters/human_female/humantan_female_3_mouth.dds
  gfx/characters/human_female/humantan_female_3_nose.dds
  gfx/characters/human_female/humanundead_female_eyes.dds
  gfx/characters/human_female/humanundead_female_glow.dds
  gfx/characters/human_female/humanundead_female_iris.dds
  gfx/characters/human_female/humanundead_female_mouth.dds
  gfx/characters/human_female/humanundead_female_nose.dds
  gfx/characters/human_female/humanwhite_female_1_eyes.dds
  gfx/characters/human_female/humanwhite_female_1_mouth.dds
  gfx/characters/human_female/humanwhite_female_1_nose.dds
  gfx/characters/human_female/humanwhite_female_2_eyes.dds
  gfx/characters/human_female/humanwhite_female_2_mouth.dds
  gfx/characters/human_female/humanwhite_female_2_nose.dds
  gfx/characters/human_female/humanwhite_female_3_eyes.dds
  gfx/characters/human_female/humanwhite_female_3_mouth.dds
  gfx/characters/human_female/humanwhite_female_3_nose.dds
  gfx/characters/human_female/humanwhite_female_eyes2.dds
  interface/portraits/portraits_human_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1526 Pandaria renames
  .coder_resources/Pandaria.xlsx
  localisation/00_Province_names.csv
  map/definition.csv
  map/provinceDef.xls
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1496 Localisation crusade 15
  events/wc_fel_events.txt
  localisation/00_wc_job_titles.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localisation :pen:

#1531 Female Elf Portraits
  .artist_resources/portraits/highelf_female/Martial suits Female.xcf
  .artist_resources/portraits/highelf_female/Position.txt
  .artist_resources/portraits/highelf_female/light.txt
  gfx/characters/highelf_female/highelf_female_base_1.dds
  gfx/characters/highelf_female/highelf_female_cheeks_1.dds
  gfx/characters/highelf_female/highelf_female_clothes.dds
  gfx/characters/highelf_female/highelf_female_clothes_behind.dds
  gfx/characters/highelf_female/highelf_female_clothes_infront.dds
  gfx/characters/highelf_female/highelf_female_glow.dds
  gfx/characters/highelf_female/highelf_female_hair_1.dds
  gfx/characters/highelf_female/highelf_female_hair_behind_1.dds
  gfx/characters/highelf_female/highelf_female_headgear.dds
  gfx/characters/highelf_female/highelf_female_headgear_behind.dds
  gfx/characters/highelf_female/highelf_female_headgear_mid.dds
  gfx/characters/highelf_female/highelf_female_iris.dds
  gfx/characters/highelf_male/highelf_male_clothes.dds
  gfx/characters/highelf_male/highelf_male_hair_1.dds
  gfx/characters/highelf_male/highelf_male_headgear.dds
  interface/portraits/portraits_highelf.gfx
  interface/portraits/portraits_highelf_sprites.gfx
  interface/portraits/portraits_human.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1538 Small corrupted elf portraits
  common/cultures/culture_demonic.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_fel_events.txt
  interface/portraits/portraits_highelf.gfx
  interface/portraits/portraits_highelf_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1547 Undead high elf
  common/cultures/culture_undead.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  gfx/characters/highelf_female/highelfundead_female_base.dds
  gfx/characters/highelf_male/highelfundead_male_base.dds
  gfx/characters/highelf_male/highelfundead_male_glow.dds
  gfx/characters/highelf_male/highelfundead_male_iris.dds
  history/characters/42000_high_elf.txt
  interface/portraits/portraits_highelf.gfx
  interface/portraits/portraits_highelf_sprites.gfx
  interface/portraits/portraits_human.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority critical

#1553 Undead elf portrait hotfix
  gfx/characters/highelf_female/highelfundead_female_base.dds
  gfx/characters/highelf_male/highelfundead_male_iris.dds
Labels: :art: graphics :paintbrush:, :exclamation: priority critical, :wrench: bug fix :hammer:

#1287 Drust Crisis
  common/bloodlines/wc_bloodlines.txt
  common/cultures/culture_vrykul.txt
  common/dynasties/70000_vrykul.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/wc_crisis_decisions.txt
  events/wc_crisis_events.txt
  events/wc_vrykul_events.txt
  gfx/characters/shared/vrykuls.dds
  gfx/event_pictures/boralus_siege.tga
  gfx/flags/d_order_of_embers.tga
  gfx/flags/d_thornspeakers.tga
  gfx/flags/d_throsic.tga
  gfx/flags/k_drustvar.tga
  gfx/interface/decision_icons/summon_gorak_tul.dds
  history/characters/460000_drust.txt
  history/characters/48000_tirassian.txt
  history/titles/d_order_of_embers.txt
  history/titles/d_thornspeakers.txt
  history/titles/d_throsic.txt
  history/titles/k_drustvar.txt
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_overlay.gfx
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/wc_cultures.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1511 Light's Vengeance
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  gfx/interface/inventory/artifacts/lights_vengeance.dds
  gfx/interface/inventory/artifacts/lights_vengeance_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1554 Improvements work 2
  common/artifact_spawns/wc_artifact_spawns.txt
  common/bloodlines/wc_bloodlines.txt
  common/buildings/wc_castle_culture.txt
  common/buildings/wc_tradepost_culture.txt
  common/cb_types/00_cb_types.txt
  common/cultures/culture_elf.txt
  common/cultures/culture_high_elf.txt
  common/cultures/culture_naga.txt
  common/cultures/culture_night_elf.txt
  common/cultures/culture_satyr.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/landed_titles/wc_religious_landed_titles.txt
  common/mercenaries/wc_mercenaries.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/nicknames/wc_nicknames.txt
  common/religions/arcane_group.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_trade_triggers.txt
  common/traits/wc_race_traits.txt
  decisions/wc_order_decisions.txt
  decisions/wc_realm_decisions.txt
  events/wc_frozen_throne_story_events.txt
  events/wc_order_events.txt
  events/wc_undead_events.txt
  events/wc_war_events.txt
  gfx/flags/d_blood_knights_order.tga
  gfx/interface/decision_icons/create_blood_knights_order.dds
  history/titles/d_blood_knights_order.txt
  interface/wc_decision_icons.gfx
  interface/wc_holdings.gfx
  localisation/000_Other_title_names.csv
  localisation/00_wc_job_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_cultures.csv
  music/goa_main_music.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1571 Drust hotfix
  events/wc_crisis_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1573 Ursine temple hotfix
  interface/wc_holdings.gfx
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1177 Old god healing
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/01_scripted_effects_duels.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_trait_scripted_effects.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/mnm_society_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_offmap_decisions.txt
  events/HF_religious_events.txt
  events/cm_various_events.txt
  events/furusiyya_events.txt
  events/hf_warrior_lodge_events.txt
  events/jd_chinese_diplomacy_events.txt
  events/jd_grace_decision_events.txt
  events/mnm_devil_worshipers_events.txt
  events/oldgods_ancestor_worship_events.txt
  events/rip_eternal_life_events.txt
  events/rip_maimed_events.txt
  events/rip_physician_events.txt
  events/rip_torture_events.txt
  events/rip_treatment_events.txt
  events/wc_class_events.txt
  events/wc_offmap_events.txt
  events/wc_traditions_events.txt
  events/wc_void_events.txt
  gfx/event_pictures/old_god_healing.tga
  interface/wc_event_pictures.gfx
  localisation/00_wc_offmap.csv
  localisation/00_wc_sad.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1504 18th Small Improvments
  .artist_resources/races/creature_watcher/creature_watcher.xcf
  common/bloodlines/wc_earned_bloodlines.txt
  common/cb_types/00_cb_types.txt
  common/cultures/culture_human.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_realm_decisions.txt
  decisions/wc_undead_decisions.txt
  events/plot_events.txt
  events/wc_fel_events.txt
  events/wc_undead_events.txt
  gfx/traits/creature_watcher.dds
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#1570 Hive government
  .artist_resources/governments/charframe_150_hive.xcf
  .artist_resources/governments/icon_hive_government.xcf
  .artist_resources/portraits/qiraji_male/qiraji_child.xcf
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/government_flavor/wc_government_flavor.txt
  common/governments/feudal_governments.txt
  common/governments/nomadic_governments.txt
  common/governments/republic_governments.txt
  common/governments/theocracy_governments.txt
  common/governments/tribal_governments.txt
  common/landed_titles/wc_titular_titles.txt
  common/laws/succession_laws.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  decisions/wc_dark_cult_decisions.txt
  decisions/wc_realm_decisions.txt
  events/wc_government_events.txt
  gfx/characters/qiraji_child/qiraji_child_female.dds
  gfx/characters/qiraji_child/qiraji_child_male.dds
  gfx/event_pictures/silithus.tga
  gfx/interface/decision_icons/song_of_swarm.dds
  gfx/interface/governments/charframe_100_hive.dds
  gfx/interface/governments/charframe_150_hive.dds
  gfx/interface/governments/charframe_34_hive.dds
  gfx/interface/governments/charframe_50_hive.dds
  gfx/interface/governments/charframe_75_hive.dds
  gfx/interface/governments/icon_hive_government.dds
  history/titles/c_ahnqiraj.txt
  history/titles/c_kagram.txt
  history/titles/c_skerezziz.txt
  history/titles/c_tugrann.txt
  history/titles/e_ahnqiraj.txt
  history/titles/k_ahnqiraj.txt
  interface/coat_of_arms/coats_of_arms.txt
  interface/portraits/portraits_qiraji_sprites.gfx
  interface/portraits/portraits_qirajiemperor_sprites.gfx
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  interface/wc_governments.gfx
  localisation/00_wc_government.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1537 Localisation Crusade 16
  common/landed_titles/wc_titular_titles.txt
  localisation/000_Other_title_names.csv
  localisation/000_wc_traits.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_religions.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localisation :pen:

#1381 Pandaria - Jinyu Portraits
  gfx/characters/jinyu_child/jinyu_female_child.dds
  gfx/characters/jinyu_child/jinyu_male_child.dds
  gfx/characters/jinyu_female/jinyu_female_base_1.dds
  gfx/characters/jinyu_female/jinyu_female_clothes.dds
  gfx/characters/jinyu_female/jinyu_female_neck_1.dds
  gfx/characters/jinyu_male/jinyu_male_base_1.dds
  gfx/characters/jinyu_male/jinyu_male_clothes.dds
  gfx/characters/jinyu_male/jinyu_male_neck_1.dds
  interface/portraits/portraits_jinyu.gfx
  interface/portraits/portraits_jinyu_sprites.gfx
  localisation/wc_cultures.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :star: new feature :new:

#1569 Night elf portraits
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/traits/wc_tattoos_traits.txt
  events/wc_race_events.txt
  events/wc_startup_events.txt
  gfx/characters/nightelf_female/nightelf_female_base_1.dds
  gfx/characters/nightelf_female/nightelf_female_brows.dds
  gfx/characters/nightelf_female/nightelf_female_clothes.dds
  gfx/characters/nightelf_female/nightelf_female_clothes_behind.dds
  gfx/characters/nightelf_female/nightelf_female_eyes_1.dds
  gfx/characters/nightelf_female/nightelf_female_glow.dds
  gfx/characters/nightelf_female/nightelf_female_hair_1.dds
  gfx/characters/nightelf_female/nightelf_female_hair_behind_1.dds
  gfx/characters/nightelf_female/nightelf_female_headgear.dds
  gfx/characters/nightelf_female/nightelf_female_headgear_behind.dds
  gfx/characters/nightelf_female/nightelf_female_headgear_mid.dds
  gfx/characters/nightelf_female/nightelf_female_makeup.dds
  gfx/characters/nightelf_male/nightelf_male_base_1.dds
  gfx/characters/nightelf_male/nightelf_male_beard_1.dds
  gfx/characters/nightelf_male/nightelf_male_beard_behind_1.dds
  gfx/characters/nightelf_male/nightelf_male_brows.dds
  gfx/characters/nightelf_male/nightelf_male_clothes.dds
  gfx/characters/nightelf_male/nightelf_male_clothes_behind.dds
  gfx/characters/nightelf_male/nightelf_male_eyes_1.dds
  gfx/characters/nightelf_male/nightelf_male_face.dds
  gfx/characters/nightelf_male/nightelf_male_glow.dds
  gfx/characters/nightelf_male/nightelf_male_hair_1.dds
  gfx/characters/nightelf_male/nightelf_male_hair_behind_1.dds
  gfx/characters/nightelf_male/nightelf_male_headgear.dds
  gfx/characters/nightelf_male/nightelf_male_headgear_behind.dds
  gfx/characters/nightelf_male/nightelf_male_headgear_mid.dds
  interface/portrait_properties/00_portrait_properties.txt
  interface/portraits/portraits_nightelf.gfx
  interface/portraits/portraits_nightelf_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1591 Highborne portraits
  gfx/characters/highborne_female/highborne_female_base.dds
  gfx/characters/highborne_female/highborne_female_clothes.dds
  gfx/characters/highborne_female/highborne_female_clothes_behind.dds
  gfx/characters/highborne_female/highborne_female_headgear.dds
  gfx/characters/highborne_female/highborne_female_headgear_behind.dds
  gfx/characters/highborne_female/highborne_female_headgear_mid.dds
  gfx/characters/highborne_male/highborne_male_base.dds
  gfx/characters/highborne_male/highborne_male_clothes.dds
  gfx/characters/highborne_male/highborne_male_clothes_behind.dds
  gfx/characters/highborne_male/highborne_male_headgear.dds
  gfx/characters/highborne_male/highborne_male_headgear_behind.dds
  gfx/characters/highborne_male/highborne_male_headgear_mid.dds
  interface/portraits/portraits_highborne.gfx
  interface/portraits/portraits_highborne_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1588 Adressed #1104 holding types
  history/provinces/1157 - Rustbolt.txt
  history/provinces/1158 - Scrapbone.txt
  history/provinces/1563 - Sunstone.txt
  history/provinces/1564 - Khartut.txt
  history/provinces/1585 - Sunsuph.txt
  history/provinces/159 - Greenhills.txt
  history/provinces/1610 - Southmoon.txt
  history/provinces/1611 - Eastmoon.txt
  history/provinces/1619 - Ishrak.txt
  history/provinces/162 - Silverstream.txt
  history/provinces/1638 - Isildien.txt
  history/provinces/1642 - Ravenwind.txt
  history/provinces/1644 - Oneiros.txt
  history/provinces/1654 - Darkmist.txt
  history/provinces/1655 - Emyilond.txt
  history/provinces/1656 - Asannaes.txt
  history/provinces/1698 - Ethel Rethor.txt
  history/provinces/1701 - Spiritvale.txt
  history/provinces/175 - Iron Ridge.txt
  history/provinces/1853 - Zoram.txt
  history/provinces/1854 - Blackfathom.txt
  history/provinces/1866 - Hetaera.txt
  history/provinces/1867 - Blackmaw.txt
  history/provinces/1871 - Nendis.txt
  history/provinces/1875 - Arkkoran.txt
  history/provinces/1876 - Eldara.txt
  history/provinces/1912 - Timbermaw.txt
  history/provinces/1913 - Talonbranch.txt
  history/provinces/1947 - Timberpoof.txt
  history/provinces/1956 - Winterfall.txt
  history/provinces/1970 - Shadow Rock.txt
  history/provinces/1971 - Iknal.txt
  history/provinces/1978 - Bristlelimb.txt
  history/provinces/1980 - Emberglade.txt
  history/provinces/2186 - Bridgeport.txt
  history/provinces/220 - Goshek.txt
  history/provinces/2202 - Storm Isle.txt
  history/provinces/2219 - Starfall_2.txt
  history/provinces/2221 - Jinkalak.txt
  history/provinces/2223 - Swale.txt
  history/provinces/2235 - Rezan.txt
  history/provinces/2239 - Atalgral.txt
  history/provinces/297 - Koroth.txt
  history/provinces/332 - Corins Crossing.txt
  history/provinces/333 - Northdale.txt
  history/provinces/350 - Silverfury.txt
  history/provinces/357 - Sanctum of the Sun.txt
  history/provinces/370 - Fairbreeze.txt
  history/provinces/376 - North Sanctum.txt
  history/provinces/381 - Falthrien.txt
  history/provinces/49 - Vice.txt
  history/provinces/702 - Wyrmskull Coast.txt
  history/provinces/737 - Grizzlemaw.txt
  history/provinces/744 - Ursden.txt
  history/provinces/755 - Zolheb.txt
  history/provinces/789 - Moaki.txt
  history/provinces/845 - Enkilah.txt
  history/provinces/886 - Thunderfall.txt
  history/titles/b_rustberg.txt
  history/titles/d_isildien.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :wrench: bug fix :hammer:

#1582 Waterspeaking
  common/scripted_score_values/wc_scripted_score_values.txt
  decisions/wc_religion_decisions.txt
  events/wc_primitive_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1587 Ursine description
  localisation/wc_religions.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1593 nightelf and highborne small fel corrupted
  common/cultures/culture_demonic.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  gfx/characters/highborne_male/highborne_male_headgear.dds
  gfx/characters/highborne_male/highborne_male_headgear_mid.dds
  gfx/characters/nightelf_male/nightelf_male_beard_1.dds
  gfx/characters/nightelf_male/nightelf_male_headgear.dds
  gfx/characters/nightelf_male/nightelf_male_headgear_mid.dds
  interface/portraits/portraits_highborne.gfx
  interface/portraits/portraits_nightelf.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high
