Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-06, with the labels that each got.

#1596 Gorian Empire
  common/bloodlines/wc_earned_bloodlines.txt
  common/government_flavor/00_government_flavor.txt
  common/governments/feudal_governments.txt
  common/governments/tribal_governments.txt
  common/job_titles/00_job_titles.txt
  common/landed_titles/wc_titular_titles.txt
  common/laws/succession_laws.txt
  common/minor_titles/00_minor_titles.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/objectives/00_factions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/02_scripted_effects_alternate_start.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_voting_score_values.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/succession_voting/01_succession_voting_specials.txt
  common/traits/wc_congenital_traits.txt
  decisions/realm_decisions.txt
  decisions/wc_form_x_title_decisions.txt
  events/HFP_random_flavor_events.txt
  events/HF_bloodline_events.txt
  events/HF_warrior_lodge_powers_events.txt
  events/job_offmap.txt
  events/on_action_events.txt
  events/plot_events.txt
  events/various_notification_events.txt
  events/wc_ogre_events.txt
  events/wc_troll_events.txt
  events/ze_marshal_events.txt
  gfx/event_pictures/gorian_empire.tga
  gfx/flags/e_gorian_empire.tga
  gfx/interface/decision_icons/form_the_gorian_empire.dds
  history/provinces/1631 - Eldrethalas.txt
  history/titles/e_gorian_empire.txt
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1445 Vectorized Scary Runes
  .artist_resources/coas/scary_runes_pattern.png
  .artist_resources/coas/scary_runes_pattern.svg
  .artist_resources/coas/scary_runes_pattern.xcf
  gfx/coats_of_arms/scary_runes_pattern.tga
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1595 Titanic branches
  .artist_resources/templates/religious_branch.dds
  .artist_resources/traits/religious traits/titanic_branches.xcf
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/06_scripted_effects_legendary_bloodlines.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/traits/wc_religious_traits.txt
  decisions/conversion_decisions.txt
  decisions/employment_decisions.txt
  decisions/hf_warrior_lodge_decisions.txt
  decisions/wc_religion_decisions.txt
  events/wc_on_action_events.txt
  events/wc_race_events.txt
  events/wc_religious_events.txt
  events/wc_startup_events.txt
  gfx/event_pictures/algalon.tga
  gfx/event_pictures/mechagnome.tga
  gfx/event_pictures/storm_peaks.tga
  gfx/interface/decision_icons/pick_titanic_branch.dds
  gfx/traits/gears_branch.dds
  gfx/traits/rocks_branch.dds
  gfx/traits/storms_branch.dds
  interface/wc_alternative_event_pictures.gfx
  interface/wc_decision_icons.gfx
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1542 19th Small Improvments
  common/artifacts/909_wc_artifacts_library_librams.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/game_rules/000_wc_game_rules.txt
  common/objectives/00_plots.txt
  common/on_actions/00_on_actions.txt
  common/retinue_subunits/00_retinue_subunits.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/special_troops/wc_special_troops.txt
  common/traits/wc_special_traits.txt
  decisions/mnm_society_decisions.txt
  decisions/wc_class_decisions.txt
  decisions/wc_court_decisions.txt
  decisions/wc_order_decisions.txt
  decisions/wc_politfaction_decisions.txt
  decisions/wc_realm_decisions.txt
  events/wc_class_events.txt
  events/wc_court_events.txt
  events/wc_dark_cult_events.txt
  events/wc_race_events.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  history/characters/22000_wildhammer.txt
  history/titles/c_aerie_peak.txt
  history/titles/c_dark_portal.txt
  history/titles/c_sweet_ravine.txt
  history/titles/d_dryslope.txt
  history/titles/k_wildhammer.txt
  localisation/000_wc_military_localization.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#1543 3.3.2 adaptation
  common/artifacts/00_artifacts.txt
  common/cultures/00_cultures.txt
  common/death_text/00_death_text.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/traits/02_traits.txt
  common/wonder_upgrades/00_wonder_upgrades.txt
  common/wonders/00_wonders.txt
  decisions/LT_decisions.txt
  decisions/conversion_decisions.txt
  decisions/mnm_secret_religious_societies_decisions.txt
  decisions/mnm_society_decisions.txt
  decisions/rip_various_decisions.txt
  events/HFP_crusade_events.txt
  events/HF_battle_events.txt
  events/LT_court_maintenance_events.txt
  events/LT_featured_ruler.txt
  events/LT_wonder_flavor_events.txt
  events/LT_wonder_maintenance_events.txt
  events/bankruptcy_events.txt
  events/crusade_events.txt
  events/feast_events.txt
  events/hf_warrior_lodge_legends_events.txt
  events/lovers_events.txt
  events/oldgods_historical_events.txt
  events/on_action_events.txt
  events/rebel_events_the_old_gods.txt
  events/religious_events.txt
  events/rip_eternal_life_events.txt
  events/soa_holy_order_events.txt
  events/wc_society_events.txt
  events/wol_business_events.txt
  interface/generalstuff.gfx
  interface/highlighted_ruler.gui
  interface/province.gfx
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1534 Province name overwrites
  localisation/000_Other_title_names.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1403 Attempt to fix artifact scope related error from error.log
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority low, :wrench: bug fix :hammer:

#1338 Main Menu Mod Version
  .artist_resources/_unused/gfx/interface/frontend_title_alt.dds
  .artist_resources/main_menu_game_version/bmfont.bmfc
  .artist_resources/main_menu_game_version/frontend_title.xcf
  gfx/fonts/lifecraft.dds
  gfx/fonts/lifecraft.fnt
  gfx/interface/frontend_title.alt.dds
  gfx/interface/frontend_title.dds
  interface/frontend.gui
  interface/wc_fonts.gfx
  localisation/000_wc_mod_version.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1598 Kobold rework
  common/religions/primitive_group.txt
  decisions/wc_religion_decisions.txt
  events/wc_primitive_events.txt
  interface/sad_event_pictures.gfx
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority low, :page_facing_up: localisation :pen:, :star: new feature :new:

#1607 Small portrait improving
  .artist_resources/portraits/night_elf_female/nightelf_undead_female_base_1.xcf
  .artist_resources/portraits/night_elf_male/nightelf_undead_male_face.xcf
  common/cultures/culture_elf.txt
  common/cultures/culture_undead.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/scripted_effects/wc_class_scripted_effects.txt
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  gfx/characters/nightelf_female/nightelf_undead_female_base.dds
  gfx/characters/nightelf_male/nightelf_male_base_1.dds
  gfx/characters/nightelf_male/nightelf_male_beard_1.dds
  gfx/characters/nightelf_male/nightelf_male_clothes.dds
  gfx/characters/nightelf_male/nightelf_male_hair_1.dds
  gfx/characters/nightelf_male/nightelf_undead_male_base.dds
  gfx/characters/nightelf_male/nightelf_undead_male_face.dds
  history/characters/310000_patron_characters.txt
  history/characters/42000_high_elf.txt
  interface/portraits/portraits_highborne.gfx
  interface/portraits/portraits_highelf.gfx
  interface/portraits/portraits_nightelf.gfx
  interface/portraits/portraits_nightelf_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1395 Reworked generic artifact trigger and effects
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  common/scripted_triggers/wc_artifact_spawning_scripted_triggers.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#1630 Hozen portraits
  gfx/characters/hozen_female/hozen_female_neck_1.dds
  gfx/characters/hozen_male/hozen_male_base_1.dds
  gfx/characters/hozen_male/hozen_male_neck_1.dds
  interface/portraits/portraits_hozen.gfx
  interface/portraits/portraits_hozen_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1601 Tabard of the Hand of Argus
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  events/wc_draenei_events.txt
  gfx/interface/inventory/artifacts/argus_tabard.dds
  gfx/interface/inventory/artifacts/argus_tabard_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1629 Elunic Branches
  .artist_resources/traits/religious traits/elunic_branches.xcf
  common/event_modifiers/wc_event_modifiers.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/traits/wc_religious_traits.txt
  decisions/wc_religion_decisions.txt
  events/wc_religious_events.txt
  events/wc_sad.txt
  gfx/interface/decision_icons/pick_religious_branch_kaldorei_religion.dds
  gfx/interface/decision_icons/pray_to_elune.dds
  gfx/traits/dark_elune_branch.dds
  gfx/traits/light_elune_branch.dds
  interface/wc_decision_icons.gfx
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1637 Mantid Portraits
  common/cultures/culture_aqir.txt
  gfx/characters/mantid_child/mantid_child_female.dds
  gfx/characters/mantid_child/mantid_child_male.dds
  gfx/characters/mantid_female/mantid_female_base_1.dds
  gfx/characters/mantid_male/mantid_male_neck_1.dds
  interface/portraits/portraits_mantid.gfx
  interface/portraits/portraits_mantid_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1647 Fixed #1646 fel night elven and highborn portraits
  decisions/wc_test_decisions.txt
  interface/portraits/portraits_highborne_sprites.gfx
  interface/portraits/portraits_highelf_sprites.gfx
  interface/portraits/portraits_highelfdemon_sprites.gfx
  interface/portraits/portraits_human_sprites.gfx
  interface/portraits/portraits_nightelf_sprites.gfx
  interface/portraits/portraits_nightelfdemon_sprites.gfx
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1653 Panda crossing
  map/adjacencies.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1615 1st (not really) balance tweaks
  common/cb_types/00_cb_types.txt
  common/cb_types/wc_cb_types.txt
  common/disease/00_disease.txt
  common/disease/wc_disease.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/game_rules/000_wc_game_rules.txt
  common/objectives/00_factions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  common/succession_voting/wc_succession_voting.txt
  decisions/faction_decisions.txt
  decisions/wc_war_decisions.txt
  events/rip_flavor_events.txt
  events/rip_outbreak_events.txt
  events/rip_prosperity_events.txt
  events/wc_dark_cult_events.txt
  events/wc_fel_events.txt
  events/wc_first_war_events.txt
  events/wc_immortal_events.txt
  events/wc_quest_events.txt
  events/wc_second_war_events.txt
  events/wc_third_war_events.txt
  events/wc_war_events.txt
  history/wars/first_war.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium

#1628 32th Bug Сrusade
  common/cultures/culture_aqir.txt
  common/cultures/culture_human.txt
  common/landed_titles/z_holy_sites.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_class_decisions.txt
  decisions/wc_religion_decisions.txt
  events/LT_court_maintenance_events.txt
  events/wc_dark_cult_events.txt
  events/wc_frozen_throne_story_events.txt
  events/wc_plague_events.txt
  events/wc_politfaction_events.txt
  events/wc_undead_events.txt
  history/characters/11000_dark_iron.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/42000_high_elf.txt
  history/provinces/1638 - Isildien.txt
  history/provinces/1703 - Bladefist.txt
  history/titles/c_eldrethalas.txt
  history/titles/c_elunar.txt
  history/titles/c_estulan.txt
  history/titles/c_frayfeather.txt
  history/titles/c_ishelean.txt
  history/titles/c_isildien.txt
  history/titles/d_isildien.txt
  localisation/00_wc_ruler_titles.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1656 Vanilla holding icons
  common/cultures/culture_furbolg.txt
  common/cultures/culture_gnoll.txt
  common/cultures/culture_gnome.txt
  common/cultures/culture_harpy.txt
  common/cultures/culture_hozen.txt
  common/cultures/culture_kobold.txt
  common/cultures/culture_magnataur.txt
  common/cultures/culture_murloc.txt
  common/cultures/culture_ogre.txt
  common/cultures/culture_pygmy.txt
  common/cultures/culture_quilboar.txt
  common/cultures/culture_sethrak.txt
  common/cultures/culture_tauren.txt
  common/cultures/culture_titanforged.txt
  common/cultures/culture_trogg.txt
  common/cultures/culture_troll.txt
  common/cultures/culture_tuskarr.txt
  common/cultures/culture_vrykul.txt
  common/cultures/culture_vulpera.txt
  interface/wc_holdings.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1577 Localisation crusade 17
  localisation/000_Other_title_names.csv
  localisation/000_wc_military_localization.csv
  localisation/000_wc_traits.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_economy.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
  localisation/wc_religion_buildings.csv
  localisation/wc_religions.csv
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1549 Artifacts for Gorak Tul
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  events/wc_crisis_events.txt
  gfx/interface/inventory/artifacts/blightreaper.dds
  gfx/interface/inventory/artifacts/blightreaper_small.dds
  gfx/interface/inventory/artifacts/mantle_of_gorak_tul.dds
  gfx/interface/inventory/artifacts/mantle_of_gorak_tul_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1400 Reworked Vanilla Sacrifice Events
  common/scripted_effects/wc_sacrifice_scripted_effects.txt
  events/HF_religious_events.txt
  events/sunset_invasion.txt
  events/wc_sacrifice_events.txt
  localisation/00_wc_sacrifice_events.csv
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#1660 Refactored can_fight_prev_trigger
  common/cb_types/00_cb_types.txt
  common/cb_types/01_cb_types.txt
  common/cb_types/02_cb_types_shattered_world.txt
  common/cb_types/wc_cb_types.txt
  common/scripted_triggers/wc_scripted_triggers.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1623 Adapted Hermetics
  common/artifacts/00_artifacts.txt
  common/minor_titles/00_minor_titles.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/scripted_triggers/wc_society_scripted_triggers.txt
  common/societies/00_societies.txt
  common/societies/wc_societies.txt
  common/wonder_upgrades/00_wonder_upgrades.txt
  decisions/mnm_hermetics_decisions.txt
  decisions/wc_society_decisions.txt
  events/mnm_hermetics_events.txt
  events/wc_quest_events.txt
  gfx/interface/inventory/artifacts/discs_norgannon.dds
  gfx/interface/inventory/artifacts/discs_norgannon_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1664 custom loc code name change
  common/scripted_effects/wc_artifacts_generic_scripted_effects.txt
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1514 3rd Historical Flavor Crusade
  common/dynasties/116000_tauren.txt
  common/dynasties/1_azerothian.txt
  common/dynasties/26000_tirassian.txt
  common/dynasties/30000_lordaeronian.txt
  common/dynasties/32000_hillsbrad.txt
  common/dynasties/34000_alteraci.txt
  common/dynasties/42000_ogre.txt
  common/dynasties/60000_pirate.txt
  common/landed_titles/wc_titular_titles.txt
  common/nicknames/wc_nicknames.txt
  history/characters/1_azerothian.txt
  history/characters/210000_tauren.txt
  history/characters/48000_tirassian.txt
  history/characters/52000_ogre.txt
  history/characters/53000_hillsbrad.txt
  history/characters/58000_alteraci.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/90000_pirate.txt
  history/provinces/1159 - Grum.txt
  history/provinces/1160 - Shipwreck.txt
  history/provinces/2220 - Forlorn_3.txt
  history/provinces/2222 - Northpoint.txt
  history/provinces/2224 - Roaring Wilds.txt
  history/provinces/2225 - Polder Crag.txt
  history/provinces/2227 - Lapidis Island.txt
  history/provinces/2229 - Ungol.txt
  history/provinces/94 - South Islands.txt
  history/titles/c_crystalvale.txt
  history/titles/c_deathknell.txt
  history/titles/c_forlorn_3.txt
  history/titles/c_frostsabre.txt
  history/titles/c_grum.txt
  history/titles/c_hatherford.txt
  history/titles/c_lapidis_island.txt
  history/titles/c_north_tide.txt
  history/titles/c_northpoint.txt
  history/titles/c_polder_crag.txt
  history/titles/c_roaring_wilds.txt
  history/titles/c_shipwreck.txt
  history/titles/c_skittering_dark.txt
  history/titles/c_south_islands.txt
  history/titles/c_tol_ronal.txt
  history/titles/c_ungol.txt
  history/titles/d_bloodsail_buccaneers.txt
  history/titles/d_channel_islands.txt
  history/titles/d_silverpine.txt
  localisation/000_Other_title_names.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1666 Closed #1425 winters
  common/landed_titles/01_landed_titles.txt
  history/provinces/2224 - Roaring Wilds.txt
  history/provinces/2225 - Polder Crag.txt
  history/provinces/2227 - Lapidis Island.txt
  map/climate.txt
  map/provinceDef.xls
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :star: new feature :new:

#1668 1st Pandaria Fixes and Tweaks
  common/cultures/culture_hozen.txt
  common/cultures/culture_mogu.txt
  common/cultures/culture_trogg.txt
  common/religions/pandaren_religion_group.txt
  common/religions/secular_group.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  interface/coat_of_arms/coats_of_arms.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical, :wrench: bug fix :hammer:
