Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-07, with the labels that each got.

#1671 Pandaria Winters
  map/climate.txt
  map/provinceDef.xls
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#1667 21th Small Improvments
  common/cultures/culture_gnoll.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/laws/succession_laws.txt
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/01_scripted_effects_duels.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_health_traits.txt
  common/traits/wc_race_traits.txt
  decisions/hf_warrior_lodge_decisions.txt
  events/HF_religious_events.txt
  events/on_action_events.txt
  events/wc_addiction_events.txt
  events/wc_crisis_events.txt
  events/wc_race_events.txt
  events/wc_startup_events.txt
  events/wc_third_war_events.txt
  history/characters/29000_gnoll.txt
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#1674 Split of Yulin
  common/landed_titles/01_landed_titles.txt
  common/landed_titles/z_landed_titles_pandaria.txt
  gfx/flags/_other/d_lushat_lan.tga
  gfx/flags/d_dawnchaser.tga
  gfx/flags/d_lei_jiao.tga
  gfx/flags/d_marista.tga
  gfx/flags/e_banshan.tga
  gfx/flags/k_sheilun.tga
  history/provinces/1171 - Makers Perch.txt
  history/provinces/1172 - Nalaksha.txt
  history/technology/e_banshan.txt
  history/technology/e_yulin.txt
  history/titles/d_dawnchaser.txt
  history/titles/d_lei_jiao.txt
  history/titles/d_lushat_lan.txt
  history/titles/d_marista.txt
  history/titles/e_banshan.txt
  history/titles/k_sheilun.txt
  localisation/00_Duchy_names.csv
  localisation/00_Empire_names.csv
  localisation/00_Kingdom_names.csv
  map/climate.txt
  map/geographical_region.txt
  map/island_region.txt
  map/provinceDef.xls
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#1678 Generic empire name
  localisation/00_wc_ruler_titles_castle.csv
Labels: :exclamation: priority critical, :star: new feature :new:

#1676 Drust title fix
  common/dynasties/70000_vrykul.txt
  events/wc_crisis_events.txt
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_tribal.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1679 Working Pandaria life spans
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_race_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1583 Panda and mogu temporary portraits
  gfx/characters/mogu_child/mogu_female_child.dds
  gfx/characters/mogu_child/mogu_male_child.dds
  gfx/characters/mogu_female/mogu_female_neck_1.dds
  gfx/characters/mogu_male/mogu_male_base_1.dds
  gfx/characters/pandaren_female/pandaren_female_base_1.dds
  gfx/characters/pandaren_male/pandaren_male_base_1.dds
  interface/portraits/portraits_mogu.gfx
  interface/portraits/portraits_mogu_sprites.gfx
  interface/portraits/portraits_pandaren.gfx
  interface/portraits/portraits_pandaren_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1680 Grummle portraits
  gfx/characters/grummle_child/grummle_child_female.dds
  gfx/characters/grummle_child/grummle_child_male.dds
  gfx/characters/grummle_female/grummle_female_base_1.dds
  gfx/characters/grummle_male/grummle_male_base_1.dds
  interface/portraits/portraits_grummle.gfx
  interface/portraits/portraits_grummle_sprites.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1631 Saurok portraits
  gfx/characters/saurok_child/saurok_child_female.dds
  gfx/characters/saurok_child/saurok_child_male.dds
  gfx/characters/saurok_female/saurok_female_neck_1.dds
  gfx/characters/saurok_male/saurok_male_neck_1.dds
  interface/portraits/portraits_saurok.gfx
  interface/portraits/portraits_saurok_sprites.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1686 2nd Religious Icon Rework
  common/landed_titles/z_holy_sites.txt
  common/religions/arcane_group.txt
  common/religions/dragon_religion_group.txt
  common/religions/druidism_group.txt
  common/religions/elemental_lords_group.txt
  common/religions/fel_group.txt
  common/religions/light_group.txt
  common/religions/loa_group.txt
  common/religions/necromancy_group.txt
  common/religions/nerubian_religion_group.txt
  common/religions/pandaren_religion_group.txt
  common/religions/primitive_group.txt
  common/religions/secular_group.txt
  common/religions/shamanism_group.txt
  common/religions/void_group.txt
  common/religions/vrykul_religion_group.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_religion_decisions.txt
  gfx/interface/religion_icon_strip.dds
  gfx/interface/religion_icon_strip_big.dds
  gfx/interface/religion_icon_strip_small.dds
  history/characters/380000_frostnymph.txt
  history/provinces/713 - Giants Run.txt
  history/provinces/715 - Glade Forest.txt
  interface/coat_of_arms/coats_of_arms.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1644 Class immortality rework
  common/bloodlines/02_earned_bloodlines.txt
  common/game_rules/00_game_rules.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_class_traits.txt
  events/rip_eternal_life_events.txt
  events/wc_race_events.txt
  localisation/00_wc_vanilla_replacements.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#1696 The Shenic icon issue
  common/religions/secular_group.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1681 Sha
  common/event_modifiers/wc_event_modifiers.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_trait_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_sha_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1694 Spiritbinding
  common/scripted_effects/wc_corruption_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_vanilla_scripted_triggers.txt
  decisions/wc_race_decisions.txt
  events/wc_race_events.txt
  gfx/event_pictures/jade_mogu_golem.tga
  gfx/interface/decision_icons/build_new_vessel.dds
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1672 Eastern religions adaptation
  common/cb_types/00_cb_types.txt
  common/minor_titles/00_minor_titles.txt
  common/nicknames/00_nicknames.txt
  common/objectives/00_ambitions.txt
  common/on_actions/00_on_actions.txt
  common/religions/pandaren_religion_group.txt
  common/religions/secular_group.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/06_scripted_effects_legendary_bloodlines.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/01_scripted_triggers_combat.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/conversion_decisions.txt
  decisions/dynasty_decisions.txt
  decisions/employment_decisions.txt
  decisions/hf_warrior_lodge_decisions.txt
  decisions/jd_taoist_decisions.txt
  decisions/minor_decisions.txt
  decisions/settlement_decisions.txt
  events/HFP_health_events.txt
  events/HF_baptism_events.txt
  events/HF_bloodline_acquisition_events.txt
  events/HF_bloodline_events.txt
  events/HF_religious_events.txt
  events/LT_wonder_flavor_events.txt
  events/adventurers_negotiation.txt
  events/cm_murder_plot_events.txt
  events/councillor_events.txt
  events/female_councillor_events.txt
  events/guardian_events.txt
  events/indian_pilgrim_events.txt
  events/jd_chinese_invasion_events.txt
  events/job_lord_spiritual.txt
  events/job_offmap.txt
  events/lovers_events.txt
  events/mnm_artifacts_events.txt
  events/mnm_monastic_orders_events.txt
  events/religious_events.txt
  events/rip_hospital_events.txt
  events/rip_physician_events.txt
  events/roi_feast_events.txt
  events/roi_guru_events.txt
  events/soa_heresy_events.txt
  events/various_traits_events.txt
  events/wol_hunting_events.txt
  events/wol_intrigue_events.txt
  events/wol_scholarship_events.txt
  events/wol_seduction_events.txt
  events/wol_theology_events.txt
  events/ze_adolescence_events.txt
  events/ze_extra_events.txt
  events/ze_lord_spiritual_events.txt
  gfx/event_pictures/roi_peasants_and_elephants.dds
  gfx/event_pictures/roi_ruler_riding_elephant.dds
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :hammer: maintenance :wrench:, :star: new feature :new:

#1670 Coat of Arms 3
  .artist_resources/coas/10x6.png
  .artist_resources/coas/10x7.png
  .artist_resources/coas/7x10.png
  .artist_resources/coas/7x6.png
  .artist_resources/coas/ancient_symbols_pattern.svg
  .artist_resources/coas/pandaren_symbols_pattern.svg
  .artist_resources/coas/vrykul_runes_pattern.svg
  gfx/coats_of_arms/ancient_symbols_pattern.tga
  gfx/coats_of_arms/pandaren_symbols_pattern.tga
  gfx/coats_of_arms/vrykul_runes_pattern.tga
  interface/coat_of_arms/coats_of_arms.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1702 Pandaria holy sites
  common/landed_titles/z_holy_sites.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#1705 Sunwell religious head bugfix
  history/titles/c_falthrien.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1689 Adding Justice Gaze to the game
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/902_wc_artifacts_crown_helmets.txt
  gfx/interface/inventory/artifacts/justice_gaze.dds
  gfx/interface/inventory/artifacts/justice_gaze_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :star: new feature :new:

#1706 Memefixes 7
  decisions/wc_society_decisions.txt
  events/wc_frozen_throne_story_events.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/6000_gurubashi.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:, :wrench: bug fix :hammer:

#1455 French localisation
  localisation/000_Other_title_names.csv
  localisation/000_wc_military_localization.csv
  localisation/000_wc_traits.csv
  localisation/00_ciwc_united_localisation.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_economy.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_government.csv
  localisation/00_wc_job_titles.csv
  localisation/00_wc_mnm_replace.csv
  localisation/00_wc_offmap.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_ruler_titles_city.csv
  localisation/00_wc_ruler_titles_magocracy.csv
  localisation/00_wc_ruler_titles_nomadic.csv
  localisation/00_wc_ruler_titles_technocracy.csv
  localisation/00_wc_ruler_titles_temple.csv
  localisation/00_wc_ruler_titles_tribal.csv
  localisation/00_wc_ruler_titles_vice_royalty.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
  localisation/tyr_wc_loa.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
  localisation/wc_religion_buildings.csv
  localisation/wc_religions.csv
  localisation/wc_uniques.csv
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:

#1708 33th Bug Crusade
  common/retinue_subunits/00_retinue_subunits.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/00_scripted_triggers.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_plot_triggers.txt
  decisions/rip_various_decisions.txt
  events/wc_dark_cult_events.txt
  events/wc_politfaction_events.txt
  gfx/coats_of_arms/dynasties_orcish.tga
  gfx/coats_of_arms/dynasties_orcish2.tga
  history/characters/42000_high_elf.txt
  history/characters/60000_63000_lordaeronian.txt
  history/characters/66000_zandalari.txt
  interface/coat_of_arms/coats_of_arms.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1482 Cho'galls Journey
  common/dynasties/2000_orc.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/scripted_triggers/wcsp_scripted_triggers.txt
  decisions/wc_dark_cult_decisions.txt
  events/wc_dark_cult_events.txt
  events/wc_on_action_events.txt
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
  history/provinces/1619 - Ishrak.txt
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1684 Adding of Elun'tara to the game
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  gfx/interface/inventory/artifacts/eluntara.dds
  gfx/interface/inventory/artifacts/eluntara_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :star: new feature :new:

#1717 Young Zul
  history/characters/66000_zandalari.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1718 2nd Pandaria Fixes and Tweaks
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_race_events.txt
  gfx/flags/e_shekmag.tga
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :wrench: bug fix :hammer:

#1673 Localisation crusade 18
  common/defines/00_dummy.lua
  events/wc_frostwolf_events.txt
  events/wc_third_war_events.txt
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_generics.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1677 Pandaria Empire
  common/bloodlines/wc_earned_bloodlines.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_effects/wc_title_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_form_x_title_decisions.txt
  events/wc_pandaria_events.txt
  events/wc_title_events.txt
  gfx/event_pictures/pandaria_twin_monoliths.tga
  gfx/flags/_unused/d_silverwing_sentinels.tga
  gfx/flags/e_pandaria_empire.tga
  gfx/interface/decision_icons/form_the_pandaria_empire.dds
  history/titles/e_pandaria_empire.txt
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1722 2nd Balance Tweaks
  common/defines/00_dummy.lua
  decisions/wc_undead_decisions.txt
  decisions/wc_war_decisions.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority critical

#1724 7th Patrons
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/titles/b_follruk.txt
  history/titles/b_shiftbomb_3.txt
  history/titles/c_ametharan.txt
  history/titles/c_binanu.txt
  history/titles/c_deep_elem.txt
  history/titles/c_faerseton.txt
  history/titles/c_falthrien.txt
  history/titles/c_sentinel_hill.txt
  history/titles/c_spiritvale.txt
Labels: :exclamation: priority critical, :star: new feature :new:

#1725 Invaders' hotfixes
  common/cb_types/00_cb_types.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  decisions/wc_class_decisions.txt
  decisions/wc_dark_cult_decisions.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1726 4th Flags
  gfx/flags/d_constellas.tga
  gfx/flags/d_dordanil.tga
  gfx/flags/d_east_dun_morogh.tga
  gfx/flags/d_golden_strand.tga
  gfx/flags/d_isildien.tga
  gfx/flags/d_khartut.tga
  gfx/flags/d_murcevin.tga
  gfx/flags/d_nittawosew.tga
  gfx/flags/d_ordilaran.tga
  gfx/flags/d_queldanas_isle.tga
  gfx/flags/d_red_cloud.tga
  gfx/flags/d_searing_gorge.tga
  gfx/flags/d_shalandis.tga
  gfx/flags/d_silvermoon.tga
  gfx/flags/d_stardust.tga
  gfx/flags/d_sungraze_peak.tga
  gfx/flags/d_sunnyglade.tga
  gfx/flags/d_thalassian_pass.tga
  gfx/flags/d_zolnanji.tga
  gfx/flags/k_frostmane.tga
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1734 Yaungol portraits
  gfx/characters/yaungol_male/yaungol_male_beard_1.dds
  gfx/characters/yaungol_male/yaungol_male_beard_ties_front.dds
  gfx/characters/yaungol_male/yaungol_male_brows.dds
  gfx/characters/yaungol_male/yaungol_male_fur.dds
  gfx/characters/yaungol_male/yaungol_male_hair_1.dds
  gfx/characters/yaungol_male/yaungol_male_hair_behind_1.dds
  gfx/characters/yaungol_male/yaungol_male_horns_1.dds
  gfx/characters/yaungol_male/yaungol_male_neck_1.dds
  interface/portraits/portraits_yaungol.gfx
  interface/portraits/portraits_yaungol_sprites.gfx
Labels: :art: graphics :paintbrush:, :star: new feature :new:
