Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-01, with the labels that each got.

#1039 Balkanized Vrykul
  .artist_resources/flags/k_howling_fjord.xcf
  common/dynasties/70000_vrykul.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_effects/wc_scripted_effects.txt
  decisions/wc_realm_decisions.txt
  events/wc_realm_events.txt
  gfx/coats_of_arms/dynasties_vrykul.tga
  gfx/event_pictures/utgarde.tga
  gfx/flags/d_winterskorn.tga
  gfx/flags/k_howling_fjord.tga
  gfx/interface/decision_icons/awaken_ymiron.dds
  history/characters/100000_vrykul.txt
  history/provinces/696 - Utgarde.txt
  history/provinces/698 - Ember Clutch.txt
  history/provinces/699 - New Agamand.txt
  history/provinces/700 - Shield Hill.txt
  history/provinces/702 - Wyrmskull Coast.txt
  history/provinces/708 - Bealgun.txt
  history/provinces/709 - Eastern Cape.txt
  history/provinces/718 - Gjalerbron.txt
  history/provinces/720 - Steelgate.txt
  history/provinces/736 - Voldrune.txt
  history/titles/c_bealgun.txt
  history/titles/c_eastern_cape.txt
  history/titles/c_ember_clutch.txt
  history/titles/c_gjalerbron.txt
  history/titles/c_grarland.txt
  history/titles/c_halgrind.txt
  history/titles/c_new_agamand.txt
  history/titles/c_nifflevar.txt
  history/titles/c_shield_hill.txt
  history/titles/c_steelgate.txt
  history/titles/c_utgarde.txt
  history/titles/c_voldrune.txt
  history/titles/c_winterhoof.txt
  history/titles/c_wyrmskull_coast.txt
  history/titles/d_dragonflayer.txt
  history/titles/d_giants_run.txt
  history/titles/d_gjalerbron.txt
  history/titles/d_halgrind.txt
  history/titles/d_nifflevar.txt
  history/titles/d_spears_isles.txt
  history/titles/d_utgarde.txt
  history/titles/d_winterskorn.txt
  history/titles/k_howling_fjord.txt
  interface/coat_of_arms/coats_of_arms.txt
  interface/wc_decision_icons.gfx
  interface/wc_event_pictures.gfx
  localisation/000_Other_title_names.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :art: graphics :paintbrush:, :balance_scale: balance :balance_scale:, :exclamation: priority high, :page_facing_up: localization :pen:, :star: new feature :new:

#992 New Councillor Job Titles
  localisation/00_wc_job_titles.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#1037 Camera Position In Menus
  common/defines/camera.lua
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1031 Historical Warcraft Wonders
  history/provinces/226 - Northreach.txt
  history/provinces/227 - Northfold.txt
  history/provinces/269 - Lordaeron.txt
  history/provinces/95 - Surohi.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1064 Zandalar wonders
  history/provinces/3576 - Dazaralor.txt
  history/provinces/3587 - Ataldazar.txt
  history/provinces/3597 - Nazwatha.txt
  history/provinces/3599 - Necropolis.txt
  history/provinces/3604 - Sethraliss.txt
  history/provinces/3610 - Atulaman.txt
  history/provinces/3616 - Slisetriss.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1003 Patrons gamerule
  common/game_rules/wc_unimportant_game_rules.txt
  common/scripted_effects/wc_history_scripted_effects.txt
  history/characters/11000_dark_iron.txt
  history/characters/16000_gnome.txt
  history/characters/310000_patron_characters.txt
  history/characters/42000_high_elf.txt
  history/characters/60000_lordaeronian.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1062 Unused Building Localization
  .coder_resources/_unused/localisation/00_wc_special_units.csv
  .coder_resources/_unused/localisation/not_used_strings.csv
  .coder_resources/_unused/localisation/wc_fel.csv
  .coder_resources/_unused/localisation/wc_oldgods.csv
  .coder_resources/_unused/localisation/wc_scourge.csv
  common/buildings/wc_druidic.txt
  common/buildings/wc_uniques.txt
  common/scripted_effects/wc_building_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  events/wc_dark_cult_events.txt
  localisation/00_wc_generics.csv
  localisation/mercaneries_holyorders.csv
  localisation/wc_religion_buildings.csv
  localisation/wc_uniques.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:

#1032 Frost giants
  common/buildings/wc_castle_culture.txt
  common/retinue_subunits/00_retinue_subunits.txt
  localisation/000_wc_military_localization.csv
  localisation/wc_culture_buildings.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1061 Balkanized Vrykul Fixes
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_government_events.txt
  events/wc_realm_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#976 Culture Switch Limitations
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/conversion_decisions.txt
  events/guardian_events.txt
  events/ze_childhood_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :ice_cream: vanilla modification :icecream:

#968 Generic Jewelry Artifacts
  common/artifacts/904_wc_artifacts_amulets_generic.txt
  common/artifacts/907_wc_artifacts_rings_generic.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_artifacts_gamestart_scripted_effects.txt
  common/scripted_effects/wc_artifacts_scripted_effects.txt
  common/scripted_triggers/wc_scripted_artifacts_triggers.txt
  events/wc_artifact_spawn_gamestart.txt
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_1a_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_1b_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_1c_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_1d_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_1p_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_2a_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_2b_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_2c_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_2d_small.dds
  gfx/interface/inventory/artifacts/inv_6_0raid_necklace_2p_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace2_blue_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace2_green_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace2_purple_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace2_red_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace2_white_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace3_blue_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace3_green_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace3_purple_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace3_red_small.dds
  gfx/interface/inventory/artifacts/inv_jewelcrafting_necklace3_white_small.dds
  gfx/interface/inventory/artifacts/inv_jewelry_necklace_54_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_bluelv1_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_bluelv2_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_bluelv3_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_bluelv4_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_greenlv1_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_greenlv2_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_greenlv3_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_greenlv4_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_purplelv1_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_purplelv2_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_purplelv3_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_purplelv4_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_redlv1_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_redlv2_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_redlv3_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_redlv4_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_silverlv1_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_silverlv2_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_silverlv3_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_silverlv4_small.dds
  gfx/interface/inventory/artifacts/inv_misc_6oring_solium_small.dds
  interface/wc_treasury.gfx
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customizable_localisation_artifact_names.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localization :pen:, :star: new feature :new:

#1074 Generic Artifacts German Loc
  localisation/00_DEwc_united_localisation.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_2_DE_customizable_localisation_artifact_names.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localization :pen:

#1076 Attribute Tooltip Suffix
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customizable_localisation_artifact_names.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localization :pen:

#977 Odd Dynastic Names
  common/dynasties/16000_arathorian.txt
  common/dynasties/1_azerothian.txt
  common/dynasties/22000_baradin.txt
  common/dynasties/24000_gilnean.txt
  common/dynasties/26000_tirassian.txt
  common/dynasties/30000_lordaeronian.txt
  common/dynasties/32000_hillsbrad.txt
  common/dynasties/34000_alteraci.txt
  common/dynasties/36000_dalaranian.txt
Labels: :grey_exclamation: priority low, :page_facing_up: localization :pen:

#1059 24th Bug Сrusade
  common/cb_types/00_cb_types.txt
  common/laws/crown_laws.txt
  common/objectives/00_factions.txt
  common/objectives/00_plots.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/mnm_society_decisions.txt
  events/wc_class_events.txt
  events/wc_fel_events.txt
  localisation/000_wc_traits.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/wc_religions.csv
Labels: :exclamation: priority critical, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#987 Child of Destiny Adaptation
  common/objectives/00_focuses.txt
  common/scripted_triggers/wc_region_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/HF_bloodline_acquisition_events.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/00_customizable_localisation.txt
Labels: :exclamation: priority high, :ice_cream: vanilla modification :icecream:, :page_facing_up: localization :pen:, :wrench: bug fix :hammer:

#1084 Storm Giants
  .artist_resources/portraits/stormgiant_male/light.txt
  .artist_resources/portraits/stormgiant_male/position.txt
  .artist_resources/portraits/stormgiant_male/screenshot_100.tga
  .artist_resources/races/creature_giant/creature_giant.xcf
  .coder_resources/List of races.txt
  common/buildings/wc_castle_culture.txt
  common/cultures/culture_titanforged.txt
  common/dynasties/123000_frozen_giant.txt
  common/dynasties/152000_storm_giant.txt
  common/graphicalculturetypes/wc_graphicalculturetype.txt
  common/retinue_subunits/00_retinue_subunits.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_race_traits.txt
  events/wc_race_events.txt
  gfx/characters/stormgiant_male/stormgiant_male_base_1.dds
  gfx/traits/creature_giant.dds
  gfx/traits/creature_ice_giant.dds
  history/characters/140000_satyr.txt
  history/characters/290000_frozen_giant.txt
  history/characters/440000_storm_giant.txt
  history/provinces/914 - Guodalir.txt
  history/provinces/927 - Jahaqua.txt
  history/provinces/928 - Myehona.txt
  history/provinces/929 - Forlorn.txt
  history/provinces/930 - Assmel.txt
  history/titles/c_assmel.txt
  history/titles/c_forlorn.txt
  history/titles/c_guodalir.txt
  history/titles/c_jahaqua.txt
  history/titles/c_myehona.txt
  history/titles/d_assmel.txt
  history/titles/k_crystalsong_forest.txt
  interface/portraits/portraits_stormgiant.gfx
  interface/portraits/portraits_stormgiant_sprites.gfx
  interface/wc_traits.gfx
  localisation/000_wc_military_localization.csv
  localisation/000_wc_traits.csv
  localisation/WikipediaLinks.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
Labels: :exclamation: priority high, :page_facing_up: localization :pen:, :star: new feature :new:

#1055 Defias Brotherhood
  common/dynasties/1_azerothian.txt
  common/landed_titles/wc_titular_titles.txt
  common/scripted_triggers/wc_faction_scripted_triggers.txt
  gfx/flags/d_defias_brotherhood.tga
  history/characters/1_azerothian.txt
  history/provinces/11 - Stonefield.txt
  history/provinces/12 - Sunnyglade.txt
  history/provinces/17 - Moonbrook.txt
  history/provinces/27 - Gold Coast.txt
  history/provinces/28 - Longshore.txt
  history/provinces/30 - Demont.txt
  history/provinces/32 - Mortwakes Tower.txt
  history/titles/c_demont.txt
  history/titles/c_gold_coast.txt
  history/titles/c_longshore.txt
  history/titles/c_moonbrook.txt
  history/titles/c_mortwakes_tower.txt
  history/titles/c_stonefield.txt
  history/titles/c_sunnyglade.txt
  history/titles/d_defias_brotherhood.txt
  localisation/000_Other_title_names.csv
  localisation/00_wc_ruler_titles.csv
  localisation/WikipediaLinks.csv
Labels: :exclamation: priority critical, :star: new feature :new:

#1087 Sunstrider CoA & Dynamic Quel'thalas Flag
  common/dynasties/20000_high_elf.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_third_war_events.txt
  events/wc_title_events.txt
  gfx/coats_of_arms/dynasties_helf.tga
  interface/coat_of_arms/coats_of_arms.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low, :star: new feature :new:

#1081 Removed Same Being Opinion
  common/modifier_definitions/wc_opinion_modifier_definitions.txt
  common/traits/wc_being_traits.txt
  history/characters/100000_vrykul.txt
  history/characters/66000_zandalari.txt
  history/provinces/3612 - Zemlan.txt
  history/provinces/3623 - Ominous Island.txt
  history/provinces/3623 - Ominous island.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#1086 5th Patrons
  common/dynasties/125000_patron_dynasties.txt
  history/characters/310000_patron_characters.txt
  history/provinces/3536 - Crimson Forest.txt
  history/titles/c_crimson_forest.txt
  history/titles/c_havenswood.txt
  history/titles/c_rotting_mire.txt
  history/titles/c_south_highlands.txt
  history/titles/c_southwatch.txt
  history/titles/c_windshear.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1108 Bugfixes
  common/achievements.txt
  common/retinue_subunits/00_retinue_subunits.txt
  common/scripted_effects/wc_history_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_society_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_fel_events.txt
  events/wc_loa_events.txt
  events/wc_third_war_events.txt
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1078 History Bugfixes
  common/dynasties/310000_unpopulated.txt
  history/characters/1_azerothian.txt
  history/characters/340000_night_elf.txt
  history/characters/390000_sethrak.txt
  history/characters/40000_kobold.txt
  history/characters/420000_ancients.txt
  history/characters/42000_high_elf.txt
  history/characters/46000_gilnean.txt
  history/characters/53000_hillsbrad.txt
  history/characters/54000_witherbark.txt
  history/characters/68000_darkspear.txt
  history/characters/74000_bloodsail.txt
  history/characters/78000_gorloc.txt
  history/characters/80000_drakkari.txt
  history/titles/c_andaroth.txt
  history/titles/c_chagajin.txt
  history/titles/c_darkshore.txt
  history/titles/c_darrow_hill.txt
  history/titles/c_draksotra.txt
  history/titles/c_east_coast.txt
  history/titles/c_east_sanctum.txt
  history/titles/c_fir_valley.txt
  history/titles/c_glumr.txt
  history/titles/c_gokuntea.txt
  history/titles/c_golden_strand.txt
  history/titles/c_goldenmist.txt
  history/titles/c_gorlro.txt
  history/titles/c_greenrush.txt
  history/titles/c_hammondfield.txt
  history/titles/c_ice_pass.txt
  history/titles/c_indule.txt
  history/titles/c_loch_islands.txt
  history/titles/c_loose_cliffs.txt
  history/titles/c_low_fields.txt
  history/titles/c_mamtoth.txt
  history/titles/c_moaki.txt
  history/titles/c_oghit.txt
  history/titles/c_raincoast.txt
  history/titles/c_rainspeaker.txt
  history/titles/c_shadowprey.txt
  history/titles/c_shadraalor.txt
  history/titles/c_shaolwatha.txt
  history/titles/c_south_slough.txt
  history/titles/c_southshore.txt
  history/titles/c_splursh.txt
  history/titles/c_sseratus.txt
  history/titles/c_stormglen.txt
  history/titles/c_tarren_mill.txt
  history/titles/c_tautau.txt
  history/titles/c_tranquil_shore.txt
  history/titles/c_tranquillien.txt
  history/titles/c_verdant_forest.txt
  history/titles/c_wildgrowth.txt
  history/titles/d_draksotra.txt
  history/titles/d_draktharon.txt
  history/titles/d_mistwhispers.txt
  history/titles/d_mosswalkers.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1115 Created Vanilla Replacements File
  localisation/000_wc_traits.csv
  localisation/00_HolyFury.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:, :page_facing_up: localization :pen:
