Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-02, with the labels that each got.

#1083 Generic Artifact Origins
  common/scripted_effects/wc_artifacts_scripted_effects.txt
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_random_artifact_names.csv
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority low, :hammer: maintenance :wrench:, :page_facing_up: localisation :pen:

#1129 Mind Control Effects/Triggers
  common/cb_types/00_cb_types.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/wc_undead_decisions.txt
  events/wc_plague_events.txt
  events/wc_undead_events.txt
  gfx/traits/champion_of_the_lich_king.dds
  interface/wc_traits.gfx
  localisation/000_wc_traits.csv
Labels: :exclamation: priority critical, :hammer: maintenance :wrench:

#1113 Artifacts Spawn Gamerule
  common/artifacts/907_wc_artifacts_rings_generic.txt
  common/game_rules/000_wc_game_rules.txt
  common/scripted_effects/wc_artifacts_gamestart_scripted_effects.txt
  common/scripted_effects/wc_artifacts_scripted_effects.txt
  common/scripted_triggers/wc_scripted_artifacts_spawn_triggers.txt
  events/wc_artifact_spawn_gamestart.txt
  localisation/00_memewc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation_generic_artifacts.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:, :star: new feature :new:, :wrench: bug fix :hammer:

#1131 Interface fix
  interface/domestic_treasury.gui
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low, :wrench: bug fix :hammer:

#1136 Nerfed provinces in Silithus and Ahn'Qiraj kingdoms
  history/provinces/2960 - Hiveashi.txt
  history/provinces/2961 - Crystalvale.txt
  history/provinces/2963 - Hivezora.txt
  history/provinces/2967 - Ashakx.txt
  history/provinces/2968 - Hiveregal.txt
  history/provinces/2969 - Xernannoss.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#1117 Wonders 3
  common/scripted_triggers/wc_religious_triggers.txt
  common/wonder_upgrades/00_wonder_upgrades.txt
  history/provinces/3576 - Dazaralor.txt
  history/provinces/696 - Utgarde.txt
  history/provinces/754 - Gundrak.txt
  history/provinces/81 - Atalhakkar.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1125 Forsaken Culture
  common/buildings/wc_castle_culture.txt
  common/cultures/culture_undead.txt
  common/dynasties/1000_forsaken.txt
  common/landed_titles/wc_titular_titles.txt
  common/landed_titles/z_landed_titles_eastern_kingdoms.txt
  common/scripted_effects/wc_title_scripted_effects.txt
  common/scripted_triggers/wc_title_scripted_triggers.txt
  decisions/wc_realm_decisions.txt
  events/wc_title_events.txt
  events/wc_undead_events.txt
  gfx/flags/d_forsaken.tga
  localisation/000_Other_title_names.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/wc_culture_buildings.csv
  localisation/wc_cultures.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:, :star: new feature :new:

#1139 2nd History Remarks
  common/dynasties/1_azerothian.txt
  common/dynasties/20000_high_elf.txt
  common/dynasties/2000_orc.txt
  common/dynasties/30000_lordaeronian.txt
  common/scripted_effects/wc_scripted_effects.txt
  history/characters/10000_orc.txt
  history/characters/1_azerothian.txt
  history/characters/42000_high_elf.txt
  history/characters/58000_alteraci.txt
  history/characters/60000_lordaeronian.txt
  history/titles/b_cathedral_square.txt
  history/titles/d_church_of_the_holy_light.txt
  history/titles/d_ravenholdt.txt
  history/titles/k_stormwind.txt
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium, :star: new feature :new:

#1007 Merger with Lich King
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_trait_scripted_effects.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/wc_undead_decisions.txt
  events/wc_third_war_events.txt
  events/wc_undead_events.txt
  gfx/interface/decision_icons/merge_with_champion.dds
  interface/wc_decision_icons.gfx
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1155 Localisation crusade 9
  localisation/000_Other_title_names.csv
  localisation/000_wc_military_localization.csv
  localisation/000_wc_traits.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_job_titles.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :page_facing_up: localisation :pen:

#1152 3rd History Remarks
  common/dynasties/10000_gnome.txt
  common/dynasties/4000_dwarf.txt
  common/dynasties/42000_ogre.txt
  common/nicknames/wc_nicknames.txt
  history/characters/10000_orc.txt
  history/characters/16000_gnome.txt
  history/characters/17000_28000_bronzebeard.txt
  history/characters/52000_ogre.txt
  history/characters/59000_dalaranian.txt
  history/characters/6000_gurubashi.txt
  history/characters/64000_goblin.txt
  history/titles/d_blackwater_raiders.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1132 Moving Wonders Localisation
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#1153 End of the Scourge
  common/on_actions/00_on_actions.txt
  events/wc_undead_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority medium, :star: new feature :new:

#1156 Fixed #942 Crash
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_third_war_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1159 Fixed #1154 Issue
  common/cb_types/00_cb_types.txt
  common/scripted_effects/wc_scripted_effects.txt
  events/wc_plague_events.txt
  events/wc_undead_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1053 Lich King Vision
  common/on_actions/00_on_actions.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_corruption_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/wc_fel_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :page_facing_up: localisation :pen:, :star: new feature :new:

#1164 Deleted Province Duplicates
  history/provinces/134 - GolBolar.txt
  history/provinces/230 - VanKeiki.txt
  history/provinces/254 - PeleAhjin.txt
  history/provinces/257 - QuelDanil.txt
  history/provinces/258 - ShadraAlor.txt
  history/provinces/260 - JinthaAlor.txt
  history/provinces/265 - Lower JinthaAlor.txt
  history/provinces/2919 - AnBarhan.txt
  history/provinces/2990 - ElDratir.txt
  history/provinces/3022 - JambaRrak.txt
  history/provinces/3185 - DorDanil.txt
  history/provinces/3193 - OrdilAran.txt
  history/provinces/3202 - AtelAnor.txt
  history/provinces/3229 - BashalAran.txt
  history/provinces/3237 - AmethAran.txt
  history/provinces/3243 - MorlosAran.txt
  history/provinces/3246 - EmerAran.txt
  history/provinces/3293 - KelTheril.txt
  history/provinces/3294 - SnowDaril.txt
  history/provinces/3296 - NaeDanar.txt
  history/provinces/3310 - BwonAlor.txt
  history/provinces/3311 - ShadraDar.txt
  history/provinces/355 - QuelLithien.txt
  history/provinces/3568 - JinKalak.txt
  history/provinces/3623 - Ominous island.txt
  history/provinces/365 - TorWatha.txt
  history/provinces/367 - ZebWatha.txt
  history/provinces/53 - ZulMarash.txt
  history/provinces/60 - ZulMamwe.txt
  history/provinces/61 - ZulKunda.txt
  history/provinces/692 - ZulMashar.txt
  history/provinces/731 - DrakZin.txt
  history/provinces/732 - ZebHalak.txt
  history/provinces/755 - ZolHeb.txt
  history/provinces/756 - DubraJin.txt
  history/provinces/757 - ZolMaz.txt
  history/provinces/760 - DrakMabwa.txt
  history/provinces/761 - ZimRhuk.txt
  history/provinces/764 - ZimTorga.txt
  history/provinces/765 - HebDrakkar.txt
  history/provinces/770 - ChagaJin.txt
  history/provinces/771 - DrakSotra.txt
  history/provinces/772 - ZimAbwa.txt
  history/provinces/774 - HebValok.txt
  history/provinces/946 - BattokAlor.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#1118 Thirsty Hakkar
  .coder_resources/_unused/decisions/wc_religion_decisions.txt
  .coder_resources/_unused/events/wc_loa_events.txt
  common/bloodlines/02_earned_bloodlines.txt
  common/cb_types/01_cb_types.txt
  common/scripted_effects/03_scripted_effects_sainthood.txt
  common/scripted_score_values/00_scripted_score_values.txt
  common/traits/02_traits.txt
  common/wonders/00_wonders.txt
  decisions/HF_religious_decisions.txt
  decisions/hf_warrior_lodge_decisions.txt
  decisions/sunset_invasion.txt
  decisions/wc_religion_decisions.txt
  events/HF_battle_events.txt
  events/HF_religious_events.txt
  events/HF_warrior_lodge_powers_events.txt
  events/imprisoned_events.txt
  events/sunset_invasion.txt
  events/wc_loa_events.txt
  localisation/00_wc_vanilla_replacements.csv
Labels: :grey_exclamation: priority low, :ice_cream: vanilla modification :icecream:, :page_facing_up: localisation :pen:, :star: new feature :new:

#1170 1st Culling of Vanilla
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  decisions/HFP_holy_order_decisions.txt
  decisions/HFP_realm_decisions.txt
  events/HFP_realm_events.txt
  events/misc_old_gods_events.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:

#1169 Malfurion Not Archdruid Issue
  common/scripted_effects/wc_society_scripted_effects.txt
  history/characters/10000_orc.txt
  history/characters/52000_ogre.txt
  history/characters/59000_dalaranian.txt
  history/characters/60000_lordaeronian.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1171 4th History Remarks
  history/characters/42000_high_elf.txt
  history/characters/60000_lordaeronian.txt
  localisation/WikipediaLinks.csv
Labels: :exclamation: priority high, :star: new feature :new:

#1121 25th Bug Crusade
  .artist_resources/_unused/gfx/traits/creature_skeleton.dds
  .artist_resources/_unused/gfx/traits/skeleton.dds
  .coder_resources/List of races.txt
  .coder_resources/_unused/localisation/not_used_strings.csv
  common/on_actions/00_on_actions.txt
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_effects/wc_faction_scripted_effects.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/wc_special_traits.txt
  decisions/HL_mercenary_decisions.txt
  decisions/rip_torture_decisions.txt
  decisions/wc_offmap_decisions.txt
  events/feudal_life_events.txt
  events/polygamy_events.txt
  events/rip_treatment_events.txt
  events/tournament_events.txt
  events/wc_diplomacy_events.txt
  events/wc_offmap_events.txt
  events/wc_race_events.txt
  events/wc_realm_events.txt
  events/wc_third_war_events.txt
  events/wc_traditions_events.txt
  events/wc_undead_events.txt
  events/wc_void_events.txt
  history/characters/60000_lordaeronian.txt
  history/provinces/573 - Oomsk.txt
  history/titles/k_howling_fjord.txt
  history/titles/k_ironforge.txt
  interface/wc_traits.gfx
  localisation/00_wc_generics.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  map/terrain.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1094 Lore Human Names
  history/characters/1_azerothian.txt
  history/characters/44000_baradin.txt
  history/characters/46000_gilnean.txt
  history/characters/48000_tirassian.txt
  history/characters/53000_hillsbrad.txt
  history/characters/58000_alteraci.txt
  history/characters/60000_lordaeronian.txt
  history/characters/90000_pirate.txt
  history/titles/c_addle.txt
  history/titles/c_alther.txt
  history/titles/c_balor.txt
  history/titles/c_blackrock_pass.txt
  history/titles/c_brightwood_grove.txt
  history/titles/c_crowgate.txt
  history/titles/c_goldshire.txt
  history/titles/c_grand_hamlet.txt
  history/titles/c_khagrihm.txt
  history/titles/c_lakeshire.txt
  history/titles/c_lonely_tower.txt
  history/titles/c_misty_valley.txt
  history/titles/c_northshire.txt
  history/titles/c_raven_hill.txt
  history/titles/c_richgarden.txt
  history/titles/c_splinter_junction.txt
  history/titles/c_stonecairn.txt
  history/titles/c_stonefield.txt
  history/titles/c_stormwind.txt
  history/titles/c_tranquil_gardens.txt
  history/titles/c_westbrook.txt
  history/titles/d_elwynn.txt
  history/titles/d_stormwind.txt
  history/titles/k_stormwind.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1192 Memefixes 2
  common/game_rules/wc_unimportant_game_rules.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/sunset_invasion.txt
  decisions/wc_realm_decisions.txt
  events/wc_druidic_events.txt
  events/wc_light_events.txt
  events/wc_realm_events.txt
  events/wc_third_war_events.txt
  history/characters/10000_orc.txt
  localisation/00_wc_random_artifact_names.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/customizable_localisation/wc_2_DE_customizable_localisation_artifact_names.txt
  localisation/customizable_localisation/wc_customisable_localisation_DE.txt
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#1190 26th Bug Crusade
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/buildings/wc_castle_culture.txt
  common/buildings/wc_hospital.txt
  common/buildings/wc_temple.txt
  common/cultures/culture_murloc.txt
  common/on_actions/00_on_actions.txt
  common/scripted_effects/wc_scripted_effects.txt
  decisions/wc_society_decisions.txt
  events/wc_dark_cult_events.txt
  events/wc_undead_events.txt
  history/characters/78000_gorloc.txt
  interface/portrait_properties/00_portrait_properties.txt
  localisation/00_wc_sad.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
  localisation/wc_religion_buildings.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1209 Memefixes 3
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/01_artifacts_books.txt
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_onehanded_generic.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded_generic.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded_runeblades_generic.txt
  common/artifacts/908_wc_artifacts_relic.txt
  common/scripted_triggers/wc_scripted_artifacts_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_war_decisions.txt
  localisation/00_zuwc_united_localisation.csv
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority medium, :wrench: bug fix :hammer:

#1217 Can Interact Triggers
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/wc_test_decisions.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1240 Giftable artifacts
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/artifacts/901_wc_artifacts_weapon_twohanded.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  common/artifacts/908_wc_artifacts_relic.txt
  common/artifacts/909_wc_artifacts_library.txt
  common/artifacts/909_wc_artifacts_library_librams.txt
  common/artifacts/910_wc_artifacts_leader.txt
  localisation/00_zuwc_united_localisation.csv
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority low

#1147 Write down whispers
  common/artifacts/909_wc_artifacts_library.txt
  common/event_modifiers/wc_cooldown_modifiers.txt
  common/event_modifiers/wc_event_modifiers.txt
  common/scripted_triggers/wc_society_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/mnm_hermetics_decisions.txt
  events/wc_on_action_events.txt
  events/wc_society_events.txt
  gfx/event_pictures/madness.tga
  gfx/interface/inventory/artifacts/old_god_book_green.dds
  gfx/interface/inventory/artifacts/old_god_book_green_small.dds
  gfx/interface/inventory/artifacts/old_god_book_purple.dds
  gfx/interface/inventory/artifacts/old_god_book_purple_small.dds
  gfx/interface/inventory/artifacts/old_god_book_red.dds
  gfx/interface/inventory/artifacts/old_god_book_red_small.dds
  gfx/interface/inventory/artifacts/old_god_book_yellow.dds
  gfx/interface/inventory/artifacts/old_god_book_yellow_small.dds
  interface/wc_event_pictures.gfx
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/customizable_localisation/wc_customizable_localisation_cooldowns.txt
Labels: :grey_exclamation: priority medium, :ice_cream: vanilla modification :icecream:, :star: new feature :new:

#1124 Old Gods Sacrifice Decisions Rework
  common/scripted_effects/wc_sacrifice_scripted_effects.txt
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_religious_triggers.txt
  common/scripted_triggers/wc_sacrifice_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/societies/wc_societies.txt
  decisions/HF_religious_decisions.txt
  decisions/mnm_society_decisions.txt
  decisions/sunset_invasion.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_united_sacrifice_decision.txt
  events/HF_religious_events.txt
  events/mnm_devil_worshipers_events.txt
  gfx/interface/special_decision_icons/old_gods_sacrifice_decision.dds
  interface/domestic_offmaps.gui
  interface/wc_domestic_diplomacy.gfx
  localisation/00_wc_offmap.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:, :star: new feature :new:

#1244 can_has_sexual_relation_with_prev Issue
  events/HF_coronation_events.txt
  events/HF_sway_events.txt
  events/mnm_monastic_orders_events.txt
  events/rip_flavor_events.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1207 Replaced from_society_sacrifice_root_effect
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  decisions/wc_class_decisions.txt
Labels: :exclamation: priority high, :hammer: maintenance :wrench:
