Repository Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth, pull requests merged in 2020-03, with the labels that each got.

#1157 Localisation crusade 10
  events/wc_sad.txt
  localisation/000_Other_title_names.csv
  localisation/000_wc_traits.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_ruler_titles.csv
  localisation/00_wc_ruler_titles_castle.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_wc_wonders.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1249 Improved harpy portraits
  gfx/characters/harpy_male/harpy_male_base_1.dds
  gfx/characters/harpy_male/harpy_male_neck_1.dds
  interface/portraits/portraits_harpy.gfx
  interface/portraits/portraits_harpy_sprites.gfx
Labels: :art: graphics :paintbrush:

#943 Removing DLC Requirements from Mod 2
  common/societies/wc_societies.txt
  decisions/wc_dark_cult_decisions.txt
  events/mnm_misc_events.txt
  events/wc_dark_cult_events.txt
  events/wc_quest_events.txt
  localisation/00_wc_mnm_replace.csv
  localisation/customizable_localisation/wc_customizable_localisation_society.txt
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#1280 Fixed Reverted Nightmares Localization
  localisation/00_zuwc_united_localisation.csv
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:

#1281 27th Bug Crusade
  common/buildings/wc_hospital.txt
  common/buildings/wc_temple.txt
  common/defines/00_dummy.lua
  common/disease/wc_disease.txt
  common/scripted_effects/wc_disease_effects.txt
  common/scripted_score_values/wc_scripted_class_values.txt
  events/rip_symptom_events.txt
  events/wc_offmap_events.txt
  history/provinces/323 - Northridge.txt
  localisation/00_wc_sad.csv
  localisation/00_wc_wonders_upgrades.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority critical, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:

#1236 Refactored Old Gods Offmap Interface
  .artist_resources/_unused/gfx/interface/offmap_screens/china_dragons.dds
  common/offmap_powers/wc_offmap_cthun.txt
  common/offmap_powers/wc_offmap_nzoth.txt
  common/offmap_powers/wc_offmap_yogg_saron.txt
  common/offmap_powers/wc_offmap_yshaarj.txt
  gfx/interface/offmap_screen/button_chinese_history.dds
  gfx/interface/offmap_screen/china_divider.dds
  gfx/interface/offmap_screen/china_dynasty_frame.dds
  gfx/interface/offmap_screen/china_lionmonsterdragon.dds
  gfx/interface/offmap_screen/china_screen_button.dds
  gfx/interface/offmap_screen/mapmode_button_chinese_sphere.dds
  gfx/interface/offmap_screen/old_gods/button_old_gods_history.dds
  gfx/interface/offmap_screen/old_gods/mapmode_button_old_gods_sphere.dds
  gfx/interface/offmap_screen/old_gods/offmap_currency_old_gods_banner.dds
  gfx/interface/offmap_screen/old_gods/old_gods_background.dds
  gfx/interface/offmap_screen/old_gods/old_gods_big_banner.dds
  gfx/interface/offmap_screen/old_gods/old_gods_dislike_icon.dds
  gfx/interface/offmap_screen/old_gods/old_gods_emperor_portrait_ring.dds
  gfx/interface/offmap_screen/old_gods/old_gods_give_gift_button.dds
  gfx/interface/offmap_screen/old_gods/old_gods_hostile_action_button.dds
  gfx/interface/offmap_screen/old_gods/old_gods_like_icon.dds
  gfx/interface/offmap_screen/old_gods/old_gods_policy.dds
  gfx/interface/offmap_screen/old_gods/old_gods_recieve_gift_button.dds
  gfx/interface/offmap_screen/old_gods/old_gods_ruler_banner.dds
  gfx/interface/offmap_screen/old_gods/old_gods_screen_button.dds
  gfx/interface/offmap_screen/old_gods/old_gods_status.dds
  gfx/interface/offmap_screen/old_gods/old_gods_symbol_frame.dds
  gfx/interface/offmap_screen/old_gods/round_close_button.dds
  gfx/interface/offmap_screen/silk_road_blocked.dds
  gfx/interface/offmap_screen/trade_post_map_icon.dds
  interface/domestic_offmaps.gfx
  interface/wc_domestic_offmap_old_gods.gui
  interface/wc_domestic_offmaps.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1274 15th Small Improvments
  common/bloodlines/wc_bloodlines.txt
  common/bloodlines/wc_earned_bloodlines.txt
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/scripted_triggers/wc_society_scripted_triggers.txt
  common/traits/02_traits.txt
  common/traits/wc_race_traits.txt
  common/traits/wc_special_traits.txt
  decisions/mnm_society_decisions.txt
  events/mnm_devil_worshipers_events.txt
  events/wc_ai_cleanup_events.txt
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high, :star: new feature :new:

#1292 Sorting Generic Artifact Files
  common/artifacts/904_wc_artifacts_amulets_generic.txt
  common/artifacts/907_wc_artifacts_rings_generic.txt
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_1.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_2_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_2_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_2_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_2_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_2_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_3_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_3_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_3_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_3_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_3_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_4_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_4_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_4_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_4_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_4_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_5_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_5_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_5_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_5_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/amulet_5_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_1.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_2_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_2_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_2_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_2_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_2_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_3_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_3_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_3_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_3_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_3_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_4_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_4_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_4_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_4_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_4_stewardship.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_5_diplomacy.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_5_intrigue.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_5_learning.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_5_martial.dds
  gfx/interface/inventory/artifacts/jewelry_generic/ring_5_stewardship.dds
  interface/wc_treasury.gfx
  interface/wc_treasury_generic.gfx
Labels: :grey_exclamation: priority medium, :hammer: maintenance :wrench:

#1291 Titan family rework
  common/dynasties/150000_titan.txt
  common/dynasties/90000_nraqi.txt
  common/nicknames/wc_nicknames.txt
  history/characters/120000_nraqi.txt
  history/characters/400000_titan.txt
  localisation/00_wc_sad.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1126 Decision to Sacrifice All Prisoners
  common/scripted_triggers/wc_sacrifice_scripted_triggers.txt
  decisions/wc_offmap_decisions.txt
  decisions/wc_united_sacrifice_decision.txt
  interface/wc_decision_icons.gfx
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1182 Sacrifices at Twilight Altar
  events/HF_religious_events.txt
Labels: :grey_exclamation: priority low, :page_facing_up: localisation :pen:, :star: new feature :new:

#1210 Sacrifice Points Adaptation
  common/scripted_effects/00_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  common/traits/02_traits.txt
  events/HF_religious_events.txt
Labels: :grey_exclamation: priority low, :ice_cream: vanilla modification :icecream:, :wrench: bug fix :hammer:

#1286 Reginald Windsor and Ironfoe
  common/artifacts/901_wc_artifacts_weapon_onehanded.txt
  common/dynasties/1_azerothian.txt
  common/scripted_effects/wc_artifacts_historical_scripted_effects.txt
  history/characters/1_azerothian.txt
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority medium, :page_facing_up: localisation :pen:

#1193 Dynamic Event Pictures
  common/scripted_effects/wc_sacrifice_scripted_effects.txt
  events/HF_religious_events.txt
  events/sunset_invasion.txt
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1308 Demonic holding icons
  .artist_resources/holdings/eredargfx/arts/Shadowmoon-Valley-Portal-World-Legion(1x1).jpg
  common/cultures/culture_satyr.txt
  common/religions/fel_group.txt
  gfx/interface/holdings/eredargfx/province_capital_settlement_frame_eredargfx.dds
  gfx/interface/holdings/eredargfx/province_settlement_frame_eredargfx.dds
  gfx/interface/holdings/eredargfx/settlement_building_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_castle_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_castle_eredargfx_looted.tga
  gfx/interface/holdings/eredargfx/settlement_city_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_city_eredargfx_looted.tga
  gfx/interface/holdings/eredargfx/settlement_new_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_temple_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_temple_eredargfx_looted.tga
  gfx/interface/holdings/eredargfx/settlement_tribal_empty_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_tribal_eredargfx.tga
  gfx/interface/holdings/eredargfx/settlement_tribal_eredargfx_looted.tga
  gfx/interface/holdings/lichgfx/settlement_building_lichgfx.tga
  gfx/interface/holdings/orcgfx/settlement_temple_orcgfx.tga
  gfx/interface/holdings/orcgfx/settlement_temple_orcgfx_looted.tga
  interface/wc_holdings.gfx
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1179 Librams that make sense
  common/artifacts/909_wc_artifacts_library_librams.txt
  decisions/wc_class_decisions.txt
  events/wc_class_events.txt
Labels: :balance_scale: balance :balance_scale:, :exclamation: priority high

#1318 Fixed #1316 + renames
  .coder_resources/Pandaria.xlsx
  localisation/00_Province_names.csv
  map/climate.txt
  map/default.map
  map/definition.csv
  map/provinceDef.xls
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1261 11th Localization Crusade
  .coder_resources/_unused/localisation/not_used_strings.csv
  localisation/000_wc_military_localization.csv
  localisation/00_DEwc_united_localisation.csv
  localisation/00_memewc_united_localisation.csv
  localisation/00_wc_artifact_localisation.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customisable_localisation_DE.txt
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:

#1320 Adding the Belt of Anduin Lothar
  common/artifact_spawns/wc_artifact_spawns.txt
  common/artifacts/906_wc_artifacts_ceremonial_torso.txt
  gfx/interface/inventory/artifacts/belt_of_lothar.dds
  gfx/interface/inventory/artifacts/belt_of_lothar_small.dds
  interface/wc_treasury.gfx
  localisation/00_wc_artifact_localisation.csv
Labels: :star: new feature :new:

#1315 Tidesages can convert to secret religions
  common/scripted_effects/wc_vanilla_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/mnm_secret_religious_societies_decisions.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1329 South Seas and Ulduar model positions
  map/positions.txt
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1337 Added flags for old god heralds
  gfx/flags/e_herald_cthun.tga
  gfx/flags/e_herald_nzoth.tga
  gfx/flags/e_herald_yoggsaron.tga
  gfx/flags/e_herald_yshaarj.tga
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority low

#1327 Constellar's Minors 1
  common/dynasties/128000_night_elf.txt
  common/dynasties/20000_high_elf.txt
  history/characters/340000_night_elf.txt
  history/characters/42000_high_elf.txt
  localisation/WikipediaLinks.csv
Labels: :grey_exclamation: priority low, :star: new feature :new:

#1344 Changed holy sites to Ulduar and same for yogg-saron's herald title capital
  common/landed_titles/wc_titular_titles.txt
  common/landed_titles/z_holy_sites.txt
Labels: :exclamation: priority high, :star: new feature :new:

#1333 August Celestials religion icon
  .artist_resources/religions/pandaren.xcf
  gfx/interface/religion_icon_strip.dds
  gfx/interface/religion_icon_strip_big.dds
  gfx/interface/religion_icon_strip_small.dds
Labels: :art: graphics :paintbrush:, :grey_exclamation: priority medium

#1355 Non-whitish humans
  interface/portraits/portraits_human.gfx
Labels: :art: graphics :paintbrush:, :exclamation: priority high

#1347 Changes to request power and follower of old god modifiers
  common/event_modifiers/wc_event_modifiers.txt
Labels: :balance_scale: balance :balance_scale:, :grey_exclamation: priority medium

#1307 Old god wonders
  common/modifier_definitions/wc_text_modifier_definitions.txt
  common/retinue_subunits/00_retinue_subunits.txt
  common/wonder_upgrades/wc_wonders_historical_upgrades.txt
  common/wonders/wc_wonders_historical.txt
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ahnqiraj_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_shrine_of_storms_small.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_large.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_medium.dds
  gfx/interface/wonder_interface/wonder_strips/wonder_strip_ulduar_small.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_crucible_of_storms.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_forge_of_wills.dds
  gfx/interface/wonder_interface/wonder_upgrades/upgrade_icon_silithid_greathive.dds
  history/provinces/2956 - Ahnqiraj.txt
  history/provinces/3545 - Sagehold.txt
  history/provinces/858 - Ulduar.txt
  interface/wc_wonder.gfx
  localisation/000_wc_military_localization.csv
  localisation/00_wc_sad.csv
  localisation/00_wc_wonders.csv
  localisation/00_wc_wonders_upgrades.csv
Labels: :art: graphics :paintbrush:, :exclamation: priority high, :star: new feature :new:

#1351 28th Bug Crusade
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_effects/wc_war_scripted_effects.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  decisions/HF_sway_antagonize_decisions.txt
  events/HF_sway_events.txt
  events/rip_flavor_events.txt
  events/wc_court_events.txt
  events/wc_undead_events.txt
  history/characters/10000_orc.txt
  localisation/000_Other_title_names.csv
Labels: :exclamation: priority critical, :wrench: bug fix :hammer:

#1219 Killing Plot Adaptation
  common/game_rules/wc_unimportant_game_rules.txt
  common/scripted_effects/wc_scripted_effects.txt
  common/scripted_score_values/wc_scripted_score_values.txt
  common/scripted_triggers/wc_class_scripted_triggers.txt
  common/scripted_triggers/wc_scripted_plot_triggers.txt
  common/scripted_triggers/wc_scripted_triggers.txt
  events/cm_murder_plot_events.txt
  events/plot_events.txt
  localisation/00_wc_vanilla_replacements.csv
  localisation/00_zuwc_united_localisation.csv
  localisation/customizable_localisation/wc_customizable_localisation.txt
Labels: :exclamation: priority high, :page_facing_up: localisation :pen:, :wrench: bug fix :hammer:
